// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package raydium_launchpad

// Account discriminators
var (
	Account_GlobalConfig   = [8]byte{149, 8, 156, 202, 160, 252, 176, 217}
	Account_PlatformConfig = [8]byte{160, 78, 128, 0, 248, 83, 230, 160}
	Account_PoolState      = [8]byte{247, 237, 227, 245, 215, 195, 222, 70}
	Account_VestingRecord  = [8]byte{106, 243, 221, 205, 230, 126, 85, 83}
)

// Event discriminators
var (
	Event_ClaimVestedEvent   = [8]byte{21, 194, 114, 87, 120, 211, 226, 32}
	Event_CreateVestingEvent = [8]byte{150, 152, 11, 179, 52, 210, 191, 125}
	Event_PoolCreateEvent    = [8]byte{151, 215, 226, 9, 118, 161, 115, 174}
	Event_TradeEvent         = [8]byte{189, 219, 127, 211, 78, 230, 97, 238}
)

// Instruction discriminators
var (
	Instruction_BuyExactIn                   = [8]byte{250, 234, 13, 123, 213, 156, 19, 236}
	Instruction_BuyExactOut                  = [8]byte{24, 211, 116, 40, 105, 3, 153, 56}
	Instruction_ClaimCreatorFee              = [8]byte{26, 97, 138, 203, 132, 171, 141, 252}
	Instruction_ClaimPlatformFee             = [8]byte{156, 39, 208, 135, 76, 237, 61, 72}
	Instruction_ClaimPlatformFeeFromVault    = [8]byte{117, 241, 198, 168, 248, 218, 80, 29}
	Instruction_ClaimVestedToken             = [8]byte{49, 33, 104, 30, 189, 157, 79, 35}
	Instruction_CollectFee                   = [8]byte{60, 173, 247, 103, 4, 93, 130, 48}
	Instruction_CollectMigrateFee            = [8]byte{255, 186, 150, 223, 235, 118, 201, 186}
	Instruction_CreateConfig                 = [8]byte{201, 207, 243, 114, 75, 111, 47, 189}
	Instruction_CreatePlatformConfig         = [8]byte{176, 90, 196, 175, 253, 113, 220, 20}
	Instruction_CreatePlatformVestingAccount = [8]byte{146, 71, 173, 69, 98, 19, 15, 106}
	Instruction_CreateVestingAccount         = [8]byte{129, 178, 2, 13, 217, 172, 230, 218}
	Instruction_Initialize                   = [8]byte{175, 175, 109, 31, 13, 152, 155, 237}
	Instruction_InitializeV2                 = [8]byte{67, 153, 175, 39, 218, 16, 38, 32}
	Instruction_InitializeWithToken2022      = [8]byte{37, 190, 126, 222, 44, 154, 171, 17}
	Instruction_MigrateToAmm                 = [8]byte{207, 82, 192, 145, 254, 207, 145, 223}
	Instruction_MigrateToCpswap              = [8]byte{136, 92, 200, 103, 28, 218, 144, 140}
	Instruction_RemovePlatformCurveParam     = [8]byte{27, 30, 62, 169, 93, 224, 24, 145}
	Instruction_SellExactIn                  = [8]byte{149, 39, 222, 155, 211, 124, 152, 26}
	Instruction_SellExactOut                 = [8]byte{95, 200, 71, 34, 8, 9, 11, 166}
	Instruction_UpdateConfig                 = [8]byte{29, 158, 252, 191, 10, 83, 219, 99}
	Instruction_UpdatePlatformConfig         = [8]byte{195, 60, 76, 129, 146, 45, 67, 143}
	Instruction_UpdatePlatformCurveParam     = [8]byte{138, 144, 138, 250, 220, 128, 4, 57}
)
