// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package raydium_cp_swap

// Account discriminators
var (
	Account_AmmConfig        = [8]byte{218, 244, 33, 104, 203, 203, 43, 111}
	Account_ObservationState = [8]byte{122, 174, 197, 53, 129, 9, 165, 132}
	Account_Permission       = [8]byte{224, 83, 28, 79, 10, 253, 161, 28}
	Account_PoolState        = [8]byte{247, 237, 227, 245, 215, 195, 222, 70}
)

// Event discriminators
var (
	Event_LpChangeEvent = [8]byte{121, 163, 205, 201, 57, 218, 117, 60}
	Event_SwapEvent     = [8]byte{64, 198, 205, 232, 38, 8, 113, 226}
)

// Instruction discriminators
var (
	Instruction_ClosePermissionPda       = [8]byte{156, 84, 32, 118, 69, 135, 70, 123}
	Instruction_CollectCreatorFee        = [8]byte{20, 22, 86, 123, 198, 28, 219, 132}
	Instruction_CollectFundFee           = [8]byte{167, 138, 78, 149, 223, 194, 6, 126}
	Instruction_CollectProtocolFee       = [8]byte{136, 136, 252, 221, 194, 66, 126, 89}
	Instruction_CreateAmmConfig          = [8]byte{137, 52, 237, 212, 215, 117, 108, 104}
	Instruction_CreatePermissionPda      = [8]byte{135, 136, 2, 216, 137, 169, 181, 202}
	Instruction_Deposit                  = [8]byte{242, 35, 198, 137, 82, 225, 242, 182}
	Instruction_Initialize               = [8]byte{175, 175, 109, 31, 13, 152, 155, 237}
	Instruction_InitializeWithPermission = [8]byte{63, 55, 254, 65, 49, 178, 89, 121}
	Instruction_SwapBaseInput            = [8]byte{143, 190, 90, 218, 196, 30, 51, 222}
	Instruction_SwapBaseOutput           = [8]byte{55, 217, 98, 86, 163, 74, 180, 173}
	Instruction_UpdateAmmConfig          = [8]byte{49, 60, 174, 136, 154, 28, 116, 200}
	Instruction_UpdatePoolStatus         = [8]byte{130, 87, 108, 6, 46, 224, 117, 123}
	Instruction_Withdraw                 = [8]byte{183, 18, 70, 156, 148, 109, 161, 34}
)
