// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package raydium_cp_swap

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Holds the current owner of the factory
type AmmConfig struct {
	// Bump to identify PDA
	Bump uint8 `json:"bump"`

	// Status to control if new pool can be create
	DisableCreatePool bool `json:"disableCreatePool"`

	// Config index
	Index uint16 `json:"index"`

	// The trade fee, denominated in hundredths of a bip (10^-6)
	TradeFeeRate uint64 `json:"tradeFeeRate"`

	// The protocol fee
	ProtocolFeeRate uint64 `json:"protocolFeeRate"`

	// The fund fee, denominated in hundredths of a bip (10^-6)
	FundFeeRate uint64 `json:"fundFeeRate"`

	// Fee for create a new pool
	CreatePoolFee uint64 `json:"createPoolFee"`

	// Address of the protocol fee owner
	ProtocolOwner solanago.PublicKey `json:"protocolOwner"`

	// Address of the fund fee owner
	FundOwner solanago.PublicKey `json:"fundOwner"`

	// The pool creator fee, denominated in hundredths of a bip (10^-6)
	CreatorFeeRate uint64 `json:"creatorFeeRate"`

	// padding
	Padding [15]uint64 `json:"padding"`
}

func (obj AmmConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `DisableCreatePool`:
	err = encoder.Encode(obj.DisableCreatePool)
	if err != nil {
		return errors.NewField("DisableCreatePool", err)
	}
	// Serialize `Index`:
	err = encoder.Encode(obj.Index)
	if err != nil {
		return errors.NewField("Index", err)
	}
	// Serialize `TradeFeeRate`:
	err = encoder.Encode(obj.TradeFeeRate)
	if err != nil {
		return errors.NewField("TradeFeeRate", err)
	}
	// Serialize `ProtocolFeeRate`:
	err = encoder.Encode(obj.ProtocolFeeRate)
	if err != nil {
		return errors.NewField("ProtocolFeeRate", err)
	}
	// Serialize `FundFeeRate`:
	err = encoder.Encode(obj.FundFeeRate)
	if err != nil {
		return errors.NewField("FundFeeRate", err)
	}
	// Serialize `CreatePoolFee`:
	err = encoder.Encode(obj.CreatePoolFee)
	if err != nil {
		return errors.NewField("CreatePoolFee", err)
	}
	// Serialize `ProtocolOwner`:
	err = encoder.Encode(obj.ProtocolOwner)
	if err != nil {
		return errors.NewField("ProtocolOwner", err)
	}
	// Serialize `FundOwner`:
	err = encoder.Encode(obj.FundOwner)
	if err != nil {
		return errors.NewField("FundOwner", err)
	}
	// Serialize `CreatorFeeRate`:
	err = encoder.Encode(obj.CreatorFeeRate)
	if err != nil {
		return errors.NewField("CreatorFeeRate", err)
	}
	// Serialize `Padding`:
	err = encoder.Encode(obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj AmmConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AmmConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AmmConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `DisableCreatePool`:
	err = decoder.Decode(&obj.DisableCreatePool)
	if err != nil {
		return errors.NewField("DisableCreatePool", err)
	}
	// Deserialize `Index`:
	err = decoder.Decode(&obj.Index)
	if err != nil {
		return errors.NewField("Index", err)
	}
	// Deserialize `TradeFeeRate`:
	err = decoder.Decode(&obj.TradeFeeRate)
	if err != nil {
		return errors.NewField("TradeFeeRate", err)
	}
	// Deserialize `ProtocolFeeRate`:
	err = decoder.Decode(&obj.ProtocolFeeRate)
	if err != nil {
		return errors.NewField("ProtocolFeeRate", err)
	}
	// Deserialize `FundFeeRate`:
	err = decoder.Decode(&obj.FundFeeRate)
	if err != nil {
		return errors.NewField("FundFeeRate", err)
	}
	// Deserialize `CreatePoolFee`:
	err = decoder.Decode(&obj.CreatePoolFee)
	if err != nil {
		return errors.NewField("CreatePoolFee", err)
	}
	// Deserialize `ProtocolOwner`:
	err = decoder.Decode(&obj.ProtocolOwner)
	if err != nil {
		return errors.NewField("ProtocolOwner", err)
	}
	// Deserialize `FundOwner`:
	err = decoder.Decode(&obj.FundOwner)
	if err != nil {
		return errors.NewField("FundOwner", err)
	}
	// Deserialize `CreatorFeeRate`:
	err = decoder.Decode(&obj.CreatorFeeRate)
	if err != nil {
		return errors.NewField("CreatorFeeRate", err)
	}
	// Deserialize `Padding`:
	err = decoder.Decode(&obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj *AmmConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AmmConfig: %w", err)
	}
	return nil
}

func UnmarshalAmmConfig(buf []byte) (*AmmConfig, error) {
	obj := new(AmmConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type CreatorFeeOn binary.BorshEnum

const (
	CreatorFeeOn_BothToken CreatorFeeOn = iota
	CreatorFeeOn_OnlyToken0
	CreatorFeeOn_OnlyToken1
)

func (value CreatorFeeOn) String() string {
	switch value {
	case CreatorFeeOn_BothToken:
		return "BothToken"
	case CreatorFeeOn_OnlyToken0:
		return "OnlyToken0"
	case CreatorFeeOn_OnlyToken1:
		return "OnlyToken1"
	default:
		return ""
	}
}

// Emitted when deposit and withdraw
type LpChangeEvent struct {
	PoolId         solanago.PublicKey `json:"poolId"`
	LpAmountBefore uint64             `json:"lpAmountBefore"`

	// pool vault sub trade fees
	Token0VaultBefore uint64 `json:"token0VaultBefore"`

	// pool vault sub trade fees
	Token1VaultBefore uint64 `json:"token1VaultBefore"`

	// calculate result without transfer fee
	Token0Amount uint64 `json:"token0Amount"`

	// calculate result without transfer fee
	Token1Amount      uint64 `json:"token1Amount"`
	Token0TransferFee uint64 `json:"token0TransferFee"`
	Token1TransferFee uint64 `json:"token1TransferFee"`
	ChangeType        uint8  `json:"changeType"`
}

func (obj LpChangeEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PoolId`:
	err = encoder.Encode(obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Serialize `LpAmountBefore`:
	err = encoder.Encode(obj.LpAmountBefore)
	if err != nil {
		return errors.NewField("LpAmountBefore", err)
	}
	// Serialize `Token0VaultBefore`:
	err = encoder.Encode(obj.Token0VaultBefore)
	if err != nil {
		return errors.NewField("Token0VaultBefore", err)
	}
	// Serialize `Token1VaultBefore`:
	err = encoder.Encode(obj.Token1VaultBefore)
	if err != nil {
		return errors.NewField("Token1VaultBefore", err)
	}
	// Serialize `Token0Amount`:
	err = encoder.Encode(obj.Token0Amount)
	if err != nil {
		return errors.NewField("Token0Amount", err)
	}
	// Serialize `Token1Amount`:
	err = encoder.Encode(obj.Token1Amount)
	if err != nil {
		return errors.NewField("Token1Amount", err)
	}
	// Serialize `Token0TransferFee`:
	err = encoder.Encode(obj.Token0TransferFee)
	if err != nil {
		return errors.NewField("Token0TransferFee", err)
	}
	// Serialize `Token1TransferFee`:
	err = encoder.Encode(obj.Token1TransferFee)
	if err != nil {
		return errors.NewField("Token1TransferFee", err)
	}
	// Serialize `ChangeType`:
	err = encoder.Encode(obj.ChangeType)
	if err != nil {
		return errors.NewField("ChangeType", err)
	}
	return nil
}

func (obj LpChangeEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding LpChangeEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *LpChangeEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PoolId`:
	err = decoder.Decode(&obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Deserialize `LpAmountBefore`:
	err = decoder.Decode(&obj.LpAmountBefore)
	if err != nil {
		return errors.NewField("LpAmountBefore", err)
	}
	// Deserialize `Token0VaultBefore`:
	err = decoder.Decode(&obj.Token0VaultBefore)
	if err != nil {
		return errors.NewField("Token0VaultBefore", err)
	}
	// Deserialize `Token1VaultBefore`:
	err = decoder.Decode(&obj.Token1VaultBefore)
	if err != nil {
		return errors.NewField("Token1VaultBefore", err)
	}
	// Deserialize `Token0Amount`:
	err = decoder.Decode(&obj.Token0Amount)
	if err != nil {
		return errors.NewField("Token0Amount", err)
	}
	// Deserialize `Token1Amount`:
	err = decoder.Decode(&obj.Token1Amount)
	if err != nil {
		return errors.NewField("Token1Amount", err)
	}
	// Deserialize `Token0TransferFee`:
	err = decoder.Decode(&obj.Token0TransferFee)
	if err != nil {
		return errors.NewField("Token0TransferFee", err)
	}
	// Deserialize `Token1TransferFee`:
	err = decoder.Decode(&obj.Token1TransferFee)
	if err != nil {
		return errors.NewField("Token1TransferFee", err)
	}
	// Deserialize `ChangeType`:
	err = decoder.Decode(&obj.ChangeType)
	if err != nil {
		return errors.NewField("ChangeType", err)
	}
	return nil
}

func (obj *LpChangeEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling LpChangeEvent: %w", err)
	}
	return nil
}

func UnmarshalLpChangeEvent(buf []byte) (*LpChangeEvent, error) {
	obj := new(LpChangeEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// The element of observations in ObservationState
type Observation struct {
	// The block timestamp of the observation
	BlockTimestamp uint64 `json:"blockTimestamp"`

	// the cumulative of token0 price during the duration time, Q32.32, the remaining 64 bit for overflow
	CumulativeToken0PriceX32 binary.Uint128 `json:"cumulativeToken0PriceX32"`

	// the cumulative of token1 price during the duration time, Q32.32, the remaining 64 bit for overflow
	CumulativeToken1PriceX32 binary.Uint128 `json:"cumulativeToken1PriceX32"`
}

func (obj Observation) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `BlockTimestamp`:
	err = encoder.Encode(obj.BlockTimestamp)
	if err != nil {
		return errors.NewField("BlockTimestamp", err)
	}
	// Serialize `CumulativeToken0PriceX32`:
	err = encoder.Encode(obj.CumulativeToken0PriceX32)
	if err != nil {
		return errors.NewField("CumulativeToken0PriceX32", err)
	}
	// Serialize `CumulativeToken1PriceX32`:
	err = encoder.Encode(obj.CumulativeToken1PriceX32)
	if err != nil {
		return errors.NewField("CumulativeToken1PriceX32", err)
	}
	return nil
}

func (obj Observation) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Observation: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Observation) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `BlockTimestamp`:
	err = decoder.Decode(&obj.BlockTimestamp)
	if err != nil {
		return errors.NewField("BlockTimestamp", err)
	}
	// Deserialize `CumulativeToken0PriceX32`:
	err = decoder.Decode(&obj.CumulativeToken0PriceX32)
	if err != nil {
		return errors.NewField("CumulativeToken0PriceX32", err)
	}
	// Deserialize `CumulativeToken1PriceX32`:
	err = decoder.Decode(&obj.CumulativeToken1PriceX32)
	if err != nil {
		return errors.NewField("CumulativeToken1PriceX32", err)
	}
	return nil
}

func (obj *Observation) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Observation: %w", err)
	}
	return nil
}

func UnmarshalObservation(buf []byte) (*Observation, error) {
	obj := new(Observation)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ObservationState struct {
	// Whether the ObservationState is initialized
	Initialized bool `json:"initialized"`

	// the most-recently updated index of the observations array
	ObservationIndex uint16             `json:"observationIndex"`
	PoolId           solanago.PublicKey `json:"poolId"`

	// observation array
	Observations [100]Observation `json:"observations"`

	// padding for feature update
	Padding [4]uint64 `json:"padding"`
}

func (obj ObservationState) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Initialized`:
	err = encoder.Encode(obj.Initialized)
	if err != nil {
		return errors.NewField("Initialized", err)
	}
	// Serialize `ObservationIndex`:
	err = encoder.Encode(obj.ObservationIndex)
	if err != nil {
		return errors.NewField("ObservationIndex", err)
	}
	// Serialize `PoolId`:
	err = encoder.Encode(obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Serialize `Observations`:
	err = encoder.Encode(obj.Observations)
	if err != nil {
		return errors.NewField("Observations", err)
	}
	// Serialize `Padding`:
	err = encoder.Encode(obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj ObservationState) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ObservationState: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ObservationState) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Initialized`:
	err = decoder.Decode(&obj.Initialized)
	if err != nil {
		return errors.NewField("Initialized", err)
	}
	// Deserialize `ObservationIndex`:
	err = decoder.Decode(&obj.ObservationIndex)
	if err != nil {
		return errors.NewField("ObservationIndex", err)
	}
	// Deserialize `PoolId`:
	err = decoder.Decode(&obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Deserialize `Observations`:
	err = decoder.Decode(&obj.Observations)
	if err != nil {
		return errors.NewField("Observations", err)
	}
	// Deserialize `Padding`:
	err = decoder.Decode(&obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj *ObservationState) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ObservationState: %w", err)
	}
	return nil
}

func UnmarshalObservationState(buf []byte) (*ObservationState, error) {
	obj := new(ObservationState)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Holds the current owner of the factory
type Permission struct {
	// authority
	Authority solanago.PublicKey `json:"authority"`

	// padding
	Padding [30]uint64 `json:"padding"`
}

func (obj Permission) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `Padding`:
	err = encoder.Encode(obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj Permission) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Permission: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Permission) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `Padding`:
	err = decoder.Decode(&obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj *Permission) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Permission: %w", err)
	}
	return nil
}

func UnmarshalPermission(buf []byte) (*Permission, error) {
	obj := new(Permission)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type PoolState struct {
	// Which config the pool belongs
	AmmConfig solanago.PublicKey `json:"ammConfig"`

	// pool creator
	PoolCreator solanago.PublicKey `json:"poolCreator"`

	// Token A
	Token0Vault solanago.PublicKey `json:"token0Vault"`

	// Token B
	Token1Vault solanago.PublicKey `json:"token1Vault"`

	// Pool tokens are issued when A or B tokens are deposited.
	// Pool tokens can be withdrawn back to the original A or B token.
	LpMint solanago.PublicKey `json:"lpMint"`

	// Mint information for token A
	Token0Mint solanago.PublicKey `json:"token0Mint"`

	// Mint information for token B
	Token1Mint solanago.PublicKey `json:"token1Mint"`

	// token_0 program
	Token0Program solanago.PublicKey `json:"token0Program"`

	// token_1 program
	Token1Program solanago.PublicKey `json:"token1Program"`

	// observation account to store oracle data
	ObservationKey solanago.PublicKey `json:"observationKey"`
	AuthBump       uint8              `json:"authBump"`

	// Bitwise representation of the state of the pool
	// bit0, 1: disable deposit(value is 1), 0: normal
	// bit1, 1: disable withdraw(value is 2), 0: normal
	// bit2, 1: disable swap(value is 4), 0: normal
	Status         uint8 `json:"status"`
	LpMintDecimals uint8 `json:"lpMintDecimals"`

	// mint0 and mint1 decimals
	Mint0Decimals uint8 `json:"mint0Decimals"`
	Mint1Decimals uint8 `json:"mint1Decimals"`

	// True circulating supply without burns and lock ups
	LpSupply uint64 `json:"lpSupply"`

	// The amounts of token_0 and token_1 that are owed to the liquidity provider.
	ProtocolFeesToken0 uint64 `json:"protocolFeesToken0"`
	ProtocolFeesToken1 uint64 `json:"protocolFeesToken1"`
	FundFeesToken0     uint64 `json:"fundFeesToken0"`
	FundFeesToken1     uint64 `json:"fundFeesToken1"`

	// The timestamp allowed for swap in the pool.
	OpenTime uint64 `json:"openTime"`

	// recent epoch
	RecentEpoch uint64 `json:"recentEpoch"`

	// Creator fee collect mode
	// 0: both token_0 and token_1 can be used as trade fees. It depends on what the input token is when swapping
	// 1: only token_0 as trade fee
	// 2: only token_1 as trade fee
	CreatorFeeOn      uint8    `json:"creatorFeeOn"`
	EnableCreatorFee  bool     `json:"enableCreatorFee"`
	Padding1          [6]uint8 `json:"padding1"`
	CreatorFeesToken0 uint64   `json:"creatorFeesToken0"`
	CreatorFeesToken1 uint64   `json:"creatorFeesToken1"`

	// padding for future updates
	Padding [28]uint64 `json:"padding"`
}

func (obj PoolState) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `AmmConfig`:
	err = encoder.Encode(obj.AmmConfig)
	if err != nil {
		return errors.NewField("AmmConfig", err)
	}
	// Serialize `PoolCreator`:
	err = encoder.Encode(obj.PoolCreator)
	if err != nil {
		return errors.NewField("PoolCreator", err)
	}
	// Serialize `Token0Vault`:
	err = encoder.Encode(obj.Token0Vault)
	if err != nil {
		return errors.NewField("Token0Vault", err)
	}
	// Serialize `Token1Vault`:
	err = encoder.Encode(obj.Token1Vault)
	if err != nil {
		return errors.NewField("Token1Vault", err)
	}
	// Serialize `LpMint`:
	err = encoder.Encode(obj.LpMint)
	if err != nil {
		return errors.NewField("LpMint", err)
	}
	// Serialize `Token0Mint`:
	err = encoder.Encode(obj.Token0Mint)
	if err != nil {
		return errors.NewField("Token0Mint", err)
	}
	// Serialize `Token1Mint`:
	err = encoder.Encode(obj.Token1Mint)
	if err != nil {
		return errors.NewField("Token1Mint", err)
	}
	// Serialize `Token0Program`:
	err = encoder.Encode(obj.Token0Program)
	if err != nil {
		return errors.NewField("Token0Program", err)
	}
	// Serialize `Token1Program`:
	err = encoder.Encode(obj.Token1Program)
	if err != nil {
		return errors.NewField("Token1Program", err)
	}
	// Serialize `ObservationKey`:
	err = encoder.Encode(obj.ObservationKey)
	if err != nil {
		return errors.NewField("ObservationKey", err)
	}
	// Serialize `AuthBump`:
	err = encoder.Encode(obj.AuthBump)
	if err != nil {
		return errors.NewField("AuthBump", err)
	}
	// Serialize `Status`:
	err = encoder.Encode(obj.Status)
	if err != nil {
		return errors.NewField("Status", err)
	}
	// Serialize `LpMintDecimals`:
	err = encoder.Encode(obj.LpMintDecimals)
	if err != nil {
		return errors.NewField("LpMintDecimals", err)
	}
	// Serialize `Mint0Decimals`:
	err = encoder.Encode(obj.Mint0Decimals)
	if err != nil {
		return errors.NewField("Mint0Decimals", err)
	}
	// Serialize `Mint1Decimals`:
	err = encoder.Encode(obj.Mint1Decimals)
	if err != nil {
		return errors.NewField("Mint1Decimals", err)
	}
	// Serialize `LpSupply`:
	err = encoder.Encode(obj.LpSupply)
	if err != nil {
		return errors.NewField("LpSupply", err)
	}
	// Serialize `ProtocolFeesToken0`:
	err = encoder.Encode(obj.ProtocolFeesToken0)
	if err != nil {
		return errors.NewField("ProtocolFeesToken0", err)
	}
	// Serialize `ProtocolFeesToken1`:
	err = encoder.Encode(obj.ProtocolFeesToken1)
	if err != nil {
		return errors.NewField("ProtocolFeesToken1", err)
	}
	// Serialize `FundFeesToken0`:
	err = encoder.Encode(obj.FundFeesToken0)
	if err != nil {
		return errors.NewField("FundFeesToken0", err)
	}
	// Serialize `FundFeesToken1`:
	err = encoder.Encode(obj.FundFeesToken1)
	if err != nil {
		return errors.NewField("FundFeesToken1", err)
	}
	// Serialize `OpenTime`:
	err = encoder.Encode(obj.OpenTime)
	if err != nil {
		return errors.NewField("OpenTime", err)
	}
	// Serialize `RecentEpoch`:
	err = encoder.Encode(obj.RecentEpoch)
	if err != nil {
		return errors.NewField("RecentEpoch", err)
	}
	// Serialize `CreatorFeeOn`:
	err = encoder.Encode(obj.CreatorFeeOn)
	if err != nil {
		return errors.NewField("CreatorFeeOn", err)
	}
	// Serialize `EnableCreatorFee`:
	err = encoder.Encode(obj.EnableCreatorFee)
	if err != nil {
		return errors.NewField("EnableCreatorFee", err)
	}
	// Serialize `Padding1`:
	err = encoder.Encode(obj.Padding1)
	if err != nil {
		return errors.NewField("Padding1", err)
	}
	// Serialize `CreatorFeesToken0`:
	err = encoder.Encode(obj.CreatorFeesToken0)
	if err != nil {
		return errors.NewField("CreatorFeesToken0", err)
	}
	// Serialize `CreatorFeesToken1`:
	err = encoder.Encode(obj.CreatorFeesToken1)
	if err != nil {
		return errors.NewField("CreatorFeesToken1", err)
	}
	// Serialize `Padding`:
	err = encoder.Encode(obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj PoolState) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PoolState: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PoolState) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `AmmConfig`:
	err = decoder.Decode(&obj.AmmConfig)
	if err != nil {
		return errors.NewField("AmmConfig", err)
	}
	// Deserialize `PoolCreator`:
	err = decoder.Decode(&obj.PoolCreator)
	if err != nil {
		return errors.NewField("PoolCreator", err)
	}
	// Deserialize `Token0Vault`:
	err = decoder.Decode(&obj.Token0Vault)
	if err != nil {
		return errors.NewField("Token0Vault", err)
	}
	// Deserialize `Token1Vault`:
	err = decoder.Decode(&obj.Token1Vault)
	if err != nil {
		return errors.NewField("Token1Vault", err)
	}
	// Deserialize `LpMint`:
	err = decoder.Decode(&obj.LpMint)
	if err != nil {
		return errors.NewField("LpMint", err)
	}
	// Deserialize `Token0Mint`:
	err = decoder.Decode(&obj.Token0Mint)
	if err != nil {
		return errors.NewField("Token0Mint", err)
	}
	// Deserialize `Token1Mint`:
	err = decoder.Decode(&obj.Token1Mint)
	if err != nil {
		return errors.NewField("Token1Mint", err)
	}
	// Deserialize `Token0Program`:
	err = decoder.Decode(&obj.Token0Program)
	if err != nil {
		return errors.NewField("Token0Program", err)
	}
	// Deserialize `Token1Program`:
	err = decoder.Decode(&obj.Token1Program)
	if err != nil {
		return errors.NewField("Token1Program", err)
	}
	// Deserialize `ObservationKey`:
	err = decoder.Decode(&obj.ObservationKey)
	if err != nil {
		return errors.NewField("ObservationKey", err)
	}
	// Deserialize `AuthBump`:
	err = decoder.Decode(&obj.AuthBump)
	if err != nil {
		return errors.NewField("AuthBump", err)
	}
	// Deserialize `Status`:
	err = decoder.Decode(&obj.Status)
	if err != nil {
		return errors.NewField("Status", err)
	}
	// Deserialize `LpMintDecimals`:
	err = decoder.Decode(&obj.LpMintDecimals)
	if err != nil {
		return errors.NewField("LpMintDecimals", err)
	}
	// Deserialize `Mint0Decimals`:
	err = decoder.Decode(&obj.Mint0Decimals)
	if err != nil {
		return errors.NewField("Mint0Decimals", err)
	}
	// Deserialize `Mint1Decimals`:
	err = decoder.Decode(&obj.Mint1Decimals)
	if err != nil {
		return errors.NewField("Mint1Decimals", err)
	}
	// Deserialize `LpSupply`:
	err = decoder.Decode(&obj.LpSupply)
	if err != nil {
		return errors.NewField("LpSupply", err)
	}
	// Deserialize `ProtocolFeesToken0`:
	err = decoder.Decode(&obj.ProtocolFeesToken0)
	if err != nil {
		return errors.NewField("ProtocolFeesToken0", err)
	}
	// Deserialize `ProtocolFeesToken1`:
	err = decoder.Decode(&obj.ProtocolFeesToken1)
	if err != nil {
		return errors.NewField("ProtocolFeesToken1", err)
	}
	// Deserialize `FundFeesToken0`:
	err = decoder.Decode(&obj.FundFeesToken0)
	if err != nil {
		return errors.NewField("FundFeesToken0", err)
	}
	// Deserialize `FundFeesToken1`:
	err = decoder.Decode(&obj.FundFeesToken1)
	if err != nil {
		return errors.NewField("FundFeesToken1", err)
	}
	// Deserialize `OpenTime`:
	err = decoder.Decode(&obj.OpenTime)
	if err != nil {
		return errors.NewField("OpenTime", err)
	}
	// Deserialize `RecentEpoch`:
	err = decoder.Decode(&obj.RecentEpoch)
	if err != nil {
		return errors.NewField("RecentEpoch", err)
	}
	// Deserialize `CreatorFeeOn`:
	err = decoder.Decode(&obj.CreatorFeeOn)
	if err != nil {
		return errors.NewField("CreatorFeeOn", err)
	}
	// Deserialize `EnableCreatorFee`:
	err = decoder.Decode(&obj.EnableCreatorFee)
	if err != nil {
		return errors.NewField("EnableCreatorFee", err)
	}
	// Deserialize `Padding1`:
	err = decoder.Decode(&obj.Padding1)
	if err != nil {
		return errors.NewField("Padding1", err)
	}
	// Deserialize `CreatorFeesToken0`:
	err = decoder.Decode(&obj.CreatorFeesToken0)
	if err != nil {
		return errors.NewField("CreatorFeesToken0", err)
	}
	// Deserialize `CreatorFeesToken1`:
	err = decoder.Decode(&obj.CreatorFeesToken1)
	if err != nil {
		return errors.NewField("CreatorFeesToken1", err)
	}
	// Deserialize `Padding`:
	err = decoder.Decode(&obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj *PoolState) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PoolState: %w", err)
	}
	return nil
}

func UnmarshalPoolState(buf []byte) (*PoolState, error) {
	obj := new(PoolState)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted when swap
type SwapEvent struct {
	PoolId solanago.PublicKey `json:"poolId"`

	// pool vault sub trade fees
	InputVaultBefore uint64 `json:"inputVaultBefore"`

	// pool vault sub trade fees
	OutputVaultBefore uint64 `json:"outputVaultBefore"`

	// calculate result without transfer fee
	InputAmount uint64 `json:"inputAmount"`

	// calculate result without transfer fee
	OutputAmount      uint64             `json:"outputAmount"`
	InputTransferFee  uint64             `json:"inputTransferFee"`
	OutputTransferFee uint64             `json:"outputTransferFee"`
	BaseInput         bool               `json:"baseInput"`
	InputMint         solanago.PublicKey `json:"inputMint"`
	OutputMint        solanago.PublicKey `json:"outputMint"`
	TradeFee          uint64             `json:"tradeFee"`

	// Amount of fee tokens going to creator
	CreatorFee        uint64 `json:"creatorFee"`
	CreatorFeeOnInput bool   `json:"creatorFeeOnInput"`
}

func (obj SwapEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PoolId`:
	err = encoder.Encode(obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Serialize `InputVaultBefore`:
	err = encoder.Encode(obj.InputVaultBefore)
	if err != nil {
		return errors.NewField("InputVaultBefore", err)
	}
	// Serialize `OutputVaultBefore`:
	err = encoder.Encode(obj.OutputVaultBefore)
	if err != nil {
		return errors.NewField("OutputVaultBefore", err)
	}
	// Serialize `InputAmount`:
	err = encoder.Encode(obj.InputAmount)
	if err != nil {
		return errors.NewField("InputAmount", err)
	}
	// Serialize `OutputAmount`:
	err = encoder.Encode(obj.OutputAmount)
	if err != nil {
		return errors.NewField("OutputAmount", err)
	}
	// Serialize `InputTransferFee`:
	err = encoder.Encode(obj.InputTransferFee)
	if err != nil {
		return errors.NewField("InputTransferFee", err)
	}
	// Serialize `OutputTransferFee`:
	err = encoder.Encode(obj.OutputTransferFee)
	if err != nil {
		return errors.NewField("OutputTransferFee", err)
	}
	// Serialize `BaseInput`:
	err = encoder.Encode(obj.BaseInput)
	if err != nil {
		return errors.NewField("BaseInput", err)
	}
	// Serialize `InputMint`:
	err = encoder.Encode(obj.InputMint)
	if err != nil {
		return errors.NewField("InputMint", err)
	}
	// Serialize `OutputMint`:
	err = encoder.Encode(obj.OutputMint)
	if err != nil {
		return errors.NewField("OutputMint", err)
	}
	// Serialize `TradeFee`:
	err = encoder.Encode(obj.TradeFee)
	if err != nil {
		return errors.NewField("TradeFee", err)
	}
	// Serialize `CreatorFee`:
	err = encoder.Encode(obj.CreatorFee)
	if err != nil {
		return errors.NewField("CreatorFee", err)
	}
	// Serialize `CreatorFeeOnInput`:
	err = encoder.Encode(obj.CreatorFeeOnInput)
	if err != nil {
		return errors.NewField("CreatorFeeOnInput", err)
	}
	return nil
}

func (obj SwapEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SwapEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SwapEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PoolId`:
	err = decoder.Decode(&obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Deserialize `InputVaultBefore`:
	err = decoder.Decode(&obj.InputVaultBefore)
	if err != nil {
		return errors.NewField("InputVaultBefore", err)
	}
	// Deserialize `OutputVaultBefore`:
	err = decoder.Decode(&obj.OutputVaultBefore)
	if err != nil {
		return errors.NewField("OutputVaultBefore", err)
	}
	// Deserialize `InputAmount`:
	err = decoder.Decode(&obj.InputAmount)
	if err != nil {
		return errors.NewField("InputAmount", err)
	}
	// Deserialize `OutputAmount`:
	err = decoder.Decode(&obj.OutputAmount)
	if err != nil {
		return errors.NewField("OutputAmount", err)
	}
	// Deserialize `InputTransferFee`:
	err = decoder.Decode(&obj.InputTransferFee)
	if err != nil {
		return errors.NewField("InputTransferFee", err)
	}
	// Deserialize `OutputTransferFee`:
	err = decoder.Decode(&obj.OutputTransferFee)
	if err != nil {
		return errors.NewField("OutputTransferFee", err)
	}
	// Deserialize `BaseInput`:
	err = decoder.Decode(&obj.BaseInput)
	if err != nil {
		return errors.NewField("BaseInput", err)
	}
	// Deserialize `InputMint`:
	err = decoder.Decode(&obj.InputMint)
	if err != nil {
		return errors.NewField("InputMint", err)
	}
	// Deserialize `OutputMint`:
	err = decoder.Decode(&obj.OutputMint)
	if err != nil {
		return errors.NewField("OutputMint", err)
	}
	// Deserialize `TradeFee`:
	err = decoder.Decode(&obj.TradeFee)
	if err != nil {
		return errors.NewField("TradeFee", err)
	}
	// Deserialize `CreatorFee`:
	err = decoder.Decode(&obj.CreatorFee)
	if err != nil {
		return errors.NewField("CreatorFee", err)
	}
	// Deserialize `CreatorFeeOnInput`:
	err = decoder.Decode(&obj.CreatorFeeOnInput)
	if err != nil {
		return errors.NewField("CreatorFeeOnInput", err)
	}
	return nil
}

func (obj *SwapEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SwapEvent: %w", err)
	}
	return nil
}

func UnmarshalSwapEvent(buf []byte) (*SwapEvent, error) {
	obj := new(SwapEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
