// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package pump_amm

// Account discriminators
var (
	Account_BondingCurve            = [8]byte{23, 183, 248, 55, 96, 216, 172, 96}
	Account_FeeConfig               = [8]byte{143, 52, 146, 187, 219, 123, 76, 155}
	Account_GlobalConfig            = [8]byte{149, 8, 156, 202, 160, 252, 176, 217}
	Account_GlobalVolumeAccumulator = [8]byte{202, 42, 246, 43, 142, 190, 30, 255}
	Account_Pool                    = [8]byte{241, 154, 109, 4, 17, 177, 109, 188}
	Account_SharingConfig           = [8]byte{216, 74, 9, 0, 56, 140, 93, 75}
	Account_UserVolumeAccumulator   = [8]byte{86, 255, 112, 14, 102, 53, 154, 250}
)

// Event discriminators
var (
	Event_AdminSetCoinCreatorEvent        = [8]byte{45, 220, 93, 24, 25, 97, 172, 104}
	Event_AdminUpdateTokenIncentivesEvent = [8]byte{147, 250, 108, 120, 247, 29, 67, 222}
	Event_BuyEvent                        = [8]byte{103, 244, 82, 31, 44, 245, 119, 119}
	Event_ClaimTokenIncentivesEvent       = [8]byte{79, 172, 246, 49, 205, 91, 206, 232}
	Event_CloseUserVolumeAccumulatorEvent = [8]byte{146, 159, 189, 172, 146, 88, 56, 244}
	Event_CollectCoinCreatorFeeEvent      = [8]byte{232, 245, 194, 238, 234, 218, 58, 89}
	Event_CreateConfigEvent               = [8]byte{107, 52, 89, 129, 55, 226, 81, 22}
	Event_CreatePoolEvent                 = [8]byte{177, 49, 12, 210, 160, 118, 167, 116}
	Event_DepositEvent                    = [8]byte{120, 248, 61, 83, 31, 142, 107, 144}
	Event_DisableEvent                    = [8]byte{107, 253, 193, 76, 228, 202, 27, 104}
	Event_ExtendAccountEvent              = [8]byte{97, 97, 215, 144, 93, 146, 22, 124}
	Event_InitUserVolumeAccumulatorEvent  = [8]byte{134, 36, 13, 72, 232, 101, 130, 216}
	Event_MigratePoolCoinCreatorEvent     = [8]byte{170, 221, 82, 199, 147, 165, 247, 46}
	Event_ReservedFeeRecipientsEvent      = [8]byte{43, 188, 250, 18, 221, 75, 187, 95}
	Event_SellEvent                       = [8]byte{62, 47, 55, 10, 165, 3, 220, 42}
	Event_SetBondingCurveCoinCreatorEvent = [8]byte{242, 231, 235, 102, 65, 99, 189, 211}
	Event_SetMetaplexCoinCreatorEvent     = [8]byte{150, 107, 199, 123, 124, 207, 102, 228}
	Event_SyncUserVolumeAccumulatorEvent  = [8]byte{197, 122, 167, 124, 116, 81, 91, 255}
	Event_UpdateAdminEvent                = [8]byte{225, 152, 171, 87, 246, 63, 66, 234}
	Event_UpdateFeeConfigEvent            = [8]byte{90, 23, 65, 35, 62, 244, 188, 208}
	Event_WithdrawEvent                   = [8]byte{22, 9, 133, 26, 160, 44, 71, 192}
)

// Instruction discriminators
var (
	Instruction_AdminSetCoinCreator        = [8]byte{242, 40, 117, 145, 73, 96, 105, 104}
	Instruction_AdminUpdateTokenIncentives = [8]byte{209, 11, 115, 87, 213, 23, 124, 204}
	Instruction_Buy                        = [8]byte{102, 6, 61, 18, 1, 218, 235, 234}
	Instruction_BuyExactQuoteIn            = [8]byte{198, 46, 21, 82, 180, 217, 232, 112}
	Instruction_ClaimTokenIncentives       = [8]byte{16, 4, 71, 28, 204, 1, 40, 27}
	Instruction_CloseUserVolumeAccumulator = [8]byte{249, 69, 164, 218, 150, 103, 84, 138}
	Instruction_CollectCoinCreatorFee      = [8]byte{160, 57, 89, 42, 181, 139, 43, 66}
	Instruction_CreateConfig               = [8]byte{201, 207, 243, 114, 75, 111, 47, 189}
	Instruction_CreatePool                 = [8]byte{233, 146, 209, 142, 207, 104, 64, 188}
	Instruction_Deposit                    = [8]byte{242, 35, 198, 137, 82, 225, 242, 182}
	Instruction_Disable                    = [8]byte{185, 173, 187, 90, 216, 15, 238, 233}
	Instruction_ExtendAccount              = [8]byte{234, 102, 194, 203, 150, 72, 62, 229}
	Instruction_InitUserVolumeAccumulator  = [8]byte{94, 6, 202, 115, 255, 96, 232, 183}
	Instruction_MigratePoolCoinCreator     = [8]byte{208, 8, 159, 4, 74, 175, 16, 58}
	Instruction_Sell                       = [8]byte{51, 230, 133, 164, 1, 127, 131, 173}
	Instruction_SetCoinCreator             = [8]byte{210, 149, 128, 45, 188, 58, 78, 175}
	Instruction_SetReservedFeeRecipients   = [8]byte{111, 172, 162, 232, 114, 89, 213, 142}
	Instruction_SyncUserVolumeAccumulator  = [8]byte{86, 31, 192, 87, 163, 87, 79, 238}
	Instruction_ToggleMayhemMode           = [8]byte{1, 9, 111, 208, 100, 31, 255, 163}
	Instruction_TransferCreatorFeesToPump  = [8]byte{139, 52, 134, 85, 228, 229, 108, 241}
	Instruction_UpdateAdmin                = [8]byte{161, 176, 40, 213, 60, 184, 179, 228}
	Instruction_UpdateFeeConfig            = [8]byte{104, 184, 103, 242, 88, 151, 107, 20}
	Instruction_Withdraw                   = [8]byte{183, 18, 70, 156, 148, 109, 161, 34}
)
