// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the events defined in the IDL.

package pump_amm

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyEvent(eventData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek event discriminator: %w", err)
	}
	switch discriminator {
	case Event_AdminSetCoinCreatorEvent:
		value := new(AdminSetCoinCreatorEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as AdminSetCoinCreatorEvent: %w", err)
		}
		return value, nil
	case Event_AdminUpdateTokenIncentivesEvent:
		value := new(AdminUpdateTokenIncentivesEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as AdminUpdateTokenIncentivesEvent: %w", err)
		}
		return value, nil
	case Event_BuyEvent:
		value := new(BuyEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as BuyEvent: %w", err)
		}
		return value, nil
	case Event_ClaimTokenIncentivesEvent:
		value := new(ClaimTokenIncentivesEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as ClaimTokenIncentivesEvent: %w", err)
		}
		return value, nil
	case Event_CloseUserVolumeAccumulatorEvent:
		value := new(CloseUserVolumeAccumulatorEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as CloseUserVolumeAccumulatorEvent: %w", err)
		}
		return value, nil
	case Event_CollectCoinCreatorFeeEvent:
		value := new(CollectCoinCreatorFeeEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as CollectCoinCreatorFeeEvent: %w", err)
		}
		return value, nil
	case Event_CreateConfigEvent:
		value := new(CreateConfigEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as CreateConfigEvent: %w", err)
		}
		return value, nil
	case Event_CreatePoolEvent:
		value := new(CreatePoolEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as CreatePoolEvent: %w", err)
		}
		return value, nil
	case Event_DepositEvent:
		value := new(DepositEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as DepositEvent: %w", err)
		}
		return value, nil
	case Event_DisableEvent:
		value := new(DisableEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as DisableEvent: %w", err)
		}
		return value, nil
	case Event_ExtendAccountEvent:
		value := new(ExtendAccountEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as ExtendAccountEvent: %w", err)
		}
		return value, nil
	case Event_InitUserVolumeAccumulatorEvent:
		value := new(InitUserVolumeAccumulatorEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as InitUserVolumeAccumulatorEvent: %w", err)
		}
		return value, nil
	case Event_MigratePoolCoinCreatorEvent:
		value := new(MigratePoolCoinCreatorEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as MigratePoolCoinCreatorEvent: %w", err)
		}
		return value, nil
	case Event_ReservedFeeRecipientsEvent:
		value := new(ReservedFeeRecipientsEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as ReservedFeeRecipientsEvent: %w", err)
		}
		return value, nil
	case Event_SellEvent:
		value := new(SellEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SellEvent: %w", err)
		}
		return value, nil
	case Event_SetBondingCurveCoinCreatorEvent:
		value := new(SetBondingCurveCoinCreatorEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SetBondingCurveCoinCreatorEvent: %w", err)
		}
		return value, nil
	case Event_SetMetaplexCoinCreatorEvent:
		value := new(SetMetaplexCoinCreatorEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SetMetaplexCoinCreatorEvent: %w", err)
		}
		return value, nil
	case Event_SyncUserVolumeAccumulatorEvent:
		value := new(SyncUserVolumeAccumulatorEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SyncUserVolumeAccumulatorEvent: %w", err)
		}
		return value, nil
	case Event_UpdateAdminEvent:
		value := new(UpdateAdminEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as UpdateAdminEvent: %w", err)
		}
		return value, nil
	case Event_UpdateFeeConfigEvent:
		value := new(UpdateFeeConfigEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as UpdateFeeConfigEvent: %w", err)
		}
		return value, nil
	case Event_WithdrawEvent:
		value := new(WithdrawEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as WithdrawEvent: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseEvent_AdminSetCoinCreatorEvent(eventData []byte) (*AdminSetCoinCreatorEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_AdminSetCoinCreatorEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_AdminSetCoinCreatorEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(AdminSetCoinCreatorEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type AdminSetCoinCreatorEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_AdminUpdateTokenIncentivesEvent(eventData []byte) (*AdminUpdateTokenIncentivesEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_AdminUpdateTokenIncentivesEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_AdminUpdateTokenIncentivesEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(AdminUpdateTokenIncentivesEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type AdminUpdateTokenIncentivesEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_BuyEvent(eventData []byte) (*BuyEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_BuyEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_BuyEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(BuyEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type BuyEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_ClaimTokenIncentivesEvent(eventData []byte) (*ClaimTokenIncentivesEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_ClaimTokenIncentivesEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_ClaimTokenIncentivesEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(ClaimTokenIncentivesEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type ClaimTokenIncentivesEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_CloseUserVolumeAccumulatorEvent(eventData []byte) (*CloseUserVolumeAccumulatorEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_CloseUserVolumeAccumulatorEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_CloseUserVolumeAccumulatorEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(CloseUserVolumeAccumulatorEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type CloseUserVolumeAccumulatorEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_CollectCoinCreatorFeeEvent(eventData []byte) (*CollectCoinCreatorFeeEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_CollectCoinCreatorFeeEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_CollectCoinCreatorFeeEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(CollectCoinCreatorFeeEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type CollectCoinCreatorFeeEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_CreateConfigEvent(eventData []byte) (*CreateConfigEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_CreateConfigEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_CreateConfigEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(CreateConfigEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type CreateConfigEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_CreatePoolEvent(eventData []byte) (*CreatePoolEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_CreatePoolEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_CreatePoolEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(CreatePoolEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type CreatePoolEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_DepositEvent(eventData []byte) (*DepositEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_DepositEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_DepositEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(DepositEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type DepositEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_DisableEvent(eventData []byte) (*DisableEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_DisableEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_DisableEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(DisableEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type DisableEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_ExtendAccountEvent(eventData []byte) (*ExtendAccountEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_ExtendAccountEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_ExtendAccountEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(ExtendAccountEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type ExtendAccountEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_InitUserVolumeAccumulatorEvent(eventData []byte) (*InitUserVolumeAccumulatorEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_InitUserVolumeAccumulatorEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_InitUserVolumeAccumulatorEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(InitUserVolumeAccumulatorEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type InitUserVolumeAccumulatorEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_MigratePoolCoinCreatorEvent(eventData []byte) (*MigratePoolCoinCreatorEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_MigratePoolCoinCreatorEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_MigratePoolCoinCreatorEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(MigratePoolCoinCreatorEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type MigratePoolCoinCreatorEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_ReservedFeeRecipientsEvent(eventData []byte) (*ReservedFeeRecipientsEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_ReservedFeeRecipientsEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_ReservedFeeRecipientsEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(ReservedFeeRecipientsEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type ReservedFeeRecipientsEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_SellEvent(eventData []byte) (*SellEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SellEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SellEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(SellEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SellEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_SetBondingCurveCoinCreatorEvent(eventData []byte) (*SetBondingCurveCoinCreatorEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SetBondingCurveCoinCreatorEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SetBondingCurveCoinCreatorEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(SetBondingCurveCoinCreatorEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SetBondingCurveCoinCreatorEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_SetMetaplexCoinCreatorEvent(eventData []byte) (*SetMetaplexCoinCreatorEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SetMetaplexCoinCreatorEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SetMetaplexCoinCreatorEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(SetMetaplexCoinCreatorEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SetMetaplexCoinCreatorEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_SyncUserVolumeAccumulatorEvent(eventData []byte) (*SyncUserVolumeAccumulatorEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SyncUserVolumeAccumulatorEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SyncUserVolumeAccumulatorEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(SyncUserVolumeAccumulatorEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SyncUserVolumeAccumulatorEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_UpdateAdminEvent(eventData []byte) (*UpdateAdminEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_UpdateAdminEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_UpdateAdminEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(UpdateAdminEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type UpdateAdminEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_UpdateFeeConfigEvent(eventData []byte) (*UpdateFeeConfigEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_UpdateFeeConfigEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_UpdateFeeConfigEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(UpdateFeeConfigEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type UpdateFeeConfigEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_WithdrawEvent(eventData []byte) (*WithdrawEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_WithdrawEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_WithdrawEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(WithdrawEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type WithdrawEvent: %w", err)
	}
	return event, nil
}
