// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package amm_v3

// Account discriminators
var (
	Account_AmmConfig                = [8]byte{218, 244, 33, 104, 203, 203, 43, 111}
	Account_ObservationState         = [8]byte{122, 174, 197, 53, 129, 9, 165, 132}
	Account_OperationState           = [8]byte{19, 236, 58, 237, 81, 222, 183, 252}
	Account_PersonalPositionState    = [8]byte{70, 111, 150, 126, 230, 15, 25, 117}
	Account_PoolState                = [8]byte{247, 237, 227, 245, 215, 195, 222, 70}
	Account_ProtocolPositionState    = [8]byte{100, 226, 145, 99, 146, 218, 160, 106}
	Account_SupportMintAssociated    = [8]byte{134, 40, 183, 79, 12, 112, 162, 53}
	Account_TickArrayBitmapExtension = [8]byte{60, 150, 36, 219, 97, 128, 139, 153}
	Account_TickArrayState           = [8]byte{192, 155, 85, 205, 49, 249, 129, 42}
)

// Event discriminators
var (
	Event_CollectPersonalFeeEvent     = [8]byte{166, 174, 105, 192, 81, 161, 83, 105}
	Event_CollectProtocolFeeEvent     = [8]byte{206, 87, 17, 79, 45, 41, 213, 61}
	Event_ConfigChangeEvent           = [8]byte{247, 189, 7, 119, 106, 112, 95, 151}
	Event_CreatePersonalPositionEvent = [8]byte{100, 30, 87, 249, 196, 223, 154, 206}
	Event_DecreaseLiquidityEvent      = [8]byte{58, 222, 86, 58, 68, 50, 85, 56}
	Event_IncreaseLiquidityEvent      = [8]byte{49, 79, 105, 212, 32, 34, 30, 84}
	Event_LiquidityCalculateEvent     = [8]byte{237, 112, 148, 230, 57, 84, 180, 162}
	Event_LiquidityChangeEvent        = [8]byte{126, 240, 175, 206, 158, 88, 153, 107}
	Event_PoolCreatedEvent            = [8]byte{25, 94, 75, 47, 112, 99, 53, 63}
	Event_SwapEvent                   = [8]byte{64, 198, 205, 232, 38, 8, 113, 226}
	Event_UpdateRewardInfosEvent      = [8]byte{109, 127, 186, 78, 114, 65, 37, 236}
)

// Instruction discriminators
var (
	Instruction_ClosePosition               = [8]byte{123, 134, 81, 0, 49, 68, 98, 98}
	Instruction_CollectFundFee              = [8]byte{167, 138, 78, 149, 223, 194, 6, 126}
	Instruction_CollectProtocolFee          = [8]byte{136, 136, 252, 221, 194, 66, 126, 89}
	Instruction_CollectRemainingRewards     = [8]byte{18, 237, 166, 197, 34, 16, 213, 144}
	Instruction_CreateAmmConfig             = [8]byte{137, 52, 237, 212, 215, 117, 108, 104}
	Instruction_CreateOperationAccount      = [8]byte{63, 87, 148, 33, 109, 35, 8, 104}
	Instruction_CreatePool                  = [8]byte{233, 146, 209, 142, 207, 104, 64, 188}
	Instruction_CreateSupportMintAssociated = [8]byte{17, 251, 65, 92, 136, 242, 14, 169}
	Instruction_DecreaseLiquidity           = [8]byte{160, 38, 208, 111, 104, 91, 44, 1}
	Instruction_DecreaseLiquidityV2         = [8]byte{58, 127, 188, 62, 79, 82, 196, 96}
	Instruction_IncreaseLiquidity           = [8]byte{46, 156, 243, 118, 13, 205, 251, 178}
	Instruction_IncreaseLiquidityV2         = [8]byte{133, 29, 89, 223, 69, 238, 176, 10}
	Instruction_InitializeReward            = [8]byte{95, 135, 192, 196, 242, 129, 230, 68}
	Instruction_OpenPosition                = [8]byte{135, 128, 47, 77, 15, 152, 240, 49}
	Instruction_OpenPositionV2              = [8]byte{77, 184, 74, 214, 112, 86, 241, 199}
	Instruction_OpenPositionWithToken22Nft  = [8]byte{77, 255, 174, 82, 125, 29, 201, 46}
	Instruction_SetRewardParams             = [8]byte{112, 52, 167, 75, 32, 201, 211, 137}
	Instruction_Swap                        = [8]byte{248, 198, 158, 145, 225, 117, 135, 200}
	Instruction_SwapRouterBaseIn            = [8]byte{69, 125, 115, 218, 245, 186, 242, 196}
	Instruction_SwapV2                      = [8]byte{43, 4, 237, 11, 26, 201, 30, 98}
	Instruction_TransferRewardOwner         = [8]byte{7, 22, 12, 83, 242, 43, 48, 121}
	Instruction_UpdateAmmConfig             = [8]byte{49, 60, 174, 136, 154, 28, 116, 200}
	Instruction_UpdateOperationAccount      = [8]byte{127, 70, 119, 40, 188, 227, 61, 7}
	Instruction_UpdatePoolStatus            = [8]byte{130, 87, 108, 6, 46, 224, 117, 123}
	Instruction_UpdateRewardInfos           = [8]byte{163, 172, 224, 52, 11, 154, 106, 223}
)
