// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package amm_v3

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Holds the current owner of the factory
type AmmConfig struct {
	// Bump to identify PDA
	Bump  uint8  `json:"bump"`
	Index uint16 `json:"index"`

	// Address of the protocol owner
	Owner solanago.PublicKey `json:"owner"`

	// The protocol fee
	ProtocolFeeRate uint32 `json:"protocolFeeRate"`

	// The trade fee, denominated in hundredths of a bip (10^-6)
	TradeFeeRate uint32 `json:"tradeFeeRate"`

	// The tick spacing
	TickSpacing uint16 `json:"tickSpacing"`

	// The fund fee, denominated in hundredths of a bip (10^-6)
	FundFeeRate uint32             `json:"fundFeeRate"`
	PaddingU32  uint32             `json:"paddingU32"`
	FundOwner   solanago.PublicKey `json:"fundOwner"`
	Padding     [3]uint64          `json:"padding"`
}

func (obj AmmConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `Index`:
	err = encoder.Encode(obj.Index)
	if err != nil {
		return errors.NewField("Index", err)
	}
	// Serialize `Owner`:
	err = encoder.Encode(obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Serialize `ProtocolFeeRate`:
	err = encoder.Encode(obj.ProtocolFeeRate)
	if err != nil {
		return errors.NewField("ProtocolFeeRate", err)
	}
	// Serialize `TradeFeeRate`:
	err = encoder.Encode(obj.TradeFeeRate)
	if err != nil {
		return errors.NewField("TradeFeeRate", err)
	}
	// Serialize `TickSpacing`:
	err = encoder.Encode(obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Serialize `FundFeeRate`:
	err = encoder.Encode(obj.FundFeeRate)
	if err != nil {
		return errors.NewField("FundFeeRate", err)
	}
	// Serialize `PaddingU32`:
	err = encoder.Encode(obj.PaddingU32)
	if err != nil {
		return errors.NewField("PaddingU32", err)
	}
	// Serialize `FundOwner`:
	err = encoder.Encode(obj.FundOwner)
	if err != nil {
		return errors.NewField("FundOwner", err)
	}
	// Serialize `Padding`:
	err = encoder.Encode(obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj AmmConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AmmConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AmmConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `Index`:
	err = decoder.Decode(&obj.Index)
	if err != nil {
		return errors.NewField("Index", err)
	}
	// Deserialize `Owner`:
	err = decoder.Decode(&obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Deserialize `ProtocolFeeRate`:
	err = decoder.Decode(&obj.ProtocolFeeRate)
	if err != nil {
		return errors.NewField("ProtocolFeeRate", err)
	}
	// Deserialize `TradeFeeRate`:
	err = decoder.Decode(&obj.TradeFeeRate)
	if err != nil {
		return errors.NewField("TradeFeeRate", err)
	}
	// Deserialize `TickSpacing`:
	err = decoder.Decode(&obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Deserialize `FundFeeRate`:
	err = decoder.Decode(&obj.FundFeeRate)
	if err != nil {
		return errors.NewField("FundFeeRate", err)
	}
	// Deserialize `PaddingU32`:
	err = decoder.Decode(&obj.PaddingU32)
	if err != nil {
		return errors.NewField("PaddingU32", err)
	}
	// Deserialize `FundOwner`:
	err = decoder.Decode(&obj.FundOwner)
	if err != nil {
		return errors.NewField("FundOwner", err)
	}
	// Deserialize `Padding`:
	err = decoder.Decode(&obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj *AmmConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AmmConfig: %w", err)
	}
	return nil
}

func UnmarshalAmmConfig(buf []byte) (*AmmConfig, error) {
	obj := new(AmmConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted when tokens are collected for a position
type CollectPersonalFeeEvent struct {
	// The ID of the token for which underlying tokens were collected
	PositionNftMint solanago.PublicKey `json:"positionNftMint"`

	// The token account that received the collected token_0 tokens
	RecipientTokenAccount0 solanago.PublicKey `json:"recipientTokenAccount0"`

	// The token account that received the collected token_1 tokens
	RecipientTokenAccount1 solanago.PublicKey `json:"recipientTokenAccount1"`

	// The amount of token_0 owed to the position that was collected
	Amount0 uint64 `json:"amount0"`

	// The amount of token_1 owed to the position that was collected
	Amount1 uint64 `json:"amount1"`
}

func (obj CollectPersonalFeeEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PositionNftMint`:
	err = encoder.Encode(obj.PositionNftMint)
	if err != nil {
		return errors.NewField("PositionNftMint", err)
	}
	// Serialize `RecipientTokenAccount0`:
	err = encoder.Encode(obj.RecipientTokenAccount0)
	if err != nil {
		return errors.NewField("RecipientTokenAccount0", err)
	}
	// Serialize `RecipientTokenAccount1`:
	err = encoder.Encode(obj.RecipientTokenAccount1)
	if err != nil {
		return errors.NewField("RecipientTokenAccount1", err)
	}
	// Serialize `Amount0`:
	err = encoder.Encode(obj.Amount0)
	if err != nil {
		return errors.NewField("Amount0", err)
	}
	// Serialize `Amount1`:
	err = encoder.Encode(obj.Amount1)
	if err != nil {
		return errors.NewField("Amount1", err)
	}
	return nil
}

func (obj CollectPersonalFeeEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CollectPersonalFeeEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CollectPersonalFeeEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PositionNftMint`:
	err = decoder.Decode(&obj.PositionNftMint)
	if err != nil {
		return errors.NewField("PositionNftMint", err)
	}
	// Deserialize `RecipientTokenAccount0`:
	err = decoder.Decode(&obj.RecipientTokenAccount0)
	if err != nil {
		return errors.NewField("RecipientTokenAccount0", err)
	}
	// Deserialize `RecipientTokenAccount1`:
	err = decoder.Decode(&obj.RecipientTokenAccount1)
	if err != nil {
		return errors.NewField("RecipientTokenAccount1", err)
	}
	// Deserialize `Amount0`:
	err = decoder.Decode(&obj.Amount0)
	if err != nil {
		return errors.NewField("Amount0", err)
	}
	// Deserialize `Amount1`:
	err = decoder.Decode(&obj.Amount1)
	if err != nil {
		return errors.NewField("Amount1", err)
	}
	return nil
}

func (obj *CollectPersonalFeeEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CollectPersonalFeeEvent: %w", err)
	}
	return nil
}

func UnmarshalCollectPersonalFeeEvent(buf []byte) (*CollectPersonalFeeEvent, error) {
	obj := new(CollectPersonalFeeEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted when the collected protocol fees are withdrawn by the factory owner
type CollectProtocolFeeEvent struct {
	// The pool whose protocol fee is collected
	PoolState solanago.PublicKey `json:"poolState"`

	// The address that receives the collected token_0 protocol fees
	RecipientTokenAccount0 solanago.PublicKey `json:"recipientTokenAccount0"`

	// The address that receives the collected token_1 protocol fees
	RecipientTokenAccount1 solanago.PublicKey `json:"recipientTokenAccount1"`

	// The amount of token_0 protocol fees that is withdrawn
	Amount0 uint64 `json:"amount0"`

	// The amount of token_0 protocol fees that is withdrawn
	Amount1 uint64 `json:"amount1"`
}

func (obj CollectProtocolFeeEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PoolState`:
	err = encoder.Encode(obj.PoolState)
	if err != nil {
		return errors.NewField("PoolState", err)
	}
	// Serialize `RecipientTokenAccount0`:
	err = encoder.Encode(obj.RecipientTokenAccount0)
	if err != nil {
		return errors.NewField("RecipientTokenAccount0", err)
	}
	// Serialize `RecipientTokenAccount1`:
	err = encoder.Encode(obj.RecipientTokenAccount1)
	if err != nil {
		return errors.NewField("RecipientTokenAccount1", err)
	}
	// Serialize `Amount0`:
	err = encoder.Encode(obj.Amount0)
	if err != nil {
		return errors.NewField("Amount0", err)
	}
	// Serialize `Amount1`:
	err = encoder.Encode(obj.Amount1)
	if err != nil {
		return errors.NewField("Amount1", err)
	}
	return nil
}

func (obj CollectProtocolFeeEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CollectProtocolFeeEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CollectProtocolFeeEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PoolState`:
	err = decoder.Decode(&obj.PoolState)
	if err != nil {
		return errors.NewField("PoolState", err)
	}
	// Deserialize `RecipientTokenAccount0`:
	err = decoder.Decode(&obj.RecipientTokenAccount0)
	if err != nil {
		return errors.NewField("RecipientTokenAccount0", err)
	}
	// Deserialize `RecipientTokenAccount1`:
	err = decoder.Decode(&obj.RecipientTokenAccount1)
	if err != nil {
		return errors.NewField("RecipientTokenAccount1", err)
	}
	// Deserialize `Amount0`:
	err = decoder.Decode(&obj.Amount0)
	if err != nil {
		return errors.NewField("Amount0", err)
	}
	// Deserialize `Amount1`:
	err = decoder.Decode(&obj.Amount1)
	if err != nil {
		return errors.NewField("Amount1", err)
	}
	return nil
}

func (obj *CollectProtocolFeeEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CollectProtocolFeeEvent: %w", err)
	}
	return nil
}

func UnmarshalCollectProtocolFeeEvent(buf []byte) (*CollectProtocolFeeEvent, error) {
	obj := new(CollectProtocolFeeEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted when create or update a config
type ConfigChangeEvent struct {
	Index           uint16             `json:"index"`
	Owner           solanago.PublicKey `json:"owner"`
	ProtocolFeeRate uint32             `json:"protocolFeeRate"`
	TradeFeeRate    uint32             `json:"tradeFeeRate"`
	TickSpacing     uint16             `json:"tickSpacing"`
	FundFeeRate     uint32             `json:"fundFeeRate"`
	FundOwner       solanago.PublicKey `json:"fundOwner"`
}

func (obj ConfigChangeEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Index`:
	err = encoder.Encode(obj.Index)
	if err != nil {
		return errors.NewField("Index", err)
	}
	// Serialize `Owner`:
	err = encoder.Encode(obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Serialize `ProtocolFeeRate`:
	err = encoder.Encode(obj.ProtocolFeeRate)
	if err != nil {
		return errors.NewField("ProtocolFeeRate", err)
	}
	// Serialize `TradeFeeRate`:
	err = encoder.Encode(obj.TradeFeeRate)
	if err != nil {
		return errors.NewField("TradeFeeRate", err)
	}
	// Serialize `TickSpacing`:
	err = encoder.Encode(obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Serialize `FundFeeRate`:
	err = encoder.Encode(obj.FundFeeRate)
	if err != nil {
		return errors.NewField("FundFeeRate", err)
	}
	// Serialize `FundOwner`:
	err = encoder.Encode(obj.FundOwner)
	if err != nil {
		return errors.NewField("FundOwner", err)
	}
	return nil
}

func (obj ConfigChangeEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ConfigChangeEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ConfigChangeEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Index`:
	err = decoder.Decode(&obj.Index)
	if err != nil {
		return errors.NewField("Index", err)
	}
	// Deserialize `Owner`:
	err = decoder.Decode(&obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Deserialize `ProtocolFeeRate`:
	err = decoder.Decode(&obj.ProtocolFeeRate)
	if err != nil {
		return errors.NewField("ProtocolFeeRate", err)
	}
	// Deserialize `TradeFeeRate`:
	err = decoder.Decode(&obj.TradeFeeRate)
	if err != nil {
		return errors.NewField("TradeFeeRate", err)
	}
	// Deserialize `TickSpacing`:
	err = decoder.Decode(&obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Deserialize `FundFeeRate`:
	err = decoder.Decode(&obj.FundFeeRate)
	if err != nil {
		return errors.NewField("FundFeeRate", err)
	}
	// Deserialize `FundOwner`:
	err = decoder.Decode(&obj.FundOwner)
	if err != nil {
		return errors.NewField("FundOwner", err)
	}
	return nil
}

func (obj *ConfigChangeEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ConfigChangeEvent: %w", err)
	}
	return nil
}

func UnmarshalConfigChangeEvent(buf []byte) (*ConfigChangeEvent, error) {
	obj := new(ConfigChangeEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted when create a new position
type CreatePersonalPositionEvent struct {
	// The pool for which liquidity was added
	PoolState solanago.PublicKey `json:"poolState"`

	// The address that create the position
	Minter solanago.PublicKey `json:"minter"`

	// The owner of the position and recipient of any minted liquidity
	NftOwner solanago.PublicKey `json:"nftOwner"`

	// The lower tick of the position
	TickLowerIndex int32 `json:"tickLowerIndex"`

	// The upper tick of the position
	TickUpperIndex int32 `json:"tickUpperIndex"`

	// The amount of liquidity minted to the position range
	Liquidity binary.Uint128 `json:"liquidity"`

	// The amount of token_0 was deposit for the liquidity
	DepositAmount0 uint64 `json:"depositAmount0"`

	// The amount of token_1 was deposit for the liquidity
	DepositAmount1 uint64 `json:"depositAmount1"`

	// The token transfer fee for deposit_amount_0
	DepositAmount0TransferFee uint64 `json:"depositAmount0TransferFee"`

	// The token transfer fee for deposit_amount_1
	DepositAmount1TransferFee uint64 `json:"depositAmount1TransferFee"`
}

func (obj CreatePersonalPositionEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PoolState`:
	err = encoder.Encode(obj.PoolState)
	if err != nil {
		return errors.NewField("PoolState", err)
	}
	// Serialize `Minter`:
	err = encoder.Encode(obj.Minter)
	if err != nil {
		return errors.NewField("Minter", err)
	}
	// Serialize `NftOwner`:
	err = encoder.Encode(obj.NftOwner)
	if err != nil {
		return errors.NewField("NftOwner", err)
	}
	// Serialize `TickLowerIndex`:
	err = encoder.Encode(obj.TickLowerIndex)
	if err != nil {
		return errors.NewField("TickLowerIndex", err)
	}
	// Serialize `TickUpperIndex`:
	err = encoder.Encode(obj.TickUpperIndex)
	if err != nil {
		return errors.NewField("TickUpperIndex", err)
	}
	// Serialize `Liquidity`:
	err = encoder.Encode(obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Serialize `DepositAmount0`:
	err = encoder.Encode(obj.DepositAmount0)
	if err != nil {
		return errors.NewField("DepositAmount0", err)
	}
	// Serialize `DepositAmount1`:
	err = encoder.Encode(obj.DepositAmount1)
	if err != nil {
		return errors.NewField("DepositAmount1", err)
	}
	// Serialize `DepositAmount0TransferFee`:
	err = encoder.Encode(obj.DepositAmount0TransferFee)
	if err != nil {
		return errors.NewField("DepositAmount0TransferFee", err)
	}
	// Serialize `DepositAmount1TransferFee`:
	err = encoder.Encode(obj.DepositAmount1TransferFee)
	if err != nil {
		return errors.NewField("DepositAmount1TransferFee", err)
	}
	return nil
}

func (obj CreatePersonalPositionEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CreatePersonalPositionEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CreatePersonalPositionEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PoolState`:
	err = decoder.Decode(&obj.PoolState)
	if err != nil {
		return errors.NewField("PoolState", err)
	}
	// Deserialize `Minter`:
	err = decoder.Decode(&obj.Minter)
	if err != nil {
		return errors.NewField("Minter", err)
	}
	// Deserialize `NftOwner`:
	err = decoder.Decode(&obj.NftOwner)
	if err != nil {
		return errors.NewField("NftOwner", err)
	}
	// Deserialize `TickLowerIndex`:
	err = decoder.Decode(&obj.TickLowerIndex)
	if err != nil {
		return errors.NewField("TickLowerIndex", err)
	}
	// Deserialize `TickUpperIndex`:
	err = decoder.Decode(&obj.TickUpperIndex)
	if err != nil {
		return errors.NewField("TickUpperIndex", err)
	}
	// Deserialize `Liquidity`:
	err = decoder.Decode(&obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Deserialize `DepositAmount0`:
	err = decoder.Decode(&obj.DepositAmount0)
	if err != nil {
		return errors.NewField("DepositAmount0", err)
	}
	// Deserialize `DepositAmount1`:
	err = decoder.Decode(&obj.DepositAmount1)
	if err != nil {
		return errors.NewField("DepositAmount1", err)
	}
	// Deserialize `DepositAmount0TransferFee`:
	err = decoder.Decode(&obj.DepositAmount0TransferFee)
	if err != nil {
		return errors.NewField("DepositAmount0TransferFee", err)
	}
	// Deserialize `DepositAmount1TransferFee`:
	err = decoder.Decode(&obj.DepositAmount1TransferFee)
	if err != nil {
		return errors.NewField("DepositAmount1TransferFee", err)
	}
	return nil
}

func (obj *CreatePersonalPositionEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CreatePersonalPositionEvent: %w", err)
	}
	return nil
}

func UnmarshalCreatePersonalPositionEvent(buf []byte) (*CreatePersonalPositionEvent, error) {
	obj := new(CreatePersonalPositionEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted when liquidity is decreased.
type DecreaseLiquidityEvent struct {
	// The ID of the token for which liquidity was decreased
	PositionNftMint solanago.PublicKey `json:"positionNftMint"`

	// The amount by which liquidity for the position was decreased
	Liquidity binary.Uint128 `json:"liquidity"`

	// The amount of token_0 that was paid for the decrease in liquidity
	DecreaseAmount0 uint64 `json:"decreaseAmount0"`

	// The amount of token_1 that was paid for the decrease in liquidity
	DecreaseAmount1 uint64 `json:"decreaseAmount1"`
	FeeAmount0      uint64 `json:"feeAmount0"`

	// The amount of token_1 fee
	FeeAmount1 uint64 `json:"feeAmount1"`

	// The amount of rewards
	RewardAmounts [3]uint64 `json:"rewardAmounts"`

	// The amount of token_0 transfer fee
	TransferFee0 uint64 `json:"transferFee0"`

	// The amount of token_1 transfer fee
	TransferFee1 uint64 `json:"transferFee1"`
}

func (obj DecreaseLiquidityEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PositionNftMint`:
	err = encoder.Encode(obj.PositionNftMint)
	if err != nil {
		return errors.NewField("PositionNftMint", err)
	}
	// Serialize `Liquidity`:
	err = encoder.Encode(obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Serialize `DecreaseAmount0`:
	err = encoder.Encode(obj.DecreaseAmount0)
	if err != nil {
		return errors.NewField("DecreaseAmount0", err)
	}
	// Serialize `DecreaseAmount1`:
	err = encoder.Encode(obj.DecreaseAmount1)
	if err != nil {
		return errors.NewField("DecreaseAmount1", err)
	}
	// Serialize `FeeAmount0`:
	err = encoder.Encode(obj.FeeAmount0)
	if err != nil {
		return errors.NewField("FeeAmount0", err)
	}
	// Serialize `FeeAmount1`:
	err = encoder.Encode(obj.FeeAmount1)
	if err != nil {
		return errors.NewField("FeeAmount1", err)
	}
	// Serialize `RewardAmounts`:
	err = encoder.Encode(obj.RewardAmounts)
	if err != nil {
		return errors.NewField("RewardAmounts", err)
	}
	// Serialize `TransferFee0`:
	err = encoder.Encode(obj.TransferFee0)
	if err != nil {
		return errors.NewField("TransferFee0", err)
	}
	// Serialize `TransferFee1`:
	err = encoder.Encode(obj.TransferFee1)
	if err != nil {
		return errors.NewField("TransferFee1", err)
	}
	return nil
}

func (obj DecreaseLiquidityEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding DecreaseLiquidityEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *DecreaseLiquidityEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PositionNftMint`:
	err = decoder.Decode(&obj.PositionNftMint)
	if err != nil {
		return errors.NewField("PositionNftMint", err)
	}
	// Deserialize `Liquidity`:
	err = decoder.Decode(&obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Deserialize `DecreaseAmount0`:
	err = decoder.Decode(&obj.DecreaseAmount0)
	if err != nil {
		return errors.NewField("DecreaseAmount0", err)
	}
	// Deserialize `DecreaseAmount1`:
	err = decoder.Decode(&obj.DecreaseAmount1)
	if err != nil {
		return errors.NewField("DecreaseAmount1", err)
	}
	// Deserialize `FeeAmount0`:
	err = decoder.Decode(&obj.FeeAmount0)
	if err != nil {
		return errors.NewField("FeeAmount0", err)
	}
	// Deserialize `FeeAmount1`:
	err = decoder.Decode(&obj.FeeAmount1)
	if err != nil {
		return errors.NewField("FeeAmount1", err)
	}
	// Deserialize `RewardAmounts`:
	err = decoder.Decode(&obj.RewardAmounts)
	if err != nil {
		return errors.NewField("RewardAmounts", err)
	}
	// Deserialize `TransferFee0`:
	err = decoder.Decode(&obj.TransferFee0)
	if err != nil {
		return errors.NewField("TransferFee0", err)
	}
	// Deserialize `TransferFee1`:
	err = decoder.Decode(&obj.TransferFee1)
	if err != nil {
		return errors.NewField("TransferFee1", err)
	}
	return nil
}

func (obj *DecreaseLiquidityEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling DecreaseLiquidityEvent: %w", err)
	}
	return nil
}

func UnmarshalDecreaseLiquidityEvent(buf []byte) (*DecreaseLiquidityEvent, error) {
	obj := new(DecreaseLiquidityEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted when liquidity is increased.
type IncreaseLiquidityEvent struct {
	// The ID of the token for which liquidity was increased
	PositionNftMint solanago.PublicKey `json:"positionNftMint"`

	// The amount by which liquidity for the NFT position was increased
	Liquidity binary.Uint128 `json:"liquidity"`

	// The amount of token_0 that was paid for the increase in liquidity
	Amount0 uint64 `json:"amount0"`

	// The amount of token_1 that was paid for the increase in liquidity
	Amount1 uint64 `json:"amount1"`

	// The token transfer fee for amount_0
	Amount0TransferFee uint64 `json:"amount0TransferFee"`

	// The token transfer fee for amount_1
	Amount1TransferFee uint64 `json:"amount1TransferFee"`
}

func (obj IncreaseLiquidityEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PositionNftMint`:
	err = encoder.Encode(obj.PositionNftMint)
	if err != nil {
		return errors.NewField("PositionNftMint", err)
	}
	// Serialize `Liquidity`:
	err = encoder.Encode(obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Serialize `Amount0`:
	err = encoder.Encode(obj.Amount0)
	if err != nil {
		return errors.NewField("Amount0", err)
	}
	// Serialize `Amount1`:
	err = encoder.Encode(obj.Amount1)
	if err != nil {
		return errors.NewField("Amount1", err)
	}
	// Serialize `Amount0TransferFee`:
	err = encoder.Encode(obj.Amount0TransferFee)
	if err != nil {
		return errors.NewField("Amount0TransferFee", err)
	}
	// Serialize `Amount1TransferFee`:
	err = encoder.Encode(obj.Amount1TransferFee)
	if err != nil {
		return errors.NewField("Amount1TransferFee", err)
	}
	return nil
}

func (obj IncreaseLiquidityEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding IncreaseLiquidityEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *IncreaseLiquidityEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PositionNftMint`:
	err = decoder.Decode(&obj.PositionNftMint)
	if err != nil {
		return errors.NewField("PositionNftMint", err)
	}
	// Deserialize `Liquidity`:
	err = decoder.Decode(&obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Deserialize `Amount0`:
	err = decoder.Decode(&obj.Amount0)
	if err != nil {
		return errors.NewField("Amount0", err)
	}
	// Deserialize `Amount1`:
	err = decoder.Decode(&obj.Amount1)
	if err != nil {
		return errors.NewField("Amount1", err)
	}
	// Deserialize `Amount0TransferFee`:
	err = decoder.Decode(&obj.Amount0TransferFee)
	if err != nil {
		return errors.NewField("Amount0TransferFee", err)
	}
	// Deserialize `Amount1TransferFee`:
	err = decoder.Decode(&obj.Amount1TransferFee)
	if err != nil {
		return errors.NewField("Amount1TransferFee", err)
	}
	return nil
}

func (obj *IncreaseLiquidityEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling IncreaseLiquidityEvent: %w", err)
	}
	return nil
}

func UnmarshalIncreaseLiquidityEvent(buf []byte) (*IncreaseLiquidityEvent, error) {
	obj := new(IncreaseLiquidityEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type InitializeRewardParam struct {
	// Reward open time
	OpenTime uint64 `json:"openTime"`

	// Reward end time
	EndTime uint64 `json:"endTime"`

	// Token reward per second are earned per unit of liquidity
	EmissionsPerSecondX64 binary.Uint128 `json:"emissionsPerSecondX64"`
}

func (obj InitializeRewardParam) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `OpenTime`:
	err = encoder.Encode(obj.OpenTime)
	if err != nil {
		return errors.NewField("OpenTime", err)
	}
	// Serialize `EndTime`:
	err = encoder.Encode(obj.EndTime)
	if err != nil {
		return errors.NewField("EndTime", err)
	}
	// Serialize `EmissionsPerSecondX64`:
	err = encoder.Encode(obj.EmissionsPerSecondX64)
	if err != nil {
		return errors.NewField("EmissionsPerSecondX64", err)
	}
	return nil
}

func (obj InitializeRewardParam) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding InitializeRewardParam: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *InitializeRewardParam) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `OpenTime`:
	err = decoder.Decode(&obj.OpenTime)
	if err != nil {
		return errors.NewField("OpenTime", err)
	}
	// Deserialize `EndTime`:
	err = decoder.Decode(&obj.EndTime)
	if err != nil {
		return errors.NewField("EndTime", err)
	}
	// Deserialize `EmissionsPerSecondX64`:
	err = decoder.Decode(&obj.EmissionsPerSecondX64)
	if err != nil {
		return errors.NewField("EmissionsPerSecondX64", err)
	}
	return nil
}

func (obj *InitializeRewardParam) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling InitializeRewardParam: %w", err)
	}
	return nil
}

func UnmarshalInitializeRewardParam(buf []byte) (*InitializeRewardParam, error) {
	obj := new(InitializeRewardParam)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted when liquidity decreased or increase.
type LiquidityCalculateEvent struct {
	// The pool liquidity before decrease or increase
	PoolLiquidity binary.Uint128 `json:"poolLiquidity"`

	// The pool price when decrease or increase in liquidity
	PoolSqrtPriceX64 binary.Uint128 `json:"poolSqrtPriceX64"`

	// The pool tick when decrease or increase in liquidity
	PoolTick int32 `json:"poolTick"`

	// The amount of token_0 that was calculated for the decrease or increase in liquidity
	CalcAmount0 uint64 `json:"calcAmount0"`

	// The amount of token_1 that was calculated for the decrease or increase in liquidity
	CalcAmount1   uint64 `json:"calcAmount1"`
	TradeFeeOwed0 uint64 `json:"tradeFeeOwed0"`

	// The amount of token_1 fee
	TradeFeeOwed1 uint64 `json:"tradeFeeOwed1"`

	// The amount of token_0 transfer fee without trade_fee_amount_0
	TransferFee0 uint64 `json:"transferFee0"`

	// The amount of token_1 transfer fee without trade_fee_amount_0
	TransferFee1 uint64 `json:"transferFee1"`
}

func (obj LiquidityCalculateEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PoolLiquidity`:
	err = encoder.Encode(obj.PoolLiquidity)
	if err != nil {
		return errors.NewField("PoolLiquidity", err)
	}
	// Serialize `PoolSqrtPriceX64`:
	err = encoder.Encode(obj.PoolSqrtPriceX64)
	if err != nil {
		return errors.NewField("PoolSqrtPriceX64", err)
	}
	// Serialize `PoolTick`:
	err = encoder.Encode(obj.PoolTick)
	if err != nil {
		return errors.NewField("PoolTick", err)
	}
	// Serialize `CalcAmount0`:
	err = encoder.Encode(obj.CalcAmount0)
	if err != nil {
		return errors.NewField("CalcAmount0", err)
	}
	// Serialize `CalcAmount1`:
	err = encoder.Encode(obj.CalcAmount1)
	if err != nil {
		return errors.NewField("CalcAmount1", err)
	}
	// Serialize `TradeFeeOwed0`:
	err = encoder.Encode(obj.TradeFeeOwed0)
	if err != nil {
		return errors.NewField("TradeFeeOwed0", err)
	}
	// Serialize `TradeFeeOwed1`:
	err = encoder.Encode(obj.TradeFeeOwed1)
	if err != nil {
		return errors.NewField("TradeFeeOwed1", err)
	}
	// Serialize `TransferFee0`:
	err = encoder.Encode(obj.TransferFee0)
	if err != nil {
		return errors.NewField("TransferFee0", err)
	}
	// Serialize `TransferFee1`:
	err = encoder.Encode(obj.TransferFee1)
	if err != nil {
		return errors.NewField("TransferFee1", err)
	}
	return nil
}

func (obj LiquidityCalculateEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding LiquidityCalculateEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *LiquidityCalculateEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PoolLiquidity`:
	err = decoder.Decode(&obj.PoolLiquidity)
	if err != nil {
		return errors.NewField("PoolLiquidity", err)
	}
	// Deserialize `PoolSqrtPriceX64`:
	err = decoder.Decode(&obj.PoolSqrtPriceX64)
	if err != nil {
		return errors.NewField("PoolSqrtPriceX64", err)
	}
	// Deserialize `PoolTick`:
	err = decoder.Decode(&obj.PoolTick)
	if err != nil {
		return errors.NewField("PoolTick", err)
	}
	// Deserialize `CalcAmount0`:
	err = decoder.Decode(&obj.CalcAmount0)
	if err != nil {
		return errors.NewField("CalcAmount0", err)
	}
	// Deserialize `CalcAmount1`:
	err = decoder.Decode(&obj.CalcAmount1)
	if err != nil {
		return errors.NewField("CalcAmount1", err)
	}
	// Deserialize `TradeFeeOwed0`:
	err = decoder.Decode(&obj.TradeFeeOwed0)
	if err != nil {
		return errors.NewField("TradeFeeOwed0", err)
	}
	// Deserialize `TradeFeeOwed1`:
	err = decoder.Decode(&obj.TradeFeeOwed1)
	if err != nil {
		return errors.NewField("TradeFeeOwed1", err)
	}
	// Deserialize `TransferFee0`:
	err = decoder.Decode(&obj.TransferFee0)
	if err != nil {
		return errors.NewField("TransferFee0", err)
	}
	// Deserialize `TransferFee1`:
	err = decoder.Decode(&obj.TransferFee1)
	if err != nil {
		return errors.NewField("TransferFee1", err)
	}
	return nil
}

func (obj *LiquidityCalculateEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling LiquidityCalculateEvent: %w", err)
	}
	return nil
}

func UnmarshalLiquidityCalculateEvent(buf []byte) (*LiquidityCalculateEvent, error) {
	obj := new(LiquidityCalculateEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted pool liquidity change when increase and decrease liquidity
type LiquidityChangeEvent struct {
	// The pool for swap
	PoolState solanago.PublicKey `json:"poolState"`

	// The tick of the pool
	Tick int32 `json:"tick"`

	// The tick lower of position
	TickLower int32 `json:"tickLower"`

	// The tick lower of position
	TickUpper int32 `json:"tickUpper"`

	// The liquidity of the pool before liquidity change
	LiquidityBefore binary.Uint128 `json:"liquidityBefore"`

	// The liquidity of the pool after liquidity change
	LiquidityAfter binary.Uint128 `json:"liquidityAfter"`
}

func (obj LiquidityChangeEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PoolState`:
	err = encoder.Encode(obj.PoolState)
	if err != nil {
		return errors.NewField("PoolState", err)
	}
	// Serialize `Tick`:
	err = encoder.Encode(obj.Tick)
	if err != nil {
		return errors.NewField("Tick", err)
	}
	// Serialize `TickLower`:
	err = encoder.Encode(obj.TickLower)
	if err != nil {
		return errors.NewField("TickLower", err)
	}
	// Serialize `TickUpper`:
	err = encoder.Encode(obj.TickUpper)
	if err != nil {
		return errors.NewField("TickUpper", err)
	}
	// Serialize `LiquidityBefore`:
	err = encoder.Encode(obj.LiquidityBefore)
	if err != nil {
		return errors.NewField("LiquidityBefore", err)
	}
	// Serialize `LiquidityAfter`:
	err = encoder.Encode(obj.LiquidityAfter)
	if err != nil {
		return errors.NewField("LiquidityAfter", err)
	}
	return nil
}

func (obj LiquidityChangeEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding LiquidityChangeEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *LiquidityChangeEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PoolState`:
	err = decoder.Decode(&obj.PoolState)
	if err != nil {
		return errors.NewField("PoolState", err)
	}
	// Deserialize `Tick`:
	err = decoder.Decode(&obj.Tick)
	if err != nil {
		return errors.NewField("Tick", err)
	}
	// Deserialize `TickLower`:
	err = decoder.Decode(&obj.TickLower)
	if err != nil {
		return errors.NewField("TickLower", err)
	}
	// Deserialize `TickUpper`:
	err = decoder.Decode(&obj.TickUpper)
	if err != nil {
		return errors.NewField("TickUpper", err)
	}
	// Deserialize `LiquidityBefore`:
	err = decoder.Decode(&obj.LiquidityBefore)
	if err != nil {
		return errors.NewField("LiquidityBefore", err)
	}
	// Deserialize `LiquidityAfter`:
	err = decoder.Decode(&obj.LiquidityAfter)
	if err != nil {
		return errors.NewField("LiquidityAfter", err)
	}
	return nil
}

func (obj *LiquidityChangeEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling LiquidityChangeEvent: %w", err)
	}
	return nil
}

func UnmarshalLiquidityChangeEvent(buf []byte) (*LiquidityChangeEvent, error) {
	obj := new(LiquidityChangeEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// The element of observations in ObservationState
type Observation struct {
	// The block timestamp of the observation
	BlockTimestamp uint32 `json:"blockTimestamp"`

	// the cumulative of tick during the duration time
	TickCumulative int64 `json:"tickCumulative"`

	// padding for feature update
	Padding [4]uint64 `json:"padding"`
}

func (obj Observation) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `BlockTimestamp`:
	err = encoder.Encode(obj.BlockTimestamp)
	if err != nil {
		return errors.NewField("BlockTimestamp", err)
	}
	// Serialize `TickCumulative`:
	err = encoder.Encode(obj.TickCumulative)
	if err != nil {
		return errors.NewField("TickCumulative", err)
	}
	// Serialize `Padding`:
	err = encoder.Encode(obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj Observation) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Observation: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Observation) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `BlockTimestamp`:
	err = decoder.Decode(&obj.BlockTimestamp)
	if err != nil {
		return errors.NewField("BlockTimestamp", err)
	}
	// Deserialize `TickCumulative`:
	err = decoder.Decode(&obj.TickCumulative)
	if err != nil {
		return errors.NewField("TickCumulative", err)
	}
	// Deserialize `Padding`:
	err = decoder.Decode(&obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj *Observation) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Observation: %w", err)
	}
	return nil
}

func UnmarshalObservation(buf []byte) (*Observation, error) {
	obj := new(Observation)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ObservationState struct {
	// Whether the ObservationState is initialized
	Initialized bool `json:"initialized"`

	// recent update epoch
	RecentEpoch uint64 `json:"recentEpoch"`

	// the most-recently updated index of the observations array
	ObservationIndex uint16 `json:"observationIndex"`

	// belongs to which pool
	PoolId solanago.PublicKey `json:"poolId"`

	// observation array
	Observations [100]Observation `json:"observations"`

	// padding for feature update
	Padding [4]uint64 `json:"padding"`
}

func (obj ObservationState) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Initialized`:
	err = encoder.Encode(obj.Initialized)
	if err != nil {
		return errors.NewField("Initialized", err)
	}
	// Serialize `RecentEpoch`:
	err = encoder.Encode(obj.RecentEpoch)
	if err != nil {
		return errors.NewField("RecentEpoch", err)
	}
	// Serialize `ObservationIndex`:
	err = encoder.Encode(obj.ObservationIndex)
	if err != nil {
		return errors.NewField("ObservationIndex", err)
	}
	// Serialize `PoolId`:
	err = encoder.Encode(obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Serialize `Observations`:
	err = encoder.Encode(obj.Observations)
	if err != nil {
		return errors.NewField("Observations", err)
	}
	// Serialize `Padding`:
	err = encoder.Encode(obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj ObservationState) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ObservationState: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ObservationState) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Initialized`:
	err = decoder.Decode(&obj.Initialized)
	if err != nil {
		return errors.NewField("Initialized", err)
	}
	// Deserialize `RecentEpoch`:
	err = decoder.Decode(&obj.RecentEpoch)
	if err != nil {
		return errors.NewField("RecentEpoch", err)
	}
	// Deserialize `ObservationIndex`:
	err = decoder.Decode(&obj.ObservationIndex)
	if err != nil {
		return errors.NewField("ObservationIndex", err)
	}
	// Deserialize `PoolId`:
	err = decoder.Decode(&obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Deserialize `Observations`:
	err = decoder.Decode(&obj.Observations)
	if err != nil {
		return errors.NewField("Observations", err)
	}
	// Deserialize `Padding`:
	err = decoder.Decode(&obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj *ObservationState) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ObservationState: %w", err)
	}
	return nil
}

func UnmarshalObservationState(buf []byte) (*ObservationState, error) {
	obj := new(ObservationState)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Holds the current owner of the factory
type OperationState struct {
	// Bump to identify PDA
	Bump uint8 `json:"bump"`

	// Address of the operation owner
	OperationOwners [10]solanago.PublicKey `json:"operationOwners"`

	// The mint address of whitelist to emit reward
	WhitelistMints [100]solanago.PublicKey `json:"whitelistMints"`
}

func (obj OperationState) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `OperationOwners`:
	err = encoder.Encode(obj.OperationOwners)
	if err != nil {
		return errors.NewField("OperationOwners", err)
	}
	// Serialize `WhitelistMints`:
	err = encoder.Encode(obj.WhitelistMints)
	if err != nil {
		return errors.NewField("WhitelistMints", err)
	}
	return nil
}

func (obj OperationState) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding OperationState: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *OperationState) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `OperationOwners`:
	err = decoder.Decode(&obj.OperationOwners)
	if err != nil {
		return errors.NewField("OperationOwners", err)
	}
	// Deserialize `WhitelistMints`:
	err = decoder.Decode(&obj.WhitelistMints)
	if err != nil {
		return errors.NewField("WhitelistMints", err)
	}
	return nil
}

func (obj *OperationState) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling OperationState: %w", err)
	}
	return nil
}

func UnmarshalOperationState(buf []byte) (*OperationState, error) {
	obj := new(OperationState)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type PersonalPositionState struct {
	// Bump to identify PDA
	Bump [1]uint8 `json:"bump"`

	// Mint address of the tokenized position
	NftMint solanago.PublicKey `json:"nftMint"`

	// The ID of the pool with which this token is connected
	PoolId solanago.PublicKey `json:"poolId"`

	// The lower bound tick of the position
	TickLowerIndex int32 `json:"tickLowerIndex"`

	// The upper bound tick of the position
	TickUpperIndex int32 `json:"tickUpperIndex"`

	// The amount of liquidity owned by this position
	Liquidity binary.Uint128 `json:"liquidity"`

	// The token_0 fee growth of the aggregate position as of the last action on the individual position
	FeeGrowthInside0LastX64 binary.Uint128 `json:"feeGrowthInside0LastX64"`

	// The token_1 fee growth of the aggregate position as of the last action on the individual position
	FeeGrowthInside1LastX64 binary.Uint128 `json:"feeGrowthInside1LastX64"`

	// The fees owed to the position owner in token_0, as of the last computation
	TokenFeesOwed0 uint64 `json:"tokenFeesOwed0"`

	// The fees owed to the position owner in token_1, as of the last computation
	TokenFeesOwed1 uint64                `json:"tokenFeesOwed1"`
	RewardInfos    [3]PositionRewardInfo `json:"rewardInfos"`
	RecentEpoch    uint64                `json:"recentEpoch"`
	Padding        [7]uint64             `json:"padding"`
}

func (obj PersonalPositionState) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `NftMint`:
	err = encoder.Encode(obj.NftMint)
	if err != nil {
		return errors.NewField("NftMint", err)
	}
	// Serialize `PoolId`:
	err = encoder.Encode(obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Serialize `TickLowerIndex`:
	err = encoder.Encode(obj.TickLowerIndex)
	if err != nil {
		return errors.NewField("TickLowerIndex", err)
	}
	// Serialize `TickUpperIndex`:
	err = encoder.Encode(obj.TickUpperIndex)
	if err != nil {
		return errors.NewField("TickUpperIndex", err)
	}
	// Serialize `Liquidity`:
	err = encoder.Encode(obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Serialize `FeeGrowthInside0LastX64`:
	err = encoder.Encode(obj.FeeGrowthInside0LastX64)
	if err != nil {
		return errors.NewField("FeeGrowthInside0LastX64", err)
	}
	// Serialize `FeeGrowthInside1LastX64`:
	err = encoder.Encode(obj.FeeGrowthInside1LastX64)
	if err != nil {
		return errors.NewField("FeeGrowthInside1LastX64", err)
	}
	// Serialize `TokenFeesOwed0`:
	err = encoder.Encode(obj.TokenFeesOwed0)
	if err != nil {
		return errors.NewField("TokenFeesOwed0", err)
	}
	// Serialize `TokenFeesOwed1`:
	err = encoder.Encode(obj.TokenFeesOwed1)
	if err != nil {
		return errors.NewField("TokenFeesOwed1", err)
	}
	// Serialize `RewardInfos`:
	err = encoder.Encode(obj.RewardInfos)
	if err != nil {
		return errors.NewField("RewardInfos", err)
	}
	// Serialize `RecentEpoch`:
	err = encoder.Encode(obj.RecentEpoch)
	if err != nil {
		return errors.NewField("RecentEpoch", err)
	}
	// Serialize `Padding`:
	err = encoder.Encode(obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj PersonalPositionState) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PersonalPositionState: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PersonalPositionState) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `NftMint`:
	err = decoder.Decode(&obj.NftMint)
	if err != nil {
		return errors.NewField("NftMint", err)
	}
	// Deserialize `PoolId`:
	err = decoder.Decode(&obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Deserialize `TickLowerIndex`:
	err = decoder.Decode(&obj.TickLowerIndex)
	if err != nil {
		return errors.NewField("TickLowerIndex", err)
	}
	// Deserialize `TickUpperIndex`:
	err = decoder.Decode(&obj.TickUpperIndex)
	if err != nil {
		return errors.NewField("TickUpperIndex", err)
	}
	// Deserialize `Liquidity`:
	err = decoder.Decode(&obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Deserialize `FeeGrowthInside0LastX64`:
	err = decoder.Decode(&obj.FeeGrowthInside0LastX64)
	if err != nil {
		return errors.NewField("FeeGrowthInside0LastX64", err)
	}
	// Deserialize `FeeGrowthInside1LastX64`:
	err = decoder.Decode(&obj.FeeGrowthInside1LastX64)
	if err != nil {
		return errors.NewField("FeeGrowthInside1LastX64", err)
	}
	// Deserialize `TokenFeesOwed0`:
	err = decoder.Decode(&obj.TokenFeesOwed0)
	if err != nil {
		return errors.NewField("TokenFeesOwed0", err)
	}
	// Deserialize `TokenFeesOwed1`:
	err = decoder.Decode(&obj.TokenFeesOwed1)
	if err != nil {
		return errors.NewField("TokenFeesOwed1", err)
	}
	// Deserialize `RewardInfos`:
	err = decoder.Decode(&obj.RewardInfos)
	if err != nil {
		return errors.NewField("RewardInfos", err)
	}
	// Deserialize `RecentEpoch`:
	err = decoder.Decode(&obj.RecentEpoch)
	if err != nil {
		return errors.NewField("RecentEpoch", err)
	}
	// Deserialize `Padding`:
	err = decoder.Decode(&obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj *PersonalPositionState) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PersonalPositionState: %w", err)
	}
	return nil
}

func UnmarshalPersonalPositionState(buf []byte) (*PersonalPositionState, error) {
	obj := new(PersonalPositionState)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted when a pool is created and initialized with a starting price
type PoolCreatedEvent struct {
	// The first token of the pool by address sort order
	TokenMint0 solanago.PublicKey `json:"tokenMint0"`

	// The second token of the pool by address sort order
	TokenMint1 solanago.PublicKey `json:"tokenMint1"`

	// The minimum number of ticks between initialized ticks
	TickSpacing uint16 `json:"tickSpacing"`

	// The address of the created pool
	PoolState solanago.PublicKey `json:"poolState"`

	// The initial sqrt price of the pool, as a Q64.64
	SqrtPriceX64 binary.Uint128 `json:"sqrtPriceX64"`

	// The initial tick of the pool, i.e. log base 1.0001 of the starting price of the pool
	Tick int32 `json:"tick"`

	// Vault of token_0
	TokenVault0 solanago.PublicKey `json:"tokenVault0"`

	// Vault of token_1
	TokenVault1 solanago.PublicKey `json:"tokenVault1"`
}

func (obj PoolCreatedEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `TokenMint0`:
	err = encoder.Encode(obj.TokenMint0)
	if err != nil {
		return errors.NewField("TokenMint0", err)
	}
	// Serialize `TokenMint1`:
	err = encoder.Encode(obj.TokenMint1)
	if err != nil {
		return errors.NewField("TokenMint1", err)
	}
	// Serialize `TickSpacing`:
	err = encoder.Encode(obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Serialize `PoolState`:
	err = encoder.Encode(obj.PoolState)
	if err != nil {
		return errors.NewField("PoolState", err)
	}
	// Serialize `SqrtPriceX64`:
	err = encoder.Encode(obj.SqrtPriceX64)
	if err != nil {
		return errors.NewField("SqrtPriceX64", err)
	}
	// Serialize `Tick`:
	err = encoder.Encode(obj.Tick)
	if err != nil {
		return errors.NewField("Tick", err)
	}
	// Serialize `TokenVault0`:
	err = encoder.Encode(obj.TokenVault0)
	if err != nil {
		return errors.NewField("TokenVault0", err)
	}
	// Serialize `TokenVault1`:
	err = encoder.Encode(obj.TokenVault1)
	if err != nil {
		return errors.NewField("TokenVault1", err)
	}
	return nil
}

func (obj PoolCreatedEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PoolCreatedEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PoolCreatedEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `TokenMint0`:
	err = decoder.Decode(&obj.TokenMint0)
	if err != nil {
		return errors.NewField("TokenMint0", err)
	}
	// Deserialize `TokenMint1`:
	err = decoder.Decode(&obj.TokenMint1)
	if err != nil {
		return errors.NewField("TokenMint1", err)
	}
	// Deserialize `TickSpacing`:
	err = decoder.Decode(&obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Deserialize `PoolState`:
	err = decoder.Decode(&obj.PoolState)
	if err != nil {
		return errors.NewField("PoolState", err)
	}
	// Deserialize `SqrtPriceX64`:
	err = decoder.Decode(&obj.SqrtPriceX64)
	if err != nil {
		return errors.NewField("SqrtPriceX64", err)
	}
	// Deserialize `Tick`:
	err = decoder.Decode(&obj.Tick)
	if err != nil {
		return errors.NewField("Tick", err)
	}
	// Deserialize `TokenVault0`:
	err = decoder.Decode(&obj.TokenVault0)
	if err != nil {
		return errors.NewField("TokenVault0", err)
	}
	// Deserialize `TokenVault1`:
	err = decoder.Decode(&obj.TokenVault1)
	if err != nil {
		return errors.NewField("TokenVault1", err)
	}
	return nil
}

func (obj *PoolCreatedEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PoolCreatedEvent: %w", err)
	}
	return nil
}

func UnmarshalPoolCreatedEvent(buf []byte) (*PoolCreatedEvent, error) {
	obj := new(PoolCreatedEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// The pool state
//
// PDA of `[POOL_SEED, config, token_mint_0, token_mint_1]`
type PoolState struct {
	// Bump to identify PDA
	Bump      [1]uint8           `json:"bump"`
	AmmConfig solanago.PublicKey `json:"ammConfig"`
	Owner     solanago.PublicKey `json:"owner"`

	// Token pair of the pool, where token_mint_0 address < token_mint_1 address
	TokenMint0 solanago.PublicKey `json:"tokenMint0"`
	TokenMint1 solanago.PublicKey `json:"tokenMint1"`

	// Token pair vault
	TokenVault0 solanago.PublicKey `json:"tokenVault0"`
	TokenVault1 solanago.PublicKey `json:"tokenVault1"`

	// observation account key
	ObservationKey solanago.PublicKey `json:"observationKey"`

	// mint0 and mint1 decimals
	MintDecimals0 uint8 `json:"mintDecimals0"`
	MintDecimals1 uint8 `json:"mintDecimals1"`

	// The minimum number of ticks between initialized ticks
	TickSpacing uint16 `json:"tickSpacing"`

	// The currently in range liquidity available to the pool.
	Liquidity binary.Uint128 `json:"liquidity"`

	// The current price of the pool as a sqrt(token_1/token_0) Q64.64 value
	SqrtPriceX64 binary.Uint128 `json:"sqrtPriceX64"`

	// The current tick of the pool, i.e. according to the last tick transition that was run.
	TickCurrent int32  `json:"tickCurrent"`
	Padding3    uint16 `json:"padding3"`
	Padding4    uint16 `json:"padding4"`

	// The fee growth as a Q64.64 number, i.e. fees of token_0 and token_1 collected per
	// unit of liquidity for the entire life of the pool.
	FeeGrowthGlobal0X64 binary.Uint128 `json:"feeGrowthGlobal0X64"`
	FeeGrowthGlobal1X64 binary.Uint128 `json:"feeGrowthGlobal1X64"`

	// The amounts of token_0 and token_1 that are owed to the protocol.
	ProtocolFeesToken0 uint64 `json:"protocolFeesToken0"`
	ProtocolFeesToken1 uint64 `json:"protocolFeesToken1"`

	// The amounts in and out of swap token_0 and token_1
	SwapInAmountToken0  binary.Uint128 `json:"swapInAmountToken0"`
	SwapOutAmountToken1 binary.Uint128 `json:"swapOutAmountToken1"`
	SwapInAmountToken1  binary.Uint128 `json:"swapInAmountToken1"`
	SwapOutAmountToken0 binary.Uint128 `json:"swapOutAmountToken0"`

	// Bitwise representation of the state of the pool
	// bit0, 1: disable open position and increase liquidity, 0: normal
	// bit1, 1: disable decrease liquidity, 0: normal
	// bit2, 1: disable collect fee, 0: normal
	// bit3, 1: disable collect reward, 0: normal
	// bit4, 1: disable swap, 0: normal
	Status uint8 `json:"status"`

	// Leave blank for future use
	Padding     [7]uint8      `json:"padding"`
	RewardInfos [3]RewardInfo `json:"rewardInfos"`

	// Packed initialized tick array state
	TickArrayBitmap [16]uint64 `json:"tickArrayBitmap"`

	// except protocol_fee and fund_fee
	TotalFeesToken0 uint64 `json:"totalFeesToken0"`

	// except protocol_fee and fund_fee
	TotalFeesClaimedToken0 uint64     `json:"totalFeesClaimedToken0"`
	TotalFeesToken1        uint64     `json:"totalFeesToken1"`
	TotalFeesClaimedToken1 uint64     `json:"totalFeesClaimedToken1"`
	FundFeesToken0         uint64     `json:"fundFeesToken0"`
	FundFeesToken1         uint64     `json:"fundFeesToken1"`
	OpenTime               uint64     `json:"openTime"`
	RecentEpoch            uint64     `json:"recentEpoch"`
	Padding1               [24]uint64 `json:"padding1"`
	Padding2               [32]uint64 `json:"padding2"`
}

func (obj PoolState) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `AmmConfig`:
	err = encoder.Encode(obj.AmmConfig)
	if err != nil {
		return errors.NewField("AmmConfig", err)
	}
	// Serialize `Owner`:
	err = encoder.Encode(obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Serialize `TokenMint0`:
	err = encoder.Encode(obj.TokenMint0)
	if err != nil {
		return errors.NewField("TokenMint0", err)
	}
	// Serialize `TokenMint1`:
	err = encoder.Encode(obj.TokenMint1)
	if err != nil {
		return errors.NewField("TokenMint1", err)
	}
	// Serialize `TokenVault0`:
	err = encoder.Encode(obj.TokenVault0)
	if err != nil {
		return errors.NewField("TokenVault0", err)
	}
	// Serialize `TokenVault1`:
	err = encoder.Encode(obj.TokenVault1)
	if err != nil {
		return errors.NewField("TokenVault1", err)
	}
	// Serialize `ObservationKey`:
	err = encoder.Encode(obj.ObservationKey)
	if err != nil {
		return errors.NewField("ObservationKey", err)
	}
	// Serialize `MintDecimals0`:
	err = encoder.Encode(obj.MintDecimals0)
	if err != nil {
		return errors.NewField("MintDecimals0", err)
	}
	// Serialize `MintDecimals1`:
	err = encoder.Encode(obj.MintDecimals1)
	if err != nil {
		return errors.NewField("MintDecimals1", err)
	}
	// Serialize `TickSpacing`:
	err = encoder.Encode(obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Serialize `Liquidity`:
	err = encoder.Encode(obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Serialize `SqrtPriceX64`:
	err = encoder.Encode(obj.SqrtPriceX64)
	if err != nil {
		return errors.NewField("SqrtPriceX64", err)
	}
	// Serialize `TickCurrent`:
	err = encoder.Encode(obj.TickCurrent)
	if err != nil {
		return errors.NewField("TickCurrent", err)
	}
	// Serialize `Padding3`:
	err = encoder.Encode(obj.Padding3)
	if err != nil {
		return errors.NewField("Padding3", err)
	}
	// Serialize `Padding4`:
	err = encoder.Encode(obj.Padding4)
	if err != nil {
		return errors.NewField("Padding4", err)
	}
	// Serialize `FeeGrowthGlobal0X64`:
	err = encoder.Encode(obj.FeeGrowthGlobal0X64)
	if err != nil {
		return errors.NewField("FeeGrowthGlobal0X64", err)
	}
	// Serialize `FeeGrowthGlobal1X64`:
	err = encoder.Encode(obj.FeeGrowthGlobal1X64)
	if err != nil {
		return errors.NewField("FeeGrowthGlobal1X64", err)
	}
	// Serialize `ProtocolFeesToken0`:
	err = encoder.Encode(obj.ProtocolFeesToken0)
	if err != nil {
		return errors.NewField("ProtocolFeesToken0", err)
	}
	// Serialize `ProtocolFeesToken1`:
	err = encoder.Encode(obj.ProtocolFeesToken1)
	if err != nil {
		return errors.NewField("ProtocolFeesToken1", err)
	}
	// Serialize `SwapInAmountToken0`:
	err = encoder.Encode(obj.SwapInAmountToken0)
	if err != nil {
		return errors.NewField("SwapInAmountToken0", err)
	}
	// Serialize `SwapOutAmountToken1`:
	err = encoder.Encode(obj.SwapOutAmountToken1)
	if err != nil {
		return errors.NewField("SwapOutAmountToken1", err)
	}
	// Serialize `SwapInAmountToken1`:
	err = encoder.Encode(obj.SwapInAmountToken1)
	if err != nil {
		return errors.NewField("SwapInAmountToken1", err)
	}
	// Serialize `SwapOutAmountToken0`:
	err = encoder.Encode(obj.SwapOutAmountToken0)
	if err != nil {
		return errors.NewField("SwapOutAmountToken0", err)
	}
	// Serialize `Status`:
	err = encoder.Encode(obj.Status)
	if err != nil {
		return errors.NewField("Status", err)
	}
	// Serialize `Padding`:
	err = encoder.Encode(obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	// Serialize `RewardInfos`:
	err = encoder.Encode(obj.RewardInfos)
	if err != nil {
		return errors.NewField("RewardInfos", err)
	}
	// Serialize `TickArrayBitmap`:
	err = encoder.Encode(obj.TickArrayBitmap)
	if err != nil {
		return errors.NewField("TickArrayBitmap", err)
	}
	// Serialize `TotalFeesToken0`:
	err = encoder.Encode(obj.TotalFeesToken0)
	if err != nil {
		return errors.NewField("TotalFeesToken0", err)
	}
	// Serialize `TotalFeesClaimedToken0`:
	err = encoder.Encode(obj.TotalFeesClaimedToken0)
	if err != nil {
		return errors.NewField("TotalFeesClaimedToken0", err)
	}
	// Serialize `TotalFeesToken1`:
	err = encoder.Encode(obj.TotalFeesToken1)
	if err != nil {
		return errors.NewField("TotalFeesToken1", err)
	}
	// Serialize `TotalFeesClaimedToken1`:
	err = encoder.Encode(obj.TotalFeesClaimedToken1)
	if err != nil {
		return errors.NewField("TotalFeesClaimedToken1", err)
	}
	// Serialize `FundFeesToken0`:
	err = encoder.Encode(obj.FundFeesToken0)
	if err != nil {
		return errors.NewField("FundFeesToken0", err)
	}
	// Serialize `FundFeesToken1`:
	err = encoder.Encode(obj.FundFeesToken1)
	if err != nil {
		return errors.NewField("FundFeesToken1", err)
	}
	// Serialize `OpenTime`:
	err = encoder.Encode(obj.OpenTime)
	if err != nil {
		return errors.NewField("OpenTime", err)
	}
	// Serialize `RecentEpoch`:
	err = encoder.Encode(obj.RecentEpoch)
	if err != nil {
		return errors.NewField("RecentEpoch", err)
	}
	// Serialize `Padding1`:
	err = encoder.Encode(obj.Padding1)
	if err != nil {
		return errors.NewField("Padding1", err)
	}
	// Serialize `Padding2`:
	err = encoder.Encode(obj.Padding2)
	if err != nil {
		return errors.NewField("Padding2", err)
	}
	return nil
}

func (obj PoolState) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PoolState: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PoolState) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `AmmConfig`:
	err = decoder.Decode(&obj.AmmConfig)
	if err != nil {
		return errors.NewField("AmmConfig", err)
	}
	// Deserialize `Owner`:
	err = decoder.Decode(&obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Deserialize `TokenMint0`:
	err = decoder.Decode(&obj.TokenMint0)
	if err != nil {
		return errors.NewField("TokenMint0", err)
	}
	// Deserialize `TokenMint1`:
	err = decoder.Decode(&obj.TokenMint1)
	if err != nil {
		return errors.NewField("TokenMint1", err)
	}
	// Deserialize `TokenVault0`:
	err = decoder.Decode(&obj.TokenVault0)
	if err != nil {
		return errors.NewField("TokenVault0", err)
	}
	// Deserialize `TokenVault1`:
	err = decoder.Decode(&obj.TokenVault1)
	if err != nil {
		return errors.NewField("TokenVault1", err)
	}
	// Deserialize `ObservationKey`:
	err = decoder.Decode(&obj.ObservationKey)
	if err != nil {
		return errors.NewField("ObservationKey", err)
	}
	// Deserialize `MintDecimals0`:
	err = decoder.Decode(&obj.MintDecimals0)
	if err != nil {
		return errors.NewField("MintDecimals0", err)
	}
	// Deserialize `MintDecimals1`:
	err = decoder.Decode(&obj.MintDecimals1)
	if err != nil {
		return errors.NewField("MintDecimals1", err)
	}
	// Deserialize `TickSpacing`:
	err = decoder.Decode(&obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Deserialize `Liquidity`:
	err = decoder.Decode(&obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Deserialize `SqrtPriceX64`:
	err = decoder.Decode(&obj.SqrtPriceX64)
	if err != nil {
		return errors.NewField("SqrtPriceX64", err)
	}
	// Deserialize `TickCurrent`:
	err = decoder.Decode(&obj.TickCurrent)
	if err != nil {
		return errors.NewField("TickCurrent", err)
	}
	// Deserialize `Padding3`:
	err = decoder.Decode(&obj.Padding3)
	if err != nil {
		return errors.NewField("Padding3", err)
	}
	// Deserialize `Padding4`:
	err = decoder.Decode(&obj.Padding4)
	if err != nil {
		return errors.NewField("Padding4", err)
	}
	// Deserialize `FeeGrowthGlobal0X64`:
	err = decoder.Decode(&obj.FeeGrowthGlobal0X64)
	if err != nil {
		return errors.NewField("FeeGrowthGlobal0X64", err)
	}
	// Deserialize `FeeGrowthGlobal1X64`:
	err = decoder.Decode(&obj.FeeGrowthGlobal1X64)
	if err != nil {
		return errors.NewField("FeeGrowthGlobal1X64", err)
	}
	// Deserialize `ProtocolFeesToken0`:
	err = decoder.Decode(&obj.ProtocolFeesToken0)
	if err != nil {
		return errors.NewField("ProtocolFeesToken0", err)
	}
	// Deserialize `ProtocolFeesToken1`:
	err = decoder.Decode(&obj.ProtocolFeesToken1)
	if err != nil {
		return errors.NewField("ProtocolFeesToken1", err)
	}
	// Deserialize `SwapInAmountToken0`:
	err = decoder.Decode(&obj.SwapInAmountToken0)
	if err != nil {
		return errors.NewField("SwapInAmountToken0", err)
	}
	// Deserialize `SwapOutAmountToken1`:
	err = decoder.Decode(&obj.SwapOutAmountToken1)
	if err != nil {
		return errors.NewField("SwapOutAmountToken1", err)
	}
	// Deserialize `SwapInAmountToken1`:
	err = decoder.Decode(&obj.SwapInAmountToken1)
	if err != nil {
		return errors.NewField("SwapInAmountToken1", err)
	}
	// Deserialize `SwapOutAmountToken0`:
	err = decoder.Decode(&obj.SwapOutAmountToken0)
	if err != nil {
		return errors.NewField("SwapOutAmountToken0", err)
	}
	// Deserialize `Status`:
	err = decoder.Decode(&obj.Status)
	if err != nil {
		return errors.NewField("Status", err)
	}
	// Deserialize `Padding`:
	err = decoder.Decode(&obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	// Deserialize `RewardInfos`:
	err = decoder.Decode(&obj.RewardInfos)
	if err != nil {
		return errors.NewField("RewardInfos", err)
	}
	// Deserialize `TickArrayBitmap`:
	err = decoder.Decode(&obj.TickArrayBitmap)
	if err != nil {
		return errors.NewField("TickArrayBitmap", err)
	}
	// Deserialize `TotalFeesToken0`:
	err = decoder.Decode(&obj.TotalFeesToken0)
	if err != nil {
		return errors.NewField("TotalFeesToken0", err)
	}
	// Deserialize `TotalFeesClaimedToken0`:
	err = decoder.Decode(&obj.TotalFeesClaimedToken0)
	if err != nil {
		return errors.NewField("TotalFeesClaimedToken0", err)
	}
	// Deserialize `TotalFeesToken1`:
	err = decoder.Decode(&obj.TotalFeesToken1)
	if err != nil {
		return errors.NewField("TotalFeesToken1", err)
	}
	// Deserialize `TotalFeesClaimedToken1`:
	err = decoder.Decode(&obj.TotalFeesClaimedToken1)
	if err != nil {
		return errors.NewField("TotalFeesClaimedToken1", err)
	}
	// Deserialize `FundFeesToken0`:
	err = decoder.Decode(&obj.FundFeesToken0)
	if err != nil {
		return errors.NewField("FundFeesToken0", err)
	}
	// Deserialize `FundFeesToken1`:
	err = decoder.Decode(&obj.FundFeesToken1)
	if err != nil {
		return errors.NewField("FundFeesToken1", err)
	}
	// Deserialize `OpenTime`:
	err = decoder.Decode(&obj.OpenTime)
	if err != nil {
		return errors.NewField("OpenTime", err)
	}
	// Deserialize `RecentEpoch`:
	err = decoder.Decode(&obj.RecentEpoch)
	if err != nil {
		return errors.NewField("RecentEpoch", err)
	}
	// Deserialize `Padding1`:
	err = decoder.Decode(&obj.Padding1)
	if err != nil {
		return errors.NewField("Padding1", err)
	}
	// Deserialize `Padding2`:
	err = decoder.Decode(&obj.Padding2)
	if err != nil {
		return errors.NewField("Padding2", err)
	}
	return nil
}

func (obj *PoolState) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PoolState: %w", err)
	}
	return nil
}

func UnmarshalPoolState(buf []byte) (*PoolState, error) {
	obj := new(PoolState)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type PositionRewardInfo struct {
	GrowthInsideLastX64 binary.Uint128 `json:"growthInsideLastX64"`
	RewardAmountOwed    uint64         `json:"rewardAmountOwed"`
}

func (obj PositionRewardInfo) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `GrowthInsideLastX64`:
	err = encoder.Encode(obj.GrowthInsideLastX64)
	if err != nil {
		return errors.NewField("GrowthInsideLastX64", err)
	}
	// Serialize `RewardAmountOwed`:
	err = encoder.Encode(obj.RewardAmountOwed)
	if err != nil {
		return errors.NewField("RewardAmountOwed", err)
	}
	return nil
}

func (obj PositionRewardInfo) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PositionRewardInfo: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PositionRewardInfo) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `GrowthInsideLastX64`:
	err = decoder.Decode(&obj.GrowthInsideLastX64)
	if err != nil {
		return errors.NewField("GrowthInsideLastX64", err)
	}
	// Deserialize `RewardAmountOwed`:
	err = decoder.Decode(&obj.RewardAmountOwed)
	if err != nil {
		return errors.NewField("RewardAmountOwed", err)
	}
	return nil
}

func (obj *PositionRewardInfo) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PositionRewardInfo: %w", err)
	}
	return nil
}

func UnmarshalPositionRewardInfo(buf []byte) (*PositionRewardInfo, error) {
	obj := new(PositionRewardInfo)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Info stored for each user's position
type ProtocolPositionState struct {
	// Bump to identify PDA
	Bump uint8 `json:"bump"`

	// The ID of the pool with which this token is connected
	PoolId solanago.PublicKey `json:"poolId"`

	// The lower bound tick of the position
	TickLowerIndex int32 `json:"tickLowerIndex"`

	// The upper bound tick of the position
	TickUpperIndex int32 `json:"tickUpperIndex"`

	// The amount of liquidity owned by this position
	Liquidity binary.Uint128 `json:"liquidity"`

	// The token_0 fee growth per unit of liquidity as of the last update to liquidity or fees owed
	FeeGrowthInside0LastX64 binary.Uint128 `json:"feeGrowthInside0LastX64"`

	// The token_1 fee growth per unit of liquidity as of the last update to liquidity or fees owed
	FeeGrowthInside1LastX64 binary.Uint128 `json:"feeGrowthInside1LastX64"`

	// The fees owed to the position owner in token_0
	TokenFeesOwed0 uint64 `json:"tokenFeesOwed0"`

	// The fees owed to the position owner in token_1
	TokenFeesOwed1 uint64 `json:"tokenFeesOwed1"`

	// The reward growth per unit of liquidity as of the last update to liquidity
	RewardGrowthInside [3]binary.Uint128 `json:"rewardGrowthInside"`
	RecentEpoch        uint64            `json:"recentEpoch"`
	Padding            [7]uint64         `json:"padding"`
}

func (obj ProtocolPositionState) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `PoolId`:
	err = encoder.Encode(obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Serialize `TickLowerIndex`:
	err = encoder.Encode(obj.TickLowerIndex)
	if err != nil {
		return errors.NewField("TickLowerIndex", err)
	}
	// Serialize `TickUpperIndex`:
	err = encoder.Encode(obj.TickUpperIndex)
	if err != nil {
		return errors.NewField("TickUpperIndex", err)
	}
	// Serialize `Liquidity`:
	err = encoder.Encode(obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Serialize `FeeGrowthInside0LastX64`:
	err = encoder.Encode(obj.FeeGrowthInside0LastX64)
	if err != nil {
		return errors.NewField("FeeGrowthInside0LastX64", err)
	}
	// Serialize `FeeGrowthInside1LastX64`:
	err = encoder.Encode(obj.FeeGrowthInside1LastX64)
	if err != nil {
		return errors.NewField("FeeGrowthInside1LastX64", err)
	}
	// Serialize `TokenFeesOwed0`:
	err = encoder.Encode(obj.TokenFeesOwed0)
	if err != nil {
		return errors.NewField("TokenFeesOwed0", err)
	}
	// Serialize `TokenFeesOwed1`:
	err = encoder.Encode(obj.TokenFeesOwed1)
	if err != nil {
		return errors.NewField("TokenFeesOwed1", err)
	}
	// Serialize `RewardGrowthInside`:
	err = encoder.Encode(obj.RewardGrowthInside)
	if err != nil {
		return errors.NewField("RewardGrowthInside", err)
	}
	// Serialize `RecentEpoch`:
	err = encoder.Encode(obj.RecentEpoch)
	if err != nil {
		return errors.NewField("RecentEpoch", err)
	}
	// Serialize `Padding`:
	err = encoder.Encode(obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj ProtocolPositionState) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ProtocolPositionState: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ProtocolPositionState) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `PoolId`:
	err = decoder.Decode(&obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Deserialize `TickLowerIndex`:
	err = decoder.Decode(&obj.TickLowerIndex)
	if err != nil {
		return errors.NewField("TickLowerIndex", err)
	}
	// Deserialize `TickUpperIndex`:
	err = decoder.Decode(&obj.TickUpperIndex)
	if err != nil {
		return errors.NewField("TickUpperIndex", err)
	}
	// Deserialize `Liquidity`:
	err = decoder.Decode(&obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Deserialize `FeeGrowthInside0LastX64`:
	err = decoder.Decode(&obj.FeeGrowthInside0LastX64)
	if err != nil {
		return errors.NewField("FeeGrowthInside0LastX64", err)
	}
	// Deserialize `FeeGrowthInside1LastX64`:
	err = decoder.Decode(&obj.FeeGrowthInside1LastX64)
	if err != nil {
		return errors.NewField("FeeGrowthInside1LastX64", err)
	}
	// Deserialize `TokenFeesOwed0`:
	err = decoder.Decode(&obj.TokenFeesOwed0)
	if err != nil {
		return errors.NewField("TokenFeesOwed0", err)
	}
	// Deserialize `TokenFeesOwed1`:
	err = decoder.Decode(&obj.TokenFeesOwed1)
	if err != nil {
		return errors.NewField("TokenFeesOwed1", err)
	}
	// Deserialize `RewardGrowthInside`:
	err = decoder.Decode(&obj.RewardGrowthInside)
	if err != nil {
		return errors.NewField("RewardGrowthInside", err)
	}
	// Deserialize `RecentEpoch`:
	err = decoder.Decode(&obj.RecentEpoch)
	if err != nil {
		return errors.NewField("RecentEpoch", err)
	}
	// Deserialize `Padding`:
	err = decoder.Decode(&obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj *ProtocolPositionState) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ProtocolPositionState: %w", err)
	}
	return nil
}

func UnmarshalProtocolPositionState(buf []byte) (*ProtocolPositionState, error) {
	obj := new(ProtocolPositionState)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type RewardInfo struct {
	// Reward state
	RewardState uint8 `json:"rewardState"`

	// Reward open time
	OpenTime uint64 `json:"openTime"`

	// Reward end time
	EndTime uint64 `json:"endTime"`

	// Reward last update time
	LastUpdateTime uint64 `json:"lastUpdateTime"`

	// Q64.64 number indicates how many tokens per second are earned per unit of liquidity.
	EmissionsPerSecondX64 binary.Uint128 `json:"emissionsPerSecondX64"`

	// The total amount of reward emissioned
	RewardTotalEmissioned uint64 `json:"rewardTotalEmissioned"`

	// The total amount of claimed reward
	RewardClaimed uint64 `json:"rewardClaimed"`

	// Reward token mint.
	TokenMint solanago.PublicKey `json:"tokenMint"`

	// Reward vault token account.
	TokenVault solanago.PublicKey `json:"tokenVault"`

	// The owner that has permission to set reward param
	Authority solanago.PublicKey `json:"authority"`

	// Q64.64 number that tracks the total tokens earned per unit of liquidity since the reward
	// emissions were turned on.
	RewardGrowthGlobalX64 binary.Uint128 `json:"rewardGrowthGlobalX64"`
}

func (obj RewardInfo) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `RewardState`:
	err = encoder.Encode(obj.RewardState)
	if err != nil {
		return errors.NewField("RewardState", err)
	}
	// Serialize `OpenTime`:
	err = encoder.Encode(obj.OpenTime)
	if err != nil {
		return errors.NewField("OpenTime", err)
	}
	// Serialize `EndTime`:
	err = encoder.Encode(obj.EndTime)
	if err != nil {
		return errors.NewField("EndTime", err)
	}
	// Serialize `LastUpdateTime`:
	err = encoder.Encode(obj.LastUpdateTime)
	if err != nil {
		return errors.NewField("LastUpdateTime", err)
	}
	// Serialize `EmissionsPerSecondX64`:
	err = encoder.Encode(obj.EmissionsPerSecondX64)
	if err != nil {
		return errors.NewField("EmissionsPerSecondX64", err)
	}
	// Serialize `RewardTotalEmissioned`:
	err = encoder.Encode(obj.RewardTotalEmissioned)
	if err != nil {
		return errors.NewField("RewardTotalEmissioned", err)
	}
	// Serialize `RewardClaimed`:
	err = encoder.Encode(obj.RewardClaimed)
	if err != nil {
		return errors.NewField("RewardClaimed", err)
	}
	// Serialize `TokenMint`:
	err = encoder.Encode(obj.TokenMint)
	if err != nil {
		return errors.NewField("TokenMint", err)
	}
	// Serialize `TokenVault`:
	err = encoder.Encode(obj.TokenVault)
	if err != nil {
		return errors.NewField("TokenVault", err)
	}
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `RewardGrowthGlobalX64`:
	err = encoder.Encode(obj.RewardGrowthGlobalX64)
	if err != nil {
		return errors.NewField("RewardGrowthGlobalX64", err)
	}
	return nil
}

func (obj RewardInfo) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding RewardInfo: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *RewardInfo) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `RewardState`:
	err = decoder.Decode(&obj.RewardState)
	if err != nil {
		return errors.NewField("RewardState", err)
	}
	// Deserialize `OpenTime`:
	err = decoder.Decode(&obj.OpenTime)
	if err != nil {
		return errors.NewField("OpenTime", err)
	}
	// Deserialize `EndTime`:
	err = decoder.Decode(&obj.EndTime)
	if err != nil {
		return errors.NewField("EndTime", err)
	}
	// Deserialize `LastUpdateTime`:
	err = decoder.Decode(&obj.LastUpdateTime)
	if err != nil {
		return errors.NewField("LastUpdateTime", err)
	}
	// Deserialize `EmissionsPerSecondX64`:
	err = decoder.Decode(&obj.EmissionsPerSecondX64)
	if err != nil {
		return errors.NewField("EmissionsPerSecondX64", err)
	}
	// Deserialize `RewardTotalEmissioned`:
	err = decoder.Decode(&obj.RewardTotalEmissioned)
	if err != nil {
		return errors.NewField("RewardTotalEmissioned", err)
	}
	// Deserialize `RewardClaimed`:
	err = decoder.Decode(&obj.RewardClaimed)
	if err != nil {
		return errors.NewField("RewardClaimed", err)
	}
	// Deserialize `TokenMint`:
	err = decoder.Decode(&obj.TokenMint)
	if err != nil {
		return errors.NewField("TokenMint", err)
	}
	// Deserialize `TokenVault`:
	err = decoder.Decode(&obj.TokenVault)
	if err != nil {
		return errors.NewField("TokenVault", err)
	}
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `RewardGrowthGlobalX64`:
	err = decoder.Decode(&obj.RewardGrowthGlobalX64)
	if err != nil {
		return errors.NewField("RewardGrowthGlobalX64", err)
	}
	return nil
}

func (obj *RewardInfo) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling RewardInfo: %w", err)
	}
	return nil
}

func UnmarshalRewardInfo(buf []byte) (*RewardInfo, error) {
	obj := new(RewardInfo)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Holds the current owner of the factory
type SupportMintAssociated struct {
	// Bump to identify PDA
	Bump uint8 `json:"bump"`

	// Address of the supported token22 mint
	Mint    solanago.PublicKey `json:"mint"`
	Padding [8]uint64          `json:"padding"`
}

func (obj SupportMintAssociated) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `Padding`:
	err = encoder.Encode(obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj SupportMintAssociated) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SupportMintAssociated: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SupportMintAssociated) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `Padding`:
	err = decoder.Decode(&obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj *SupportMintAssociated) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SupportMintAssociated: %w", err)
	}
	return nil
}

func UnmarshalSupportMintAssociated(buf []byte) (*SupportMintAssociated, error) {
	obj := new(SupportMintAssociated)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted by when a swap is performed for a pool
type SwapEvent struct {
	// The pool for which token_0 and token_1 were swapped
	PoolState solanago.PublicKey `json:"poolState"`

	// The address that initiated the swap call, and that received the callback
	Sender solanago.PublicKey `json:"sender"`

	// The payer token account in zero for one swaps, or the recipient token account
	// in one for zero swaps
	TokenAccount0 solanago.PublicKey `json:"tokenAccount0"`

	// The payer token account in one for zero swaps, or the recipient token account
	// in zero for one swaps
	TokenAccount1 solanago.PublicKey `json:"tokenAccount1"`

	// The real delta amount of the token_0 of the pool or user
	Amount0 uint64 `json:"amount0"`

	// The transfer fee charged by the withheld_amount of the token_0
	TransferFee0 uint64 `json:"transferFee0"`

	// The real delta of the token_1 of the pool or user
	Amount1 uint64 `json:"amount1"`

	// The transfer fee charged by the withheld_amount of the token_1
	TransferFee1 uint64 `json:"transferFee1"`

	// if true, amount_0 is negtive and amount_1 is positive
	ZeroForOne bool `json:"zeroForOne"`

	// The sqrt(price) of the pool after the swap, as a Q64.64
	SqrtPriceX64 binary.Uint128 `json:"sqrtPriceX64"`

	// The liquidity of the pool after the swap
	Liquidity binary.Uint128 `json:"liquidity"`

	// The log base 1.0001 of price of the pool after the swap
	Tick int32 `json:"tick"`
}

func (obj SwapEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PoolState`:
	err = encoder.Encode(obj.PoolState)
	if err != nil {
		return errors.NewField("PoolState", err)
	}
	// Serialize `Sender`:
	err = encoder.Encode(obj.Sender)
	if err != nil {
		return errors.NewField("Sender", err)
	}
	// Serialize `TokenAccount0`:
	err = encoder.Encode(obj.TokenAccount0)
	if err != nil {
		return errors.NewField("TokenAccount0", err)
	}
	// Serialize `TokenAccount1`:
	err = encoder.Encode(obj.TokenAccount1)
	if err != nil {
		return errors.NewField("TokenAccount1", err)
	}
	// Serialize `Amount0`:
	err = encoder.Encode(obj.Amount0)
	if err != nil {
		return errors.NewField("Amount0", err)
	}
	// Serialize `TransferFee0`:
	err = encoder.Encode(obj.TransferFee0)
	if err != nil {
		return errors.NewField("TransferFee0", err)
	}
	// Serialize `Amount1`:
	err = encoder.Encode(obj.Amount1)
	if err != nil {
		return errors.NewField("Amount1", err)
	}
	// Serialize `TransferFee1`:
	err = encoder.Encode(obj.TransferFee1)
	if err != nil {
		return errors.NewField("TransferFee1", err)
	}
	// Serialize `ZeroForOne`:
	err = encoder.Encode(obj.ZeroForOne)
	if err != nil {
		return errors.NewField("ZeroForOne", err)
	}
	// Serialize `SqrtPriceX64`:
	err = encoder.Encode(obj.SqrtPriceX64)
	if err != nil {
		return errors.NewField("SqrtPriceX64", err)
	}
	// Serialize `Liquidity`:
	err = encoder.Encode(obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Serialize `Tick`:
	err = encoder.Encode(obj.Tick)
	if err != nil {
		return errors.NewField("Tick", err)
	}
	return nil
}

func (obj SwapEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SwapEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SwapEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PoolState`:
	err = decoder.Decode(&obj.PoolState)
	if err != nil {
		return errors.NewField("PoolState", err)
	}
	// Deserialize `Sender`:
	err = decoder.Decode(&obj.Sender)
	if err != nil {
		return errors.NewField("Sender", err)
	}
	// Deserialize `TokenAccount0`:
	err = decoder.Decode(&obj.TokenAccount0)
	if err != nil {
		return errors.NewField("TokenAccount0", err)
	}
	// Deserialize `TokenAccount1`:
	err = decoder.Decode(&obj.TokenAccount1)
	if err != nil {
		return errors.NewField("TokenAccount1", err)
	}
	// Deserialize `Amount0`:
	err = decoder.Decode(&obj.Amount0)
	if err != nil {
		return errors.NewField("Amount0", err)
	}
	// Deserialize `TransferFee0`:
	err = decoder.Decode(&obj.TransferFee0)
	if err != nil {
		return errors.NewField("TransferFee0", err)
	}
	// Deserialize `Amount1`:
	err = decoder.Decode(&obj.Amount1)
	if err != nil {
		return errors.NewField("Amount1", err)
	}
	// Deserialize `TransferFee1`:
	err = decoder.Decode(&obj.TransferFee1)
	if err != nil {
		return errors.NewField("TransferFee1", err)
	}
	// Deserialize `ZeroForOne`:
	err = decoder.Decode(&obj.ZeroForOne)
	if err != nil {
		return errors.NewField("ZeroForOne", err)
	}
	// Deserialize `SqrtPriceX64`:
	err = decoder.Decode(&obj.SqrtPriceX64)
	if err != nil {
		return errors.NewField("SqrtPriceX64", err)
	}
	// Deserialize `Liquidity`:
	err = decoder.Decode(&obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Deserialize `Tick`:
	err = decoder.Decode(&obj.Tick)
	if err != nil {
		return errors.NewField("Tick", err)
	}
	return nil
}

func (obj *SwapEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SwapEvent: %w", err)
	}
	return nil
}

func UnmarshalSwapEvent(buf []byte) (*SwapEvent, error) {
	obj := new(SwapEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type TickArrayBitmapExtension struct {
	PoolId solanago.PublicKey `json:"poolId"`

	// Packed initialized tick array state for start_tick_index is positive
	PositiveTickArrayBitmap [14][8]uint64 `json:"positiveTickArrayBitmap"`

	// Packed initialized tick array state for start_tick_index is negitive
	NegativeTickArrayBitmap [14][8]uint64 `json:"negativeTickArrayBitmap"`
}

func (obj TickArrayBitmapExtension) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PoolId`:
	err = encoder.Encode(obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Serialize `PositiveTickArrayBitmap`:
	err = encoder.Encode(obj.PositiveTickArrayBitmap)
	if err != nil {
		return errors.NewField("PositiveTickArrayBitmap", err)
	}
	// Serialize `NegativeTickArrayBitmap`:
	err = encoder.Encode(obj.NegativeTickArrayBitmap)
	if err != nil {
		return errors.NewField("NegativeTickArrayBitmap", err)
	}
	return nil
}

func (obj TickArrayBitmapExtension) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TickArrayBitmapExtension: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TickArrayBitmapExtension) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PoolId`:
	err = decoder.Decode(&obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Deserialize `PositiveTickArrayBitmap`:
	err = decoder.Decode(&obj.PositiveTickArrayBitmap)
	if err != nil {
		return errors.NewField("PositiveTickArrayBitmap", err)
	}
	// Deserialize `NegativeTickArrayBitmap`:
	err = decoder.Decode(&obj.NegativeTickArrayBitmap)
	if err != nil {
		return errors.NewField("NegativeTickArrayBitmap", err)
	}
	return nil
}

func (obj *TickArrayBitmapExtension) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TickArrayBitmapExtension: %w", err)
	}
	return nil
}

func UnmarshalTickArrayBitmapExtension(buf []byte) (*TickArrayBitmapExtension, error) {
	obj := new(TickArrayBitmapExtension)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type TickArrayState struct {
	PoolId               solanago.PublicKey `json:"poolId"`
	StartTickIndex       int32              `json:"startTickIndex"`
	Ticks                [60]TickState      `json:"ticks"`
	InitializedTickCount uint8              `json:"initializedTickCount"`
	RecentEpoch          uint64             `json:"recentEpoch"`
	Padding              [107]uint8         `json:"padding"`
}

func (obj TickArrayState) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PoolId`:
	err = encoder.Encode(obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Serialize `StartTickIndex`:
	err = encoder.Encode(obj.StartTickIndex)
	if err != nil {
		return errors.NewField("StartTickIndex", err)
	}
	// Serialize `Ticks`:
	err = encoder.Encode(obj.Ticks)
	if err != nil {
		return errors.NewField("Ticks", err)
	}
	// Serialize `InitializedTickCount`:
	err = encoder.Encode(obj.InitializedTickCount)
	if err != nil {
		return errors.NewField("InitializedTickCount", err)
	}
	// Serialize `RecentEpoch`:
	err = encoder.Encode(obj.RecentEpoch)
	if err != nil {
		return errors.NewField("RecentEpoch", err)
	}
	// Serialize `Padding`:
	err = encoder.Encode(obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj TickArrayState) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TickArrayState: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TickArrayState) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PoolId`:
	err = decoder.Decode(&obj.PoolId)
	if err != nil {
		return errors.NewField("PoolId", err)
	}
	// Deserialize `StartTickIndex`:
	err = decoder.Decode(&obj.StartTickIndex)
	if err != nil {
		return errors.NewField("StartTickIndex", err)
	}
	// Deserialize `Ticks`:
	err = decoder.Decode(&obj.Ticks)
	if err != nil {
		return errors.NewField("Ticks", err)
	}
	// Deserialize `InitializedTickCount`:
	err = decoder.Decode(&obj.InitializedTickCount)
	if err != nil {
		return errors.NewField("InitializedTickCount", err)
	}
	// Deserialize `RecentEpoch`:
	err = decoder.Decode(&obj.RecentEpoch)
	if err != nil {
		return errors.NewField("RecentEpoch", err)
	}
	// Deserialize `Padding`:
	err = decoder.Decode(&obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj *TickArrayState) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TickArrayState: %w", err)
	}
	return nil
}

func UnmarshalTickArrayState(buf []byte) (*TickArrayState, error) {
	obj := new(TickArrayState)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type TickState struct {
	Tick int32 `json:"tick"`

	// Amount of net liquidity added (subtracted) when tick is crossed from left to right (right to left)
	LiquidityNet binary.Int128 `json:"liquidityNet"`

	// The total position liquidity that references this tick
	LiquidityGross binary.Uint128 `json:"liquidityGross"`

	// Fee growth per unit of liquidity on the _other_ side of this tick (relative to the current tick)
	// only has relative meaning, not absolute — the value depends on when the tick is initialized
	FeeGrowthOutside0X64    binary.Uint128    `json:"feeGrowthOutside0X64"`
	FeeGrowthOutside1X64    binary.Uint128    `json:"feeGrowthOutside1X64"`
	RewardGrowthsOutsideX64 [3]binary.Uint128 `json:"rewardGrowthsOutsideX64"`
	Padding                 [13]uint32        `json:"padding"`
}

func (obj TickState) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Tick`:
	err = encoder.Encode(obj.Tick)
	if err != nil {
		return errors.NewField("Tick", err)
	}
	// Serialize `LiquidityNet`:
	err = encoder.Encode(obj.LiquidityNet)
	if err != nil {
		return errors.NewField("LiquidityNet", err)
	}
	// Serialize `LiquidityGross`:
	err = encoder.Encode(obj.LiquidityGross)
	if err != nil {
		return errors.NewField("LiquidityGross", err)
	}
	// Serialize `FeeGrowthOutside0X64`:
	err = encoder.Encode(obj.FeeGrowthOutside0X64)
	if err != nil {
		return errors.NewField("FeeGrowthOutside0X64", err)
	}
	// Serialize `FeeGrowthOutside1X64`:
	err = encoder.Encode(obj.FeeGrowthOutside1X64)
	if err != nil {
		return errors.NewField("FeeGrowthOutside1X64", err)
	}
	// Serialize `RewardGrowthsOutsideX64`:
	err = encoder.Encode(obj.RewardGrowthsOutsideX64)
	if err != nil {
		return errors.NewField("RewardGrowthsOutsideX64", err)
	}
	// Serialize `Padding`:
	err = encoder.Encode(obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj TickState) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TickState: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TickState) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Tick`:
	err = decoder.Decode(&obj.Tick)
	if err != nil {
		return errors.NewField("Tick", err)
	}
	// Deserialize `LiquidityNet`:
	err = decoder.Decode(&obj.LiquidityNet)
	if err != nil {
		return errors.NewField("LiquidityNet", err)
	}
	// Deserialize `LiquidityGross`:
	err = decoder.Decode(&obj.LiquidityGross)
	if err != nil {
		return errors.NewField("LiquidityGross", err)
	}
	// Deserialize `FeeGrowthOutside0X64`:
	err = decoder.Decode(&obj.FeeGrowthOutside0X64)
	if err != nil {
		return errors.NewField("FeeGrowthOutside0X64", err)
	}
	// Deserialize `FeeGrowthOutside1X64`:
	err = decoder.Decode(&obj.FeeGrowthOutside1X64)
	if err != nil {
		return errors.NewField("FeeGrowthOutside1X64", err)
	}
	// Deserialize `RewardGrowthsOutsideX64`:
	err = decoder.Decode(&obj.RewardGrowthsOutsideX64)
	if err != nil {
		return errors.NewField("RewardGrowthsOutsideX64", err)
	}
	// Deserialize `Padding`:
	err = decoder.Decode(&obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj *TickState) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TickState: %w", err)
	}
	return nil
}

func UnmarshalTickState(buf []byte) (*TickState, error) {
	obj := new(TickState)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted when Reward are updated for a pool
type UpdateRewardInfosEvent struct {
	// Reward info
	RewardGrowthGlobalX64 [3]binary.Uint128 `json:"rewardGrowthGlobalX64"`
}

func (obj UpdateRewardInfosEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `RewardGrowthGlobalX64`:
	err = encoder.Encode(obj.RewardGrowthGlobalX64)
	if err != nil {
		return errors.NewField("RewardGrowthGlobalX64", err)
	}
	return nil
}

func (obj UpdateRewardInfosEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding UpdateRewardInfosEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *UpdateRewardInfosEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `RewardGrowthGlobalX64`:
	err = decoder.Decode(&obj.RewardGrowthGlobalX64)
	if err != nil {
		return errors.NewField("RewardGrowthGlobalX64", err)
	}
	return nil
}

func (obj *UpdateRewardInfosEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling UpdateRewardInfosEvent: %w", err)
	}
	return nil
}

func UnmarshalUpdateRewardInfosEvent(buf []byte) (*UpdateRewardInfosEvent, error) {
	obj := new(UpdateRewardInfosEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
