// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package weighted_swap

// Account discriminators
var (
	Account_Pool  = [8]byte{241, 154, 109, 4, 17, 177, 109, 188}
	Account_Vault = [8]byte{211, 8, 232, 43, 2, 152, 117, 119}
)

// Event discriminators
var (
	Event_PoolBalanceUpdatedEvent = [8]byte{172, 82, 114, 207, 27, 103, 211, 4}
	Event_PoolUpdatedEvent        = [8]byte{128, 39, 94, 221, 230, 222, 127, 141}
)

// Instruction discriminators
var (
	Instruction_AcceptOwner     = [8]byte{176, 23, 41, 28, 23, 111, 8, 4}
	Instruction_ChangeMaxSupply = [8]byte{93, 176, 0, 205, 69, 63, 87, 80}
	Instruction_ChangeSwapFee   = [8]byte{231, 15, 132, 51, 132, 165, 64, 170}
	Instruction_Deposit         = [8]byte{242, 35, 198, 137, 82, 225, 242, 182}
	Instruction_Initialize      = [8]byte{175, 175, 109, 31, 13, 152, 155, 237}
	Instruction_Pause           = [8]byte{211, 22, 221, 251, 74, 121, 193, 47}
	Instruction_RejectOwner     = [8]byte{238, 206, 198, 215, 51, 178, 133, 228}
	Instruction_Shutdown        = [8]byte{146, 204, 241, 213, 86, 21, 253, 211}
	Instruction_Swap            = [8]byte{248, 198, 158, 145, 225, 117, 135, 200}
	Instruction_SwapV2          = [8]byte{43, 4, 237, 11, 26, 201, 30, 98}
	Instruction_TransferOwner   = [8]byte{245, 25, 221, 175, 106, 229, 225, 45}
	Instruction_Unpause         = [8]byte{169, 144, 4, 38, 10, 141, 188, 255}
	Instruction_Withdraw        = [8]byte{183, 18, 70, 156, 148, 109, 161, 34}
)
