// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package weighted_swap

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("swapFpHZwjELNnjvThjajtiVmkz3yPQEHjLtka2fwHW")
