// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package weighted_swap

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type Pool struct {
	Owner         solanago.PublicKey  `json:"owner"`
	Vault         solanago.PublicKey  `json:"vault"`
	Mint          solanago.PublicKey  `json:"mint"`
	AuthorityBump uint8               `json:"authorityBump"`
	IsActive      bool                `json:"isActive"`
	Invariant     uint64              `json:"invariant"`
	SwapFee       uint64              `json:"swapFee"`
	Tokens        []PoolToken         `json:"tokens"`
	PendingOwner  *solanago.PublicKey `bin:"optional" json:"pendingOwner,omitempty"`
	MaxSupply     uint64              `json:"maxSupply"`
}

func (obj Pool) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Owner`:
	err = encoder.Encode(obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Serialize `Vault`:
	err = encoder.Encode(obj.Vault)
	if err != nil {
		return errors.NewField("Vault", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `AuthorityBump`:
	err = encoder.Encode(obj.AuthorityBump)
	if err != nil {
		return errors.NewField("AuthorityBump", err)
	}
	// Serialize `IsActive`:
	err = encoder.Encode(obj.IsActive)
	if err != nil {
		return errors.NewField("IsActive", err)
	}
	// Serialize `Invariant`:
	err = encoder.Encode(obj.Invariant)
	if err != nil {
		return errors.NewField("Invariant", err)
	}
	// Serialize `SwapFee`:
	err = encoder.Encode(obj.SwapFee)
	if err != nil {
		return errors.NewField("SwapFee", err)
	}
	// Serialize `Tokens`:
	err = encoder.Encode(obj.Tokens)
	if err != nil {
		return errors.NewField("Tokens", err)
	}
	// Serialize `PendingOwner` (optional):
	{
		if obj.PendingOwner == nil {
			err = encoder.WriteOption(false)
			if err != nil {
				return errors.NewOption("PendingOwner", fmt.Errorf("error while encoding optionality: %w", err))
			}
		} else {
			err = encoder.WriteOption(true)
			if err != nil {
				return errors.NewOption("PendingOwner", fmt.Errorf("error while encoding optionality: %w", err))
			}
			err = encoder.Encode(obj.PendingOwner)
			if err != nil {
				return errors.NewField("PendingOwner", err)
			}
		}
	}
	// Serialize `MaxSupply`:
	err = encoder.Encode(obj.MaxSupply)
	if err != nil {
		return errors.NewField("MaxSupply", err)
	}
	return nil
}

func (obj Pool) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Pool: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Pool) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Owner`:
	err = decoder.Decode(&obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Deserialize `Vault`:
	err = decoder.Decode(&obj.Vault)
	if err != nil {
		return errors.NewField("Vault", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `AuthorityBump`:
	err = decoder.Decode(&obj.AuthorityBump)
	if err != nil {
		return errors.NewField("AuthorityBump", err)
	}
	// Deserialize `IsActive`:
	err = decoder.Decode(&obj.IsActive)
	if err != nil {
		return errors.NewField("IsActive", err)
	}
	// Deserialize `Invariant`:
	err = decoder.Decode(&obj.Invariant)
	if err != nil {
		return errors.NewField("Invariant", err)
	}
	// Deserialize `SwapFee`:
	err = decoder.Decode(&obj.SwapFee)
	if err != nil {
		return errors.NewField("SwapFee", err)
	}
	// Deserialize `Tokens`:
	err = decoder.Decode(&obj.Tokens)
	if err != nil {
		return errors.NewField("Tokens", err)
	}
	// Deserialize `PendingOwner` (optional):
	{
		ok, err := decoder.ReadOption()
		if err != nil {
			return errors.NewOption("PendingOwner", fmt.Errorf("error while reading optionality: %w", err))
		}
		if ok {
			err = decoder.Decode(&obj.PendingOwner)
			if err != nil {
				return errors.NewField("PendingOwner", err)
			}
		}
	}
	// Deserialize `MaxSupply`:
	err = decoder.Decode(&obj.MaxSupply)
	if err != nil {
		return errors.NewField("MaxSupply", err)
	}
	return nil
}

func (obj *Pool) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Pool: %w", err)
	}
	return nil
}

func UnmarshalPool(buf []byte) (*Pool, error) {
	obj := new(Pool)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type PoolBalanceUpdatedData struct {
	Balances []uint64 `json:"balances"`
}

func (obj PoolBalanceUpdatedData) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Balances`:
	err = encoder.Encode(obj.Balances)
	if err != nil {
		return errors.NewField("Balances", err)
	}
	return nil
}

func (obj PoolBalanceUpdatedData) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PoolBalanceUpdatedData: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PoolBalanceUpdatedData) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Balances`:
	err = decoder.Decode(&obj.Balances)
	if err != nil {
		return errors.NewField("Balances", err)
	}
	return nil
}

func (obj *PoolBalanceUpdatedData) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PoolBalanceUpdatedData: %w", err)
	}
	return nil
}

func UnmarshalPoolBalanceUpdatedData(buf []byte) (*PoolBalanceUpdatedData, error) {
	obj := new(PoolBalanceUpdatedData)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type PoolBalanceUpdatedEvent struct {
	Pubkey solanago.PublicKey     `json:"pubkey"`
	Data   PoolBalanceUpdatedData `json:"data"`
}

func (obj PoolBalanceUpdatedEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Pubkey`:
	err = encoder.Encode(obj.Pubkey)
	if err != nil {
		return errors.NewField("Pubkey", err)
	}
	// Serialize `Data`:
	err = encoder.Encode(obj.Data)
	if err != nil {
		return errors.NewField("Data", err)
	}
	return nil
}

func (obj PoolBalanceUpdatedEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PoolBalanceUpdatedEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PoolBalanceUpdatedEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Pubkey`:
	err = decoder.Decode(&obj.Pubkey)
	if err != nil {
		return errors.NewField("Pubkey", err)
	}
	// Deserialize `Data`:
	err = decoder.Decode(&obj.Data)
	if err != nil {
		return errors.NewField("Data", err)
	}
	return nil
}

func (obj *PoolBalanceUpdatedEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PoolBalanceUpdatedEvent: %w", err)
	}
	return nil
}

func UnmarshalPoolBalanceUpdatedEvent(buf []byte) (*PoolBalanceUpdatedEvent, error) {
	obj := new(PoolBalanceUpdatedEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type PoolToken struct {
	Mint          solanago.PublicKey `json:"mint"`
	Decimals      uint8              `json:"decimals"`
	ScalingUp     bool               `json:"scalingUp"`
	ScalingFactor uint64             `json:"scalingFactor"`
	Balance       uint64             `json:"balance"`
	Weight        uint64             `json:"weight"`
}

func (obj PoolToken) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `Decimals`:
	err = encoder.Encode(obj.Decimals)
	if err != nil {
		return errors.NewField("Decimals", err)
	}
	// Serialize `ScalingUp`:
	err = encoder.Encode(obj.ScalingUp)
	if err != nil {
		return errors.NewField("ScalingUp", err)
	}
	// Serialize `ScalingFactor`:
	err = encoder.Encode(obj.ScalingFactor)
	if err != nil {
		return errors.NewField("ScalingFactor", err)
	}
	// Serialize `Balance`:
	err = encoder.Encode(obj.Balance)
	if err != nil {
		return errors.NewField("Balance", err)
	}
	// Serialize `Weight`:
	err = encoder.Encode(obj.Weight)
	if err != nil {
		return errors.NewField("Weight", err)
	}
	return nil
}

func (obj PoolToken) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PoolToken: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PoolToken) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `Decimals`:
	err = decoder.Decode(&obj.Decimals)
	if err != nil {
		return errors.NewField("Decimals", err)
	}
	// Deserialize `ScalingUp`:
	err = decoder.Decode(&obj.ScalingUp)
	if err != nil {
		return errors.NewField("ScalingUp", err)
	}
	// Deserialize `ScalingFactor`:
	err = decoder.Decode(&obj.ScalingFactor)
	if err != nil {
		return errors.NewField("ScalingFactor", err)
	}
	// Deserialize `Balance`:
	err = decoder.Decode(&obj.Balance)
	if err != nil {
		return errors.NewField("Balance", err)
	}
	// Deserialize `Weight`:
	err = decoder.Decode(&obj.Weight)
	if err != nil {
		return errors.NewField("Weight", err)
	}
	return nil
}

func (obj *PoolToken) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PoolToken: %w", err)
	}
	return nil
}

func UnmarshalPoolToken(buf []byte) (*PoolToken, error) {
	obj := new(PoolToken)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type PoolUpdatedData struct {
	IsActive  bool   `json:"isActive"`
	SwapFee   uint64 `json:"swapFee"`
	MaxSupply uint64 `json:"maxSupply"`
}

func (obj PoolUpdatedData) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `IsActive`:
	err = encoder.Encode(obj.IsActive)
	if err != nil {
		return errors.NewField("IsActive", err)
	}
	// Serialize `SwapFee`:
	err = encoder.Encode(obj.SwapFee)
	if err != nil {
		return errors.NewField("SwapFee", err)
	}
	// Serialize `MaxSupply`:
	err = encoder.Encode(obj.MaxSupply)
	if err != nil {
		return errors.NewField("MaxSupply", err)
	}
	return nil
}

func (obj PoolUpdatedData) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PoolUpdatedData: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PoolUpdatedData) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `IsActive`:
	err = decoder.Decode(&obj.IsActive)
	if err != nil {
		return errors.NewField("IsActive", err)
	}
	// Deserialize `SwapFee`:
	err = decoder.Decode(&obj.SwapFee)
	if err != nil {
		return errors.NewField("SwapFee", err)
	}
	// Deserialize `MaxSupply`:
	err = decoder.Decode(&obj.MaxSupply)
	if err != nil {
		return errors.NewField("MaxSupply", err)
	}
	return nil
}

func (obj *PoolUpdatedData) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PoolUpdatedData: %w", err)
	}
	return nil
}

func UnmarshalPoolUpdatedData(buf []byte) (*PoolUpdatedData, error) {
	obj := new(PoolUpdatedData)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type PoolUpdatedEvent struct {
	Pubkey solanago.PublicKey `json:"pubkey"`
	Data   PoolUpdatedData    `json:"data"`
}

func (obj PoolUpdatedEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Pubkey`:
	err = encoder.Encode(obj.Pubkey)
	if err != nil {
		return errors.NewField("Pubkey", err)
	}
	// Serialize `Data`:
	err = encoder.Encode(obj.Data)
	if err != nil {
		return errors.NewField("Data", err)
	}
	return nil
}

func (obj PoolUpdatedEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PoolUpdatedEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PoolUpdatedEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Pubkey`:
	err = decoder.Decode(&obj.Pubkey)
	if err != nil {
		return errors.NewField("Pubkey", err)
	}
	// Deserialize `Data`:
	err = decoder.Decode(&obj.Data)
	if err != nil {
		return errors.NewField("Data", err)
	}
	return nil
}

func (obj *PoolUpdatedEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PoolUpdatedEvent: %w", err)
	}
	return nil
}

func UnmarshalPoolUpdatedEvent(buf []byte) (*PoolUpdatedEvent, error) {
	obj := new(PoolUpdatedEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Vault struct {
	Admin solanago.PublicKey `json:"admin"`

	// PDA of pool programs seeded by vault address
	WithdrawAuthority solanago.PublicKey `json:"withdrawAuthority"`

	// bump seed of withdraw_authority PDA
	WithdrawAuthorityBump uint8 `json:"withdrawAuthorityBump"`

	// bump seed of vault_authority PDA
	AuthorityBump  uint8               `json:"authorityBump"`
	IsActive       bool                `json:"isActive"`
	Beneficiary    solanago.PublicKey  `json:"beneficiary"`
	BeneficiaryFee uint64              `json:"beneficiaryFee"`
	PendingAdmin   *solanago.PublicKey `bin:"optional" json:"pendingAdmin,omitempty"`
}

func (obj Vault) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Admin`:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Serialize `WithdrawAuthority`:
	err = encoder.Encode(obj.WithdrawAuthority)
	if err != nil {
		return errors.NewField("WithdrawAuthority", err)
	}
	// Serialize `WithdrawAuthorityBump`:
	err = encoder.Encode(obj.WithdrawAuthorityBump)
	if err != nil {
		return errors.NewField("WithdrawAuthorityBump", err)
	}
	// Serialize `AuthorityBump`:
	err = encoder.Encode(obj.AuthorityBump)
	if err != nil {
		return errors.NewField("AuthorityBump", err)
	}
	// Serialize `IsActive`:
	err = encoder.Encode(obj.IsActive)
	if err != nil {
		return errors.NewField("IsActive", err)
	}
	// Serialize `Beneficiary`:
	err = encoder.Encode(obj.Beneficiary)
	if err != nil {
		return errors.NewField("Beneficiary", err)
	}
	// Serialize `BeneficiaryFee`:
	err = encoder.Encode(obj.BeneficiaryFee)
	if err != nil {
		return errors.NewField("BeneficiaryFee", err)
	}
	// Serialize `PendingAdmin` (optional):
	{
		if obj.PendingAdmin == nil {
			err = encoder.WriteOption(false)
			if err != nil {
				return errors.NewOption("PendingAdmin", fmt.Errorf("error while encoding optionality: %w", err))
			}
		} else {
			err = encoder.WriteOption(true)
			if err != nil {
				return errors.NewOption("PendingAdmin", fmt.Errorf("error while encoding optionality: %w", err))
			}
			err = encoder.Encode(obj.PendingAdmin)
			if err != nil {
				return errors.NewField("PendingAdmin", err)
			}
		}
	}
	return nil
}

func (obj Vault) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Vault: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Vault) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Deserialize `WithdrawAuthority`:
	err = decoder.Decode(&obj.WithdrawAuthority)
	if err != nil {
		return errors.NewField("WithdrawAuthority", err)
	}
	// Deserialize `WithdrawAuthorityBump`:
	err = decoder.Decode(&obj.WithdrawAuthorityBump)
	if err != nil {
		return errors.NewField("WithdrawAuthorityBump", err)
	}
	// Deserialize `AuthorityBump`:
	err = decoder.Decode(&obj.AuthorityBump)
	if err != nil {
		return errors.NewField("AuthorityBump", err)
	}
	// Deserialize `IsActive`:
	err = decoder.Decode(&obj.IsActive)
	if err != nil {
		return errors.NewField("IsActive", err)
	}
	// Deserialize `Beneficiary`:
	err = decoder.Decode(&obj.Beneficiary)
	if err != nil {
		return errors.NewField("Beneficiary", err)
	}
	// Deserialize `BeneficiaryFee`:
	err = decoder.Decode(&obj.BeneficiaryFee)
	if err != nil {
		return errors.NewField("BeneficiaryFee", err)
	}
	// Deserialize `PendingAdmin` (optional):
	{
		ok, err := decoder.ReadOption()
		if err != nil {
			return errors.NewOption("PendingAdmin", fmt.Errorf("error while reading optionality: %w", err))
		}
		if ok {
			err = decoder.Decode(&obj.PendingAdmin)
			if err != nil {
				return errors.NewField("PendingAdmin", err)
			}
		}
	}
	return nil
}

func (obj *Vault) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Vault: %w", err)
	}
	return nil
}

func UnmarshalVault(buf []byte) (*Vault, error) {
	obj := new(Vault)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
