// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the accounts defined in the IDL.

package whirlpool

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyAccount(accountData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek account discriminator: %w", err)
	}
	switch discriminator {
	case Account_AdaptiveFeeTier:
		value := new(AdaptiveFeeTier)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as AdaptiveFeeTier: %w", err)
		}
		return value, nil
	case Account_DynamicTickArray:
		value := new(DynamicTickArray)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as DynamicTickArray: %w", err)
		}
		return value, nil
	case Account_FeeTier:
		value := new(FeeTier)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as FeeTier: %w", err)
		}
		return value, nil
	case Account_LockConfig:
		value := new(LockConfig)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as LockConfig: %w", err)
		}
		return value, nil
	case Account_Oracle:
		value := new(Oracle)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Oracle: %w", err)
		}
		return value, nil
	case Account_Position:
		value := new(Position)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Position: %w", err)
		}
		return value, nil
	case Account_PositionBundle:
		value := new(PositionBundle)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as PositionBundle: %w", err)
		}
		return value, nil
	case Account_TickArray:
		value := new(TickArray)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as TickArray: %w", err)
		}
		return value, nil
	case Account_TokenBadge:
		value := new(TokenBadge)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as TokenBadge: %w", err)
		}
		return value, nil
	case Account_Whirlpool:
		value := new(Whirlpool)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Whirlpool: %w", err)
		}
		return value, nil
	case Account_WhirlpoolsConfig:
		value := new(WhirlpoolsConfig)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as WhirlpoolsConfig: %w", err)
		}
		return value, nil
	case Account_WhirlpoolsConfigExtension:
		value := new(WhirlpoolsConfigExtension)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as WhirlpoolsConfigExtension: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseAccount_AdaptiveFeeTier(accountData []byte) (*AdaptiveFeeTier, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_AdaptiveFeeTier {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_AdaptiveFeeTier, binary.FormatDiscriminator(discriminator))
	}
	acc := new(AdaptiveFeeTier)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type AdaptiveFeeTier: %w", err)
	}
	return acc, nil
}

func ParseAccount_DynamicTickArray(accountData []byte) (*DynamicTickArray, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_DynamicTickArray {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_DynamicTickArray, binary.FormatDiscriminator(discriminator))
	}
	acc := new(DynamicTickArray)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type DynamicTickArray: %w", err)
	}
	return acc, nil
}

func ParseAccount_FeeTier(accountData []byte) (*FeeTier, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_FeeTier {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_FeeTier, binary.FormatDiscriminator(discriminator))
	}
	acc := new(FeeTier)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type FeeTier: %w", err)
	}
	return acc, nil
}

func ParseAccount_LockConfig(accountData []byte) (*LockConfig, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_LockConfig {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_LockConfig, binary.FormatDiscriminator(discriminator))
	}
	acc := new(LockConfig)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type LockConfig: %w", err)
	}
	return acc, nil
}

func ParseAccount_Oracle(accountData []byte) (*Oracle, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Oracle {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Oracle, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Oracle)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Oracle: %w", err)
	}
	return acc, nil
}

func ParseAccount_Position(accountData []byte) (*Position, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Position {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Position, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Position)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Position: %w", err)
	}
	return acc, nil
}

func ParseAccount_PositionBundle(accountData []byte) (*PositionBundle, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_PositionBundle {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_PositionBundle, binary.FormatDiscriminator(discriminator))
	}
	acc := new(PositionBundle)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type PositionBundle: %w", err)
	}
	return acc, nil
}

func ParseAccount_TickArray(accountData []byte) (*TickArray, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_TickArray {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_TickArray, binary.FormatDiscriminator(discriminator))
	}
	acc := new(TickArray)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type TickArray: %w", err)
	}
	return acc, nil
}

func ParseAccount_TokenBadge(accountData []byte) (*TokenBadge, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_TokenBadge {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_TokenBadge, binary.FormatDiscriminator(discriminator))
	}
	acc := new(TokenBadge)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type TokenBadge: %w", err)
	}
	return acc, nil
}

func ParseAccount_Whirlpool(accountData []byte) (*Whirlpool, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Whirlpool {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Whirlpool, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Whirlpool)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Whirlpool: %w", err)
	}
	return acc, nil
}

func ParseAccount_WhirlpoolsConfig(accountData []byte) (*WhirlpoolsConfig, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_WhirlpoolsConfig {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_WhirlpoolsConfig, binary.FormatDiscriminator(discriminator))
	}
	acc := new(WhirlpoolsConfig)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type WhirlpoolsConfig: %w", err)
	}
	return acc, nil
}

func ParseAccount_WhirlpoolsConfigExtension(accountData []byte) (*WhirlpoolsConfigExtension, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_WhirlpoolsConfigExtension {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_WhirlpoolsConfigExtension, binary.FormatDiscriminator(discriminator))
	}
	acc := new(WhirlpoolsConfigExtension)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type WhirlpoolsConfigExtension: %w", err)
	}
	return acc, nil
}
