// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package vault

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ClaimRewards is the `claimRewards` instruction.
type ClaimRewards struct {

	// [0] = [] vault
	//
	// [1] = [] strategy
	//
	// [2] = [] tokenProgram
	//
	// [3] = [WRITE] tokenRewardAcc
	//
	// [4] = [SIGNER] operator
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewClaimRewardsInstructionBuilder creates a new `ClaimRewards` instruction builder.
func NewClaimRewardsInstructionBuilder() *ClaimRewards {
	nd := &ClaimRewards{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 5),
	}
	return nd
}

// SetVaultAccount sets the "vault" account.
func (inst *ClaimRewards) SetVaultAccount(vault ag_solanago.PublicKey) *ClaimRewards {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(vault)
	return inst
}

// GetVaultAccount gets the "vault" account.
func (inst *ClaimRewards) GetVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStrategyAccount sets the "strategy" account.
func (inst *ClaimRewards) SetStrategyAccount(strategy ag_solanago.PublicKey) *ClaimRewards {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(strategy)
	return inst
}

// GetStrategyAccount gets the "strategy" account.
func (inst *ClaimRewards) GetStrategyAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *ClaimRewards) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *ClaimRewards {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *ClaimRewards) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetTokenRewardAccAccount sets the "tokenRewardAcc" account.
func (inst *ClaimRewards) SetTokenRewardAccAccount(tokenRewardAcc ag_solanago.PublicKey) *ClaimRewards {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(tokenRewardAcc).WRITE()
	return inst
}

// GetTokenRewardAccAccount gets the "tokenRewardAcc" account.
func (inst *ClaimRewards) GetTokenRewardAccAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetOperatorAccount sets the "operator" account.
func (inst *ClaimRewards) SetOperatorAccount(operator ag_solanago.PublicKey) *ClaimRewards {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(operator).SIGNER()
	return inst
}

// GetOperatorAccount gets the "operator" account.
func (inst *ClaimRewards) GetOperatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

func (inst ClaimRewards) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ClaimRewards,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ClaimRewards) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ClaimRewards) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Vault is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Strategy is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.TokenRewardAcc is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Operator is not set")
		}
	}
	return nil
}

func (inst *ClaimRewards) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ClaimRewards")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=5]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("         vault", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("      strategy", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("  tokenProgram", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("tokenRewardAcc", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("      operator", inst.AccountMetaSlice.Get(4)))
					})
				})
		})
}

func (obj ClaimRewards) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *ClaimRewards) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewClaimRewardsInstruction declares a new ClaimRewards instruction with the provided parameters and accounts.
func NewClaimRewardsInstruction(
	// Accounts:
	vault ag_solanago.PublicKey,
	strategy ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	tokenRewardAcc ag_solanago.PublicKey,
	operator ag_solanago.PublicKey) *ClaimRewards {
	return NewClaimRewardsInstructionBuilder().
		SetVaultAccount(vault).
		SetStrategyAccount(strategy).
		SetTokenProgramAccount(tokenProgram).
		SetTokenRewardAccAccount(tokenRewardAcc).
		SetOperatorAccount(operator)
}
