// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package vault

import (
	"bytes"
	"fmt"
	ag_spew "github.com/davecgh/go-spew/spew"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_text "github.com/gagliardetto/solana-go/text"
	ag_treeout "github.com/gagliardetto/treeout"
)

var ProgramID ag_solanago.PublicKey

func SetProgramID(pubkey ag_solanago.PublicKey) {
	ProgramID = pubkey
	ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
}

const ProgramName = "Vault"

func init() {
	if !ProgramID.IsZero() {
		ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
	}
}

var (
	Instruction_Initialize = ag_binary.TypeID([8]byte{175, 175, 109, 31, 13, 152, 155, 237})

	Instruction_EnableVault = ag_binary.TypeID([8]byte{145, 82, 241, 156, 26, 154, 233, 211})

	Instruction_SetOperator = ag_binary.TypeID([8]byte{238, 153, 101, 169, 243, 131, 36, 1})

	Instruction_UpdateLockedProfitDegradation = ag_binary.TypeID([8]byte{103, 192, 9, 190, 43, 209, 235, 115})

	Instruction_GetUnlockedAmount = ag_binary.TypeID([8]byte{22, 184, 50, 213, 60, 168, 181, 227})

	Instruction_TransferAdmin = ag_binary.TypeID([8]byte{42, 242, 66, 106, 228, 10, 111, 156})

	Instruction_TransferFeeVault = ag_binary.TypeID([8]byte{24, 18, 129, 149, 149, 32, 45, 105})

	Instruction_InitializeStrategy = ag_binary.TypeID([8]byte{208, 119, 144, 145, 178, 57, 105, 252})

	Instruction_RemoveStrategy = ag_binary.TypeID([8]byte{185, 238, 33, 91, 134, 210, 97, 26})

	Instruction_RemoveStrategy2 = ag_binary.TypeID([8]byte{138, 104, 208, 148, 126, 35, 195, 14})

	Instruction_CollectDust = ag_binary.TypeID([8]byte{246, 149, 21, 82, 160, 74, 254, 240})

	Instruction_AddStrategy = ag_binary.TypeID([8]byte{64, 123, 127, 227, 192, 234, 198, 20})

	Instruction_DepositStrategy = ag_binary.TypeID([8]byte{246, 82, 57, 226, 131, 222, 253, 249})

	Instruction_WithdrawStrategy = ag_binary.TypeID([8]byte{31, 45, 162, 5, 193, 217, 134, 188})

	Instruction_ClaimRewards = ag_binary.TypeID([8]byte{4, 144, 132, 71, 116, 23, 151, 80})

	Instruction_Withdraw2 = ag_binary.TypeID([8]byte{80, 6, 111, 73, 174, 211, 66, 132})

	Instruction_Deposit = ag_binary.TypeID([8]byte{242, 35, 198, 137, 82, 225, 242, 182})

	Instruction_Withdraw = ag_binary.TypeID([8]byte{183, 18, 70, 156, 148, 109, 161, 34})

	Instruction_WithdrawDirectlyFromStrategy = ag_binary.TypeID([8]byte{201, 141, 146, 46, 173, 116, 198, 22})
)

// InstructionIDToName returns the name of the instruction given its ID.
func InstructionIDToName(id ag_binary.TypeID) string {
	switch id {
	case Instruction_Initialize:
		return "Initialize"
	case Instruction_EnableVault:
		return "EnableVault"
	case Instruction_SetOperator:
		return "SetOperator"
	case Instruction_UpdateLockedProfitDegradation:
		return "UpdateLockedProfitDegradation"
	case Instruction_GetUnlockedAmount:
		return "GetUnlockedAmount"
	case Instruction_TransferAdmin:
		return "TransferAdmin"
	case Instruction_TransferFeeVault:
		return "TransferFeeVault"
	case Instruction_InitializeStrategy:
		return "InitializeStrategy"
	case Instruction_RemoveStrategy:
		return "RemoveStrategy"
	case Instruction_RemoveStrategy2:
		return "RemoveStrategy2"
	case Instruction_CollectDust:
		return "CollectDust"
	case Instruction_AddStrategy:
		return "AddStrategy"
	case Instruction_DepositStrategy:
		return "DepositStrategy"
	case Instruction_WithdrawStrategy:
		return "WithdrawStrategy"
	case Instruction_ClaimRewards:
		return "ClaimRewards"
	case Instruction_Withdraw2:
		return "Withdraw2"
	case Instruction_Deposit:
		return "Deposit"
	case Instruction_Withdraw:
		return "Withdraw"
	case Instruction_WithdrawDirectlyFromStrategy:
		return "WithdrawDirectlyFromStrategy"
	default:
		return ""
	}
}

type Instruction struct {
	ag_binary.BaseVariant
}

func (inst *Instruction) EncodeToTree(parent ag_treeout.Branches) {
	if enToTree, ok := inst.Impl.(ag_text.EncodableToTree); ok {
		enToTree.EncodeToTree(parent)
	} else {
		parent.Child(ag_spew.Sdump(inst))
	}
}

var InstructionImplDef = ag_binary.NewVariantDefinition(
	ag_binary.AnchorTypeIDEncoding,
	[]ag_binary.VariantType{
		{
			"initialize", (*Initialize)(nil),
		},
		{
			"enable_vault", (*EnableVault)(nil),
		},
		{
			"set_operator", (*SetOperator)(nil),
		},
		{
			"update_locked_profit_degradation", (*UpdateLockedProfitDegradation)(nil),
		},
		{
			"get_unlocked_amount", (*GetUnlockedAmount)(nil),
		},
		{
			"transfer_admin", (*TransferAdmin)(nil),
		},
		{
			"transfer_fee_vault", (*TransferFeeVault)(nil),
		},
		{
			"initialize_strategy", (*InitializeStrategy)(nil),
		},
		{
			"remove_strategy", (*RemoveStrategy)(nil),
		},
		{
			"remove_strategy2", (*RemoveStrategy2)(nil),
		},
		{
			"collect_dust", (*CollectDust)(nil),
		},
		{
			"add_strategy", (*AddStrategy)(nil),
		},
		{
			"deposit_strategy", (*DepositStrategy)(nil),
		},
		{
			"withdraw_strategy", (*WithdrawStrategy)(nil),
		},
		{
			"claim_rewards", (*ClaimRewards)(nil),
		},
		{
			"withdraw2", (*Withdraw2)(nil),
		},
		{
			"deposit", (*Deposit)(nil),
		},
		{
			"withdraw", (*Withdraw)(nil),
		},
		{
			"withdraw_directly_from_strategy", (*WithdrawDirectlyFromStrategy)(nil),
		},
	},
)

func (inst *Instruction) ProgramID() ag_solanago.PublicKey {
	return ProgramID
}

func (inst *Instruction) Accounts() (out []*ag_solanago.AccountMeta) {
	return inst.Impl.(ag_solanago.AccountsGettable).GetAccounts()
}

func (inst *Instruction) Data() ([]byte, error) {
	buf := new(bytes.Buffer)
	if err := ag_binary.NewBorshEncoder(buf).Encode(inst); err != nil {
		return nil, fmt.Errorf("unable to encode instruction: %w", err)
	}
	return buf.Bytes(), nil
}

func (inst *Instruction) TextEncode(encoder *ag_text.Encoder, option *ag_text.Option) error {
	return encoder.Encode(inst.Impl, option)
}

func (inst *Instruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {
	return inst.BaseVariant.UnmarshalBinaryVariant(decoder, InstructionImplDef)
}

func (inst *Instruction) MarshalWithEncoder(encoder *ag_binary.Encoder) error {
	err := encoder.WriteBytes(inst.TypeID.Bytes(), false)
	if err != nil {
		return fmt.Errorf("unable to write variant type: %w", err)
	}
	return encoder.Encode(inst.Impl)
}

func registryDecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (interface{}, error) {
	inst, err := DecodeInstruction(accounts, data)
	if err != nil {
		return nil, err
	}
	return inst, nil
}

func DecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (*Instruction, error) {
	inst := new(Instruction)
	if err := ag_binary.NewBorshDecoder(data).Decode(inst); err != nil {
		return nil, fmt.Errorf("unable to decode instruction: %w", err)
	}
	if v, ok := inst.Impl.(ag_solanago.AccountsSettable); ok {
		err := v.SetAccounts(accounts)
		if err != nil {
			return nil, fmt.Errorf("unable to set accounts for instruction: %w", err)
		}
	}
	return inst, nil
}
