// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package vault

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdateLockedProfitDegradation is the `updateLockedProfitDegradation` instruction.
type UpdateLockedProfitDegradation struct {
	LockedProfitDegradation *uint64

	// [0] = [WRITE] vault
	//
	// [1] = [SIGNER] admin
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdateLockedProfitDegradationInstructionBuilder creates a new `UpdateLockedProfitDegradation` instruction builder.
func NewUpdateLockedProfitDegradationInstructionBuilder() *UpdateLockedProfitDegradation {
	nd := &UpdateLockedProfitDegradation{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetLockedProfitDegradation sets the "lockedProfitDegradation" parameter.
func (inst *UpdateLockedProfitDegradation) SetLockedProfitDegradation(lockedProfitDegradation uint64) *UpdateLockedProfitDegradation {
	inst.LockedProfitDegradation = &lockedProfitDegradation
	return inst
}

// SetVaultAccount sets the "vault" account.
func (inst *UpdateLockedProfitDegradation) SetVaultAccount(vault ag_solanago.PublicKey) *UpdateLockedProfitDegradation {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(vault).WRITE()
	return inst
}

// GetVaultAccount gets the "vault" account.
func (inst *UpdateLockedProfitDegradation) GetVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAdminAccount sets the "admin" account.
func (inst *UpdateLockedProfitDegradation) SetAdminAccount(admin ag_solanago.PublicKey) *UpdateLockedProfitDegradation {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *UpdateLockedProfitDegradation) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst UpdateLockedProfitDegradation) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdateLockedProfitDegradation,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateLockedProfitDegradation) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateLockedProfitDegradation) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.LockedProfitDegradation == nil {
			return errors.New("LockedProfitDegradation parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Vault is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Admin is not set")
		}
	}
	return nil
}

func (inst *UpdateLockedProfitDegradation) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateLockedProfitDegradation")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("LockedProfitDegradation", *inst.LockedProfitDegradation))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("vault", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("admin", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj UpdateLockedProfitDegradation) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `LockedProfitDegradation` param:
	err = encoder.Encode(obj.LockedProfitDegradation)
	if err != nil {
		return err
	}
	return nil
}
func (obj *UpdateLockedProfitDegradation) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `LockedProfitDegradation`:
	err = decoder.Decode(&obj.LockedProfitDegradation)
	if err != nil {
		return err
	}
	return nil
}

// NewUpdateLockedProfitDegradationInstruction declares a new UpdateLockedProfitDegradation instruction with the provided parameters and accounts.
func NewUpdateLockedProfitDegradationInstruction(
	// Parameters:
	lockedProfitDegradation uint64,
	// Accounts:
	vault ag_solanago.PublicKey,
	admin ag_solanago.PublicKey) *UpdateLockedProfitDegradation {
	return NewUpdateLockedProfitDegradationInstructionBuilder().
		SetLockedProfitDegradation(lockedProfitDegradation).
		SetVaultAccount(vault).
		SetAdminAccount(admin)
}
