// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the accounts defined in the IDL.

package pump

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyAccount(accountData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek account discriminator: %w", err)
	}
	switch discriminator {
	case Account_BondingCurve:
		value := new(BondingCurve)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as BondingCurve: %w", err)
		}
		return value, nil
	case Account_FeeConfig:
		value := new(FeeConfig)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as FeeConfig: %w", err)
		}
		return value, nil
	case Account_Global:
		value := new(Global)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Global: %w", err)
		}
		return value, nil
	case Account_GlobalVolumeAccumulator:
		value := new(GlobalVolumeAccumulator)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as GlobalVolumeAccumulator: %w", err)
		}
		return value, nil
	case Account_SharingConfig:
		value := new(SharingConfig)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as SharingConfig: %w", err)
		}
		return value, nil
	case Account_UserVolumeAccumulator:
		value := new(UserVolumeAccumulator)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as UserVolumeAccumulator: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseAccount_BondingCurve(accountData []byte) (*BondingCurve, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_BondingCurve {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_BondingCurve, binary.FormatDiscriminator(discriminator))
	}
	acc := new(BondingCurve)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type BondingCurve: %w", err)
	}
	return acc, nil
}

func ParseAccount_FeeConfig(accountData []byte) (*FeeConfig, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_FeeConfig {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_FeeConfig, binary.FormatDiscriminator(discriminator))
	}
	acc := new(FeeConfig)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type FeeConfig: %w", err)
	}
	return acc, nil
}

func ParseAccount_Global(accountData []byte) (*Global, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Global {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Global, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Global)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Global: %w", err)
	}
	return acc, nil
}

func ParseAccount_GlobalVolumeAccumulator(accountData []byte) (*GlobalVolumeAccumulator, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_GlobalVolumeAccumulator {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_GlobalVolumeAccumulator, binary.FormatDiscriminator(discriminator))
	}
	acc := new(GlobalVolumeAccumulator)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type GlobalVolumeAccumulator: %w", err)
	}
	return acc, nil
}

func ParseAccount_SharingConfig(accountData []byte) (*SharingConfig, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_SharingConfig {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_SharingConfig, binary.FormatDiscriminator(discriminator))
	}
	acc := new(SharingConfig)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type SharingConfig: %w", err)
	}
	return acc, nil
}

func ParseAccount_UserVolumeAccumulator(accountData []byte) (*UserVolumeAccumulator, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_UserVolumeAccumulator {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_UserVolumeAccumulator, binary.FormatDiscriminator(discriminator))
	}
	acc := new(UserVolumeAccumulator)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type UserVolumeAccumulator: %w", err)
	}
	return acc, nil
}
