// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package pump

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type AdminSetCreatorEvent struct {
	Timestamp                int64              `json:"timestamp"`
	AdminSetCreatorAuthority solanago.PublicKey `json:"adminSetCreatorAuthority"`
	Mint                     solanago.PublicKey `json:"mint"`
	BondingCurve             solanago.PublicKey `json:"bondingCurve"`
	OldCreator               solanago.PublicKey `json:"oldCreator"`
	NewCreator               solanago.PublicKey `json:"newCreator"`
}

func (obj AdminSetCreatorEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `AdminSetCreatorAuthority`:
	err = encoder.Encode(obj.AdminSetCreatorAuthority)
	if err != nil {
		return errors.NewField("AdminSetCreatorAuthority", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `BondingCurve`:
	err = encoder.Encode(obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Serialize `OldCreator`:
	err = encoder.Encode(obj.OldCreator)
	if err != nil {
		return errors.NewField("OldCreator", err)
	}
	// Serialize `NewCreator`:
	err = encoder.Encode(obj.NewCreator)
	if err != nil {
		return errors.NewField("NewCreator", err)
	}
	return nil
}

func (obj AdminSetCreatorEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AdminSetCreatorEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AdminSetCreatorEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `AdminSetCreatorAuthority`:
	err = decoder.Decode(&obj.AdminSetCreatorAuthority)
	if err != nil {
		return errors.NewField("AdminSetCreatorAuthority", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `BondingCurve`:
	err = decoder.Decode(&obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Deserialize `OldCreator`:
	err = decoder.Decode(&obj.OldCreator)
	if err != nil {
		return errors.NewField("OldCreator", err)
	}
	// Deserialize `NewCreator`:
	err = decoder.Decode(&obj.NewCreator)
	if err != nil {
		return errors.NewField("NewCreator", err)
	}
	return nil
}

func (obj *AdminSetCreatorEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AdminSetCreatorEvent: %w", err)
	}
	return nil
}

func UnmarshalAdminSetCreatorEvent(buf []byte) (*AdminSetCreatorEvent, error) {
	obj := new(AdminSetCreatorEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type AdminSetIdlAuthorityEvent struct {
	IdlAuthority solanago.PublicKey `json:"idlAuthority"`
}

func (obj AdminSetIdlAuthorityEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `IdlAuthority`:
	err = encoder.Encode(obj.IdlAuthority)
	if err != nil {
		return errors.NewField("IdlAuthority", err)
	}
	return nil
}

func (obj AdminSetIdlAuthorityEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AdminSetIdlAuthorityEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AdminSetIdlAuthorityEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `IdlAuthority`:
	err = decoder.Decode(&obj.IdlAuthority)
	if err != nil {
		return errors.NewField("IdlAuthority", err)
	}
	return nil
}

func (obj *AdminSetIdlAuthorityEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AdminSetIdlAuthorityEvent: %w", err)
	}
	return nil
}

func UnmarshalAdminSetIdlAuthorityEvent(buf []byte) (*AdminSetIdlAuthorityEvent, error) {
	obj := new(AdminSetIdlAuthorityEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type AdminUpdateTokenIncentivesEvent struct {
	StartTime         int64              `json:"startTime"`
	EndTime           int64              `json:"endTime"`
	DayNumber         uint64             `json:"dayNumber"`
	TokenSupplyPerDay uint64             `json:"tokenSupplyPerDay"`
	Mint              solanago.PublicKey `json:"mint"`
	SecondsInADay     int64              `json:"secondsInADay"`
	Timestamp         int64              `json:"timestamp"`
}

func (obj AdminUpdateTokenIncentivesEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `StartTime`:
	err = encoder.Encode(obj.StartTime)
	if err != nil {
		return errors.NewField("StartTime", err)
	}
	// Serialize `EndTime`:
	err = encoder.Encode(obj.EndTime)
	if err != nil {
		return errors.NewField("EndTime", err)
	}
	// Serialize `DayNumber`:
	err = encoder.Encode(obj.DayNumber)
	if err != nil {
		return errors.NewField("DayNumber", err)
	}
	// Serialize `TokenSupplyPerDay`:
	err = encoder.Encode(obj.TokenSupplyPerDay)
	if err != nil {
		return errors.NewField("TokenSupplyPerDay", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `SecondsInADay`:
	err = encoder.Encode(obj.SecondsInADay)
	if err != nil {
		return errors.NewField("SecondsInADay", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj AdminUpdateTokenIncentivesEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AdminUpdateTokenIncentivesEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AdminUpdateTokenIncentivesEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `StartTime`:
	err = decoder.Decode(&obj.StartTime)
	if err != nil {
		return errors.NewField("StartTime", err)
	}
	// Deserialize `EndTime`:
	err = decoder.Decode(&obj.EndTime)
	if err != nil {
		return errors.NewField("EndTime", err)
	}
	// Deserialize `DayNumber`:
	err = decoder.Decode(&obj.DayNumber)
	if err != nil {
		return errors.NewField("DayNumber", err)
	}
	// Deserialize `TokenSupplyPerDay`:
	err = decoder.Decode(&obj.TokenSupplyPerDay)
	if err != nil {
		return errors.NewField("TokenSupplyPerDay", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `SecondsInADay`:
	err = decoder.Decode(&obj.SecondsInADay)
	if err != nil {
		return errors.NewField("SecondsInADay", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj *AdminUpdateTokenIncentivesEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AdminUpdateTokenIncentivesEvent: %w", err)
	}
	return nil
}

func UnmarshalAdminUpdateTokenIncentivesEvent(buf []byte) (*AdminUpdateTokenIncentivesEvent, error) {
	obj := new(AdminUpdateTokenIncentivesEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type BondingCurve struct {
	VirtualTokenReserves uint64             `json:"virtualTokenReserves"`
	VirtualSolReserves   uint64             `json:"virtualSolReserves"`
	RealTokenReserves    uint64             `json:"realTokenReserves"`
	RealSolReserves      uint64             `json:"realSolReserves"`
	TokenTotalSupply     uint64             `json:"tokenTotalSupply"`
	Complete             bool               `json:"complete"`
	Creator              solanago.PublicKey `json:"creator"`
	IsMayhemMode         bool               `json:"isMayhemMode"`
}

func (obj BondingCurve) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `VirtualTokenReserves`:
	err = encoder.Encode(obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Serialize `VirtualSolReserves`:
	err = encoder.Encode(obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Serialize `RealTokenReserves`:
	err = encoder.Encode(obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	// Serialize `RealSolReserves`:
	err = encoder.Encode(obj.RealSolReserves)
	if err != nil {
		return errors.NewField("RealSolReserves", err)
	}
	// Serialize `TokenTotalSupply`:
	err = encoder.Encode(obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	// Serialize `Complete`:
	err = encoder.Encode(obj.Complete)
	if err != nil {
		return errors.NewField("Complete", err)
	}
	// Serialize `Creator`:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Serialize `IsMayhemMode`:
	err = encoder.Encode(obj.IsMayhemMode)
	if err != nil {
		return errors.NewField("IsMayhemMode", err)
	}
	return nil
}

func (obj BondingCurve) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding BondingCurve: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *BondingCurve) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `VirtualTokenReserves`:
	err = decoder.Decode(&obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Deserialize `VirtualSolReserves`:
	err = decoder.Decode(&obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Deserialize `RealTokenReserves`:
	err = decoder.Decode(&obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	// Deserialize `RealSolReserves`:
	err = decoder.Decode(&obj.RealSolReserves)
	if err != nil {
		return errors.NewField("RealSolReserves", err)
	}
	// Deserialize `TokenTotalSupply`:
	err = decoder.Decode(&obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	// Deserialize `Complete`:
	err = decoder.Decode(&obj.Complete)
	if err != nil {
		return errors.NewField("Complete", err)
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Deserialize `IsMayhemMode`:
	err = decoder.Decode(&obj.IsMayhemMode)
	if err != nil {
		return errors.NewField("IsMayhemMode", err)
	}
	return nil
}

func (obj *BondingCurve) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling BondingCurve: %w", err)
	}
	return nil
}

func UnmarshalBondingCurve(buf []byte) (*BondingCurve, error) {
	obj := new(BondingCurve)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ClaimTokenIncentivesEvent struct {
	User               solanago.PublicKey `json:"user"`
	Mint               solanago.PublicKey `json:"mint"`
	Amount             uint64             `json:"amount"`
	Timestamp          int64              `json:"timestamp"`
	TotalClaimedTokens uint64             `json:"totalClaimedTokens"`
	CurrentSolVolume   uint64             `json:"currentSolVolume"`
}

func (obj ClaimTokenIncentivesEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `Amount`:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `TotalClaimedTokens`:
	err = encoder.Encode(obj.TotalClaimedTokens)
	if err != nil {
		return errors.NewField("TotalClaimedTokens", err)
	}
	// Serialize `CurrentSolVolume`:
	err = encoder.Encode(obj.CurrentSolVolume)
	if err != nil {
		return errors.NewField("CurrentSolVolume", err)
	}
	return nil
}

func (obj ClaimTokenIncentivesEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ClaimTokenIncentivesEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ClaimTokenIncentivesEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `TotalClaimedTokens`:
	err = decoder.Decode(&obj.TotalClaimedTokens)
	if err != nil {
		return errors.NewField("TotalClaimedTokens", err)
	}
	// Deserialize `CurrentSolVolume`:
	err = decoder.Decode(&obj.CurrentSolVolume)
	if err != nil {
		return errors.NewField("CurrentSolVolume", err)
	}
	return nil
}

func (obj *ClaimTokenIncentivesEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ClaimTokenIncentivesEvent: %w", err)
	}
	return nil
}

func UnmarshalClaimTokenIncentivesEvent(buf []byte) (*ClaimTokenIncentivesEvent, error) {
	obj := new(ClaimTokenIncentivesEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type CloseUserVolumeAccumulatorEvent struct {
	User                 solanago.PublicKey `json:"user"`
	Timestamp            int64              `json:"timestamp"`
	TotalUnclaimedTokens uint64             `json:"totalUnclaimedTokens"`
	TotalClaimedTokens   uint64             `json:"totalClaimedTokens"`
	CurrentSolVolume     uint64             `json:"currentSolVolume"`
	LastUpdateTimestamp  int64              `json:"lastUpdateTimestamp"`
}

func (obj CloseUserVolumeAccumulatorEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `TotalUnclaimedTokens`:
	err = encoder.Encode(obj.TotalUnclaimedTokens)
	if err != nil {
		return errors.NewField("TotalUnclaimedTokens", err)
	}
	// Serialize `TotalClaimedTokens`:
	err = encoder.Encode(obj.TotalClaimedTokens)
	if err != nil {
		return errors.NewField("TotalClaimedTokens", err)
	}
	// Serialize `CurrentSolVolume`:
	err = encoder.Encode(obj.CurrentSolVolume)
	if err != nil {
		return errors.NewField("CurrentSolVolume", err)
	}
	// Serialize `LastUpdateTimestamp`:
	err = encoder.Encode(obj.LastUpdateTimestamp)
	if err != nil {
		return errors.NewField("LastUpdateTimestamp", err)
	}
	return nil
}

func (obj CloseUserVolumeAccumulatorEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CloseUserVolumeAccumulatorEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CloseUserVolumeAccumulatorEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `TotalUnclaimedTokens`:
	err = decoder.Decode(&obj.TotalUnclaimedTokens)
	if err != nil {
		return errors.NewField("TotalUnclaimedTokens", err)
	}
	// Deserialize `TotalClaimedTokens`:
	err = decoder.Decode(&obj.TotalClaimedTokens)
	if err != nil {
		return errors.NewField("TotalClaimedTokens", err)
	}
	// Deserialize `CurrentSolVolume`:
	err = decoder.Decode(&obj.CurrentSolVolume)
	if err != nil {
		return errors.NewField("CurrentSolVolume", err)
	}
	// Deserialize `LastUpdateTimestamp`:
	err = decoder.Decode(&obj.LastUpdateTimestamp)
	if err != nil {
		return errors.NewField("LastUpdateTimestamp", err)
	}
	return nil
}

func (obj *CloseUserVolumeAccumulatorEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CloseUserVolumeAccumulatorEvent: %w", err)
	}
	return nil
}

func UnmarshalCloseUserVolumeAccumulatorEvent(buf []byte) (*CloseUserVolumeAccumulatorEvent, error) {
	obj := new(CloseUserVolumeAccumulatorEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type CollectCreatorFeeEvent struct {
	Timestamp  int64              `json:"timestamp"`
	Creator    solanago.PublicKey `json:"creator"`
	CreatorFee uint64             `json:"creatorFee"`
}

func (obj CollectCreatorFeeEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Creator`:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Serialize `CreatorFee`:
	err = encoder.Encode(obj.CreatorFee)
	if err != nil {
		return errors.NewField("CreatorFee", err)
	}
	return nil
}

func (obj CollectCreatorFeeEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CollectCreatorFeeEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CollectCreatorFeeEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Deserialize `CreatorFee`:
	err = decoder.Decode(&obj.CreatorFee)
	if err != nil {
		return errors.NewField("CreatorFee", err)
	}
	return nil
}

func (obj *CollectCreatorFeeEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CollectCreatorFeeEvent: %w", err)
	}
	return nil
}

func UnmarshalCollectCreatorFeeEvent(buf []byte) (*CollectCreatorFeeEvent, error) {
	obj := new(CollectCreatorFeeEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type CompleteEvent struct {
	User         solanago.PublicKey `json:"user"`
	Mint         solanago.PublicKey `json:"mint"`
	BondingCurve solanago.PublicKey `json:"bondingCurve"`
	Timestamp    int64              `json:"timestamp"`
}

func (obj CompleteEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `BondingCurve`:
	err = encoder.Encode(obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj CompleteEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CompleteEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CompleteEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `BondingCurve`:
	err = decoder.Decode(&obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj *CompleteEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CompleteEvent: %w", err)
	}
	return nil
}

func UnmarshalCompleteEvent(buf []byte) (*CompleteEvent, error) {
	obj := new(CompleteEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type CompletePumpAmmMigrationEvent struct {
	User             solanago.PublicKey `json:"user"`
	Mint             solanago.PublicKey `json:"mint"`
	MintAmount       uint64             `json:"mintAmount"`
	SolAmount        uint64             `json:"solAmount"`
	PoolMigrationFee uint64             `json:"poolMigrationFee"`
	BondingCurve     solanago.PublicKey `json:"bondingCurve"`
	Timestamp        int64              `json:"timestamp"`
	Pool             solanago.PublicKey `json:"pool"`
}

func (obj CompletePumpAmmMigrationEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `MintAmount`:
	err = encoder.Encode(obj.MintAmount)
	if err != nil {
		return errors.NewField("MintAmount", err)
	}
	// Serialize `SolAmount`:
	err = encoder.Encode(obj.SolAmount)
	if err != nil {
		return errors.NewField("SolAmount", err)
	}
	// Serialize `PoolMigrationFee`:
	err = encoder.Encode(obj.PoolMigrationFee)
	if err != nil {
		return errors.NewField("PoolMigrationFee", err)
	}
	// Serialize `BondingCurve`:
	err = encoder.Encode(obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	return nil
}

func (obj CompletePumpAmmMigrationEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CompletePumpAmmMigrationEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CompletePumpAmmMigrationEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `MintAmount`:
	err = decoder.Decode(&obj.MintAmount)
	if err != nil {
		return errors.NewField("MintAmount", err)
	}
	// Deserialize `SolAmount`:
	err = decoder.Decode(&obj.SolAmount)
	if err != nil {
		return errors.NewField("SolAmount", err)
	}
	// Deserialize `PoolMigrationFee`:
	err = decoder.Decode(&obj.PoolMigrationFee)
	if err != nil {
		return errors.NewField("PoolMigrationFee", err)
	}
	// Deserialize `BondingCurve`:
	err = decoder.Decode(&obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	return nil
}

func (obj *CompletePumpAmmMigrationEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CompletePumpAmmMigrationEvent: %w", err)
	}
	return nil
}

func UnmarshalCompletePumpAmmMigrationEvent(buf []byte) (*CompletePumpAmmMigrationEvent, error) {
	obj := new(CompletePumpAmmMigrationEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ConfigStatus binary.BorshEnum

const (
	ConfigStatus_Paused ConfigStatus = iota
	ConfigStatus_Active
)

func (value ConfigStatus) String() string {
	switch value {
	case ConfigStatus_Paused:
		return "Paused"
	case ConfigStatus_Active:
		return "Active"
	default:
		return ""
	}
}

type CreateEvent struct {
	Name                 string             `json:"name"`
	Symbol               string             `json:"symbol"`
	Uri                  string             `json:"uri"`
	Mint                 solanago.PublicKey `json:"mint"`
	BondingCurve         solanago.PublicKey `json:"bondingCurve"`
	User                 solanago.PublicKey `json:"user"`
	Creator              solanago.PublicKey `json:"creator"`
	Timestamp            int64              `json:"timestamp"`
	VirtualTokenReserves uint64             `json:"virtualTokenReserves"`
	VirtualSolReserves   uint64             `json:"virtualSolReserves"`
	RealTokenReserves    uint64             `json:"realTokenReserves"`
	TokenTotalSupply     uint64             `json:"tokenTotalSupply"`
}

func (obj CreateEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Name`:
	err = encoder.Encode(obj.Name)
	if err != nil {
		return errors.NewField("Name", err)
	}
	// Serialize `Symbol`:
	err = encoder.Encode(obj.Symbol)
	if err != nil {
		return errors.NewField("Symbol", err)
	}
	// Serialize `Uri`:
	err = encoder.Encode(obj.Uri)
	if err != nil {
		return errors.NewField("Uri", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `BondingCurve`:
	err = encoder.Encode(obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `Creator`:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `VirtualTokenReserves`:
	err = encoder.Encode(obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Serialize `VirtualSolReserves`:
	err = encoder.Encode(obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Serialize `RealTokenReserves`:
	err = encoder.Encode(obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	// Serialize `TokenTotalSupply`:
	err = encoder.Encode(obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	return nil
}

func (obj CreateEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CreateEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CreateEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Name`:
	err = decoder.Decode(&obj.Name)
	if err != nil {
		return errors.NewField("Name", err)
	}
	// Deserialize `Symbol`:
	err = decoder.Decode(&obj.Symbol)
	if err != nil {
		return errors.NewField("Symbol", err)
	}
	// Deserialize `Uri`:
	err = decoder.Decode(&obj.Uri)
	if err != nil {
		return errors.NewField("Uri", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `BondingCurve`:
	err = decoder.Decode(&obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `VirtualTokenReserves`:
	err = decoder.Decode(&obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Deserialize `VirtualSolReserves`:
	err = decoder.Decode(&obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Deserialize `RealTokenReserves`:
	err = decoder.Decode(&obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	// Deserialize `TokenTotalSupply`:
	err = decoder.Decode(&obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	return nil
}

func (obj *CreateEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CreateEvent: %w", err)
	}
	return nil
}

func UnmarshalCreateEvent(buf []byte) (*CreateEvent, error) {
	obj := new(CreateEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type DistributeCreatorFeesEvent struct {
	Timestamp     int64              `json:"timestamp"`
	Mint          solanago.PublicKey `json:"mint"`
	BondingCurve  solanago.PublicKey `json:"bondingCurve"`
	SharingConfig solanago.PublicKey `json:"sharingConfig"`
	Admin         solanago.PublicKey `json:"admin"`
	Shareholders  []Shareholder      `json:"shareholders"`
	Distributed   uint64             `json:"distributed"`
}

func (obj DistributeCreatorFeesEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `BondingCurve`:
	err = encoder.Encode(obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Serialize `SharingConfig`:
	err = encoder.Encode(obj.SharingConfig)
	if err != nil {
		return errors.NewField("SharingConfig", err)
	}
	// Serialize `Admin`:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Serialize `Shareholders`:
	err = encoder.Encode(obj.Shareholders)
	if err != nil {
		return errors.NewField("Shareholders", err)
	}
	// Serialize `Distributed`:
	err = encoder.Encode(obj.Distributed)
	if err != nil {
		return errors.NewField("Distributed", err)
	}
	return nil
}

func (obj DistributeCreatorFeesEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding DistributeCreatorFeesEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *DistributeCreatorFeesEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `BondingCurve`:
	err = decoder.Decode(&obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Deserialize `SharingConfig`:
	err = decoder.Decode(&obj.SharingConfig)
	if err != nil {
		return errors.NewField("SharingConfig", err)
	}
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Deserialize `Shareholders`:
	err = decoder.Decode(&obj.Shareholders)
	if err != nil {
		return errors.NewField("Shareholders", err)
	}
	// Deserialize `Distributed`:
	err = decoder.Decode(&obj.Distributed)
	if err != nil {
		return errors.NewField("Distributed", err)
	}
	return nil
}

func (obj *DistributeCreatorFeesEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling DistributeCreatorFeesEvent: %w", err)
	}
	return nil
}

func UnmarshalDistributeCreatorFeesEvent(buf []byte) (*DistributeCreatorFeesEvent, error) {
	obj := new(DistributeCreatorFeesEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ExtendAccountEvent struct {
	Account     solanago.PublicKey `json:"account"`
	User        solanago.PublicKey `json:"user"`
	CurrentSize uint64             `json:"currentSize"`
	NewSize     uint64             `json:"newSize"`
	Timestamp   int64              `json:"timestamp"`
}

func (obj ExtendAccountEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Account`:
	err = encoder.Encode(obj.Account)
	if err != nil {
		return errors.NewField("Account", err)
	}
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `CurrentSize`:
	err = encoder.Encode(obj.CurrentSize)
	if err != nil {
		return errors.NewField("CurrentSize", err)
	}
	// Serialize `NewSize`:
	err = encoder.Encode(obj.NewSize)
	if err != nil {
		return errors.NewField("NewSize", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj ExtendAccountEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ExtendAccountEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ExtendAccountEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Account`:
	err = decoder.Decode(&obj.Account)
	if err != nil {
		return errors.NewField("Account", err)
	}
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `CurrentSize`:
	err = decoder.Decode(&obj.CurrentSize)
	if err != nil {
		return errors.NewField("CurrentSize", err)
	}
	// Deserialize `NewSize`:
	err = decoder.Decode(&obj.NewSize)
	if err != nil {
		return errors.NewField("NewSize", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj *ExtendAccountEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ExtendAccountEvent: %w", err)
	}
	return nil
}

func UnmarshalExtendAccountEvent(buf []byte) (*ExtendAccountEvent, error) {
	obj := new(ExtendAccountEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type FeeConfig struct {
	Bump     uint8              `json:"bump"`
	Admin    solanago.PublicKey `json:"admin"`
	FlatFees Fees               `json:"flatFees"`
	FeeTiers []FeeTier          `json:"feeTiers"`
}

func (obj FeeConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `Admin`:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Serialize `FlatFees`:
	err = encoder.Encode(obj.FlatFees)
	if err != nil {
		return errors.NewField("FlatFees", err)
	}
	// Serialize `FeeTiers`:
	err = encoder.Encode(obj.FeeTiers)
	if err != nil {
		return errors.NewField("FeeTiers", err)
	}
	return nil
}

func (obj FeeConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding FeeConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *FeeConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Deserialize `FlatFees`:
	err = decoder.Decode(&obj.FlatFees)
	if err != nil {
		return errors.NewField("FlatFees", err)
	}
	// Deserialize `FeeTiers`:
	err = decoder.Decode(&obj.FeeTiers)
	if err != nil {
		return errors.NewField("FeeTiers", err)
	}
	return nil
}

func (obj *FeeConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling FeeConfig: %w", err)
	}
	return nil
}

func UnmarshalFeeConfig(buf []byte) (*FeeConfig, error) {
	obj := new(FeeConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type FeeTier struct {
	MarketCapLamportsThreshold binary.Uint128 `json:"marketCapLamportsThreshold"`
	Fees                       Fees           `json:"fees"`
}

func (obj FeeTier) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `MarketCapLamportsThreshold`:
	err = encoder.Encode(obj.MarketCapLamportsThreshold)
	if err != nil {
		return errors.NewField("MarketCapLamportsThreshold", err)
	}
	// Serialize `Fees`:
	err = encoder.Encode(obj.Fees)
	if err != nil {
		return errors.NewField("Fees", err)
	}
	return nil
}

func (obj FeeTier) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding FeeTier: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *FeeTier) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `MarketCapLamportsThreshold`:
	err = decoder.Decode(&obj.MarketCapLamportsThreshold)
	if err != nil {
		return errors.NewField("MarketCapLamportsThreshold", err)
	}
	// Deserialize `Fees`:
	err = decoder.Decode(&obj.Fees)
	if err != nil {
		return errors.NewField("Fees", err)
	}
	return nil
}

func (obj *FeeTier) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling FeeTier: %w", err)
	}
	return nil
}

func UnmarshalFeeTier(buf []byte) (*FeeTier, error) {
	obj := new(FeeTier)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Fees struct {
	LpFeeBps       uint64 `json:"lpFeeBps"`
	ProtocolFeeBps uint64 `json:"protocolFeeBps"`
	CreatorFeeBps  uint64 `json:"creatorFeeBps"`
}

func (obj Fees) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `LpFeeBps`:
	err = encoder.Encode(obj.LpFeeBps)
	if err != nil {
		return errors.NewField("LpFeeBps", err)
	}
	// Serialize `ProtocolFeeBps`:
	err = encoder.Encode(obj.ProtocolFeeBps)
	if err != nil {
		return errors.NewField("ProtocolFeeBps", err)
	}
	// Serialize `CreatorFeeBps`:
	err = encoder.Encode(obj.CreatorFeeBps)
	if err != nil {
		return errors.NewField("CreatorFeeBps", err)
	}
	return nil
}

func (obj Fees) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Fees: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Fees) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `LpFeeBps`:
	err = decoder.Decode(&obj.LpFeeBps)
	if err != nil {
		return errors.NewField("LpFeeBps", err)
	}
	// Deserialize `ProtocolFeeBps`:
	err = decoder.Decode(&obj.ProtocolFeeBps)
	if err != nil {
		return errors.NewField("ProtocolFeeBps", err)
	}
	// Deserialize `CreatorFeeBps`:
	err = decoder.Decode(&obj.CreatorFeeBps)
	if err != nil {
		return errors.NewField("CreatorFeeBps", err)
	}
	return nil
}

func (obj *Fees) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Fees: %w", err)
	}
	return nil
}

func UnmarshalFees(buf []byte) (*Fees, error) {
	obj := new(Fees)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Global struct {
	// Unused
	Initialized                 bool               `json:"initialized"`
	Authority                   solanago.PublicKey `json:"authority"`
	FeeRecipient                solanago.PublicKey `json:"feeRecipient"`
	InitialVirtualTokenReserves uint64             `json:"initialVirtualTokenReserves"`
	InitialVirtualSolReserves   uint64             `json:"initialVirtualSolReserves"`
	InitialRealTokenReserves    uint64             `json:"initialRealTokenReserves"`
	TokenTotalSupply            uint64             `json:"tokenTotalSupply"`
	FeeBasisPoints              uint64             `json:"feeBasisPoints"`
	WithdrawAuthority           solanago.PublicKey `json:"withdrawAuthority"`

	// Unused
	EnableMigrate            bool                  `json:"enableMigrate"`
	PoolMigrationFee         uint64                `json:"poolMigrationFee"`
	CreatorFeeBasisPoints    uint64                `json:"creatorFeeBasisPoints"`
	FeeRecipients            [7]solanago.PublicKey `json:"feeRecipients"`
	SetCreatorAuthority      solanago.PublicKey    `json:"setCreatorAuthority"`
	AdminSetCreatorAuthority solanago.PublicKey    `json:"adminSetCreatorAuthority"`
	CreateV2Enabled          bool                  `json:"createV2Enabled"`
	WhitelistPda             solanago.PublicKey    `json:"whitelistPda"`
	ReservedFeeRecipient     solanago.PublicKey    `json:"reservedFeeRecipient"`
	MayhemModeEnabled        bool                  `json:"mayhemModeEnabled"`
	ReservedFeeRecipients    [7]solanago.PublicKey `json:"reservedFeeRecipients"`
}

func (obj Global) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Initialized`:
	err = encoder.Encode(obj.Initialized)
	if err != nil {
		return errors.NewField("Initialized", err)
	}
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `FeeRecipient`:
	err = encoder.Encode(obj.FeeRecipient)
	if err != nil {
		return errors.NewField("FeeRecipient", err)
	}
	// Serialize `InitialVirtualTokenReserves`:
	err = encoder.Encode(obj.InitialVirtualTokenReserves)
	if err != nil {
		return errors.NewField("InitialVirtualTokenReserves", err)
	}
	// Serialize `InitialVirtualSolReserves`:
	err = encoder.Encode(obj.InitialVirtualSolReserves)
	if err != nil {
		return errors.NewField("InitialVirtualSolReserves", err)
	}
	// Serialize `InitialRealTokenReserves`:
	err = encoder.Encode(obj.InitialRealTokenReserves)
	if err != nil {
		return errors.NewField("InitialRealTokenReserves", err)
	}
	// Serialize `TokenTotalSupply`:
	err = encoder.Encode(obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	// Serialize `FeeBasisPoints`:
	err = encoder.Encode(obj.FeeBasisPoints)
	if err != nil {
		return errors.NewField("FeeBasisPoints", err)
	}
	// Serialize `WithdrawAuthority`:
	err = encoder.Encode(obj.WithdrawAuthority)
	if err != nil {
		return errors.NewField("WithdrawAuthority", err)
	}
	// Serialize `EnableMigrate`:
	err = encoder.Encode(obj.EnableMigrate)
	if err != nil {
		return errors.NewField("EnableMigrate", err)
	}
	// Serialize `PoolMigrationFee`:
	err = encoder.Encode(obj.PoolMigrationFee)
	if err != nil {
		return errors.NewField("PoolMigrationFee", err)
	}
	// Serialize `CreatorFeeBasisPoints`:
	err = encoder.Encode(obj.CreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CreatorFeeBasisPoints", err)
	}
	// Serialize `FeeRecipients`:
	err = encoder.Encode(obj.FeeRecipients)
	if err != nil {
		return errors.NewField("FeeRecipients", err)
	}
	// Serialize `SetCreatorAuthority`:
	err = encoder.Encode(obj.SetCreatorAuthority)
	if err != nil {
		return errors.NewField("SetCreatorAuthority", err)
	}
	// Serialize `AdminSetCreatorAuthority`:
	err = encoder.Encode(obj.AdminSetCreatorAuthority)
	if err != nil {
		return errors.NewField("AdminSetCreatorAuthority", err)
	}
	// Serialize `CreateV2Enabled`:
	err = encoder.Encode(obj.CreateV2Enabled)
	if err != nil {
		return errors.NewField("CreateV2Enabled", err)
	}
	// Serialize `WhitelistPda`:
	err = encoder.Encode(obj.WhitelistPda)
	if err != nil {
		return errors.NewField("WhitelistPda", err)
	}
	// Serialize `ReservedFeeRecipient`:
	err = encoder.Encode(obj.ReservedFeeRecipient)
	if err != nil {
		return errors.NewField("ReservedFeeRecipient", err)
	}
	// Serialize `MayhemModeEnabled`:
	err = encoder.Encode(obj.MayhemModeEnabled)
	if err != nil {
		return errors.NewField("MayhemModeEnabled", err)
	}
	// Serialize `ReservedFeeRecipients`:
	err = encoder.Encode(obj.ReservedFeeRecipients)
	if err != nil {
		return errors.NewField("ReservedFeeRecipients", err)
	}
	return nil
}

func (obj Global) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Global: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Global) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Initialized`:
	err = decoder.Decode(&obj.Initialized)
	if err != nil {
		return errors.NewField("Initialized", err)
	}
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `FeeRecipient`:
	err = decoder.Decode(&obj.FeeRecipient)
	if err != nil {
		return errors.NewField("FeeRecipient", err)
	}
	// Deserialize `InitialVirtualTokenReserves`:
	err = decoder.Decode(&obj.InitialVirtualTokenReserves)
	if err != nil {
		return errors.NewField("InitialVirtualTokenReserves", err)
	}
	// Deserialize `InitialVirtualSolReserves`:
	err = decoder.Decode(&obj.InitialVirtualSolReserves)
	if err != nil {
		return errors.NewField("InitialVirtualSolReserves", err)
	}
	// Deserialize `InitialRealTokenReserves`:
	err = decoder.Decode(&obj.InitialRealTokenReserves)
	if err != nil {
		return errors.NewField("InitialRealTokenReserves", err)
	}
	// Deserialize `TokenTotalSupply`:
	err = decoder.Decode(&obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	// Deserialize `FeeBasisPoints`:
	err = decoder.Decode(&obj.FeeBasisPoints)
	if err != nil {
		return errors.NewField("FeeBasisPoints", err)
	}
	// Deserialize `WithdrawAuthority`:
	err = decoder.Decode(&obj.WithdrawAuthority)
	if err != nil {
		return errors.NewField("WithdrawAuthority", err)
	}
	// Deserialize `EnableMigrate`:
	err = decoder.Decode(&obj.EnableMigrate)
	if err != nil {
		return errors.NewField("EnableMigrate", err)
	}
	// Deserialize `PoolMigrationFee`:
	err = decoder.Decode(&obj.PoolMigrationFee)
	if err != nil {
		return errors.NewField("PoolMigrationFee", err)
	}
	// Deserialize `CreatorFeeBasisPoints`:
	err = decoder.Decode(&obj.CreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CreatorFeeBasisPoints", err)
	}
	// Deserialize `FeeRecipients`:
	err = decoder.Decode(&obj.FeeRecipients)
	if err != nil {
		return errors.NewField("FeeRecipients", err)
	}
	// Deserialize `SetCreatorAuthority`:
	err = decoder.Decode(&obj.SetCreatorAuthority)
	if err != nil {
		return errors.NewField("SetCreatorAuthority", err)
	}
	// Deserialize `AdminSetCreatorAuthority`:
	err = decoder.Decode(&obj.AdminSetCreatorAuthority)
	if err != nil {
		return errors.NewField("AdminSetCreatorAuthority", err)
	}
	// Deserialize `CreateV2Enabled`:
	err = decoder.Decode(&obj.CreateV2Enabled)
	if err != nil {
		return errors.NewField("CreateV2Enabled", err)
	}
	// Deserialize `WhitelistPda`:
	err = decoder.Decode(&obj.WhitelistPda)
	if err != nil {
		return errors.NewField("WhitelistPda", err)
	}
	// Deserialize `ReservedFeeRecipient`:
	err = decoder.Decode(&obj.ReservedFeeRecipient)
	if err != nil {
		return errors.NewField("ReservedFeeRecipient", err)
	}
	// Deserialize `MayhemModeEnabled`:
	err = decoder.Decode(&obj.MayhemModeEnabled)
	if err != nil {
		return errors.NewField("MayhemModeEnabled", err)
	}
	// Deserialize `ReservedFeeRecipients`:
	err = decoder.Decode(&obj.ReservedFeeRecipients)
	if err != nil {
		return errors.NewField("ReservedFeeRecipients", err)
	}
	return nil
}

func (obj *Global) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Global: %w", err)
	}
	return nil
}

func UnmarshalGlobal(buf []byte) (*Global, error) {
	obj := new(Global)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type GlobalVolumeAccumulator struct {
	StartTime        int64              `json:"startTime"`
	EndTime          int64              `json:"endTime"`
	SecondsInADay    int64              `json:"secondsInADay"`
	Mint             solanago.PublicKey `json:"mint"`
	TotalTokenSupply [30]uint64         `json:"totalTokenSupply"`
	SolVolumes       [30]uint64         `json:"solVolumes"`
}

func (obj GlobalVolumeAccumulator) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `StartTime`:
	err = encoder.Encode(obj.StartTime)
	if err != nil {
		return errors.NewField("StartTime", err)
	}
	// Serialize `EndTime`:
	err = encoder.Encode(obj.EndTime)
	if err != nil {
		return errors.NewField("EndTime", err)
	}
	// Serialize `SecondsInADay`:
	err = encoder.Encode(obj.SecondsInADay)
	if err != nil {
		return errors.NewField("SecondsInADay", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `TotalTokenSupply`:
	err = encoder.Encode(obj.TotalTokenSupply)
	if err != nil {
		return errors.NewField("TotalTokenSupply", err)
	}
	// Serialize `SolVolumes`:
	err = encoder.Encode(obj.SolVolumes)
	if err != nil {
		return errors.NewField("SolVolumes", err)
	}
	return nil
}

func (obj GlobalVolumeAccumulator) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding GlobalVolumeAccumulator: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *GlobalVolumeAccumulator) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `StartTime`:
	err = decoder.Decode(&obj.StartTime)
	if err != nil {
		return errors.NewField("StartTime", err)
	}
	// Deserialize `EndTime`:
	err = decoder.Decode(&obj.EndTime)
	if err != nil {
		return errors.NewField("EndTime", err)
	}
	// Deserialize `SecondsInADay`:
	err = decoder.Decode(&obj.SecondsInADay)
	if err != nil {
		return errors.NewField("SecondsInADay", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `TotalTokenSupply`:
	err = decoder.Decode(&obj.TotalTokenSupply)
	if err != nil {
		return errors.NewField("TotalTokenSupply", err)
	}
	// Deserialize `SolVolumes`:
	err = decoder.Decode(&obj.SolVolumes)
	if err != nil {
		return errors.NewField("SolVolumes", err)
	}
	return nil
}

func (obj *GlobalVolumeAccumulator) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling GlobalVolumeAccumulator: %w", err)
	}
	return nil
}

func UnmarshalGlobalVolumeAccumulator(buf []byte) (*GlobalVolumeAccumulator, error) {
	obj := new(GlobalVolumeAccumulator)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type InitUserVolumeAccumulatorEvent struct {
	Payer     solanago.PublicKey `json:"payer"`
	User      solanago.PublicKey `json:"user"`
	Timestamp int64              `json:"timestamp"`
}

func (obj InitUserVolumeAccumulatorEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Payer`:
	err = encoder.Encode(obj.Payer)
	if err != nil {
		return errors.NewField("Payer", err)
	}
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj InitUserVolumeAccumulatorEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding InitUserVolumeAccumulatorEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *InitUserVolumeAccumulatorEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Payer`:
	err = decoder.Decode(&obj.Payer)
	if err != nil {
		return errors.NewField("Payer", err)
	}
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj *InitUserVolumeAccumulatorEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling InitUserVolumeAccumulatorEvent: %w", err)
	}
	return nil
}

func UnmarshalInitUserVolumeAccumulatorEvent(buf []byte) (*InitUserVolumeAccumulatorEvent, error) {
	obj := new(InitUserVolumeAccumulatorEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type MigrateBondingCurveCreatorEvent struct {
	Timestamp     int64              `json:"timestamp"`
	Mint          solanago.PublicKey `json:"mint"`
	BondingCurve  solanago.PublicKey `json:"bondingCurve"`
	SharingConfig solanago.PublicKey `json:"sharingConfig"`
	OldCreator    solanago.PublicKey `json:"oldCreator"`
	NewCreator    solanago.PublicKey `json:"newCreator"`
}

func (obj MigrateBondingCurveCreatorEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `BondingCurve`:
	err = encoder.Encode(obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Serialize `SharingConfig`:
	err = encoder.Encode(obj.SharingConfig)
	if err != nil {
		return errors.NewField("SharingConfig", err)
	}
	// Serialize `OldCreator`:
	err = encoder.Encode(obj.OldCreator)
	if err != nil {
		return errors.NewField("OldCreator", err)
	}
	// Serialize `NewCreator`:
	err = encoder.Encode(obj.NewCreator)
	if err != nil {
		return errors.NewField("NewCreator", err)
	}
	return nil
}

func (obj MigrateBondingCurveCreatorEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding MigrateBondingCurveCreatorEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *MigrateBondingCurveCreatorEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `BondingCurve`:
	err = decoder.Decode(&obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Deserialize `SharingConfig`:
	err = decoder.Decode(&obj.SharingConfig)
	if err != nil {
		return errors.NewField("SharingConfig", err)
	}
	// Deserialize `OldCreator`:
	err = decoder.Decode(&obj.OldCreator)
	if err != nil {
		return errors.NewField("OldCreator", err)
	}
	// Deserialize `NewCreator`:
	err = decoder.Decode(&obj.NewCreator)
	if err != nil {
		return errors.NewField("NewCreator", err)
	}
	return nil
}

func (obj *MigrateBondingCurveCreatorEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling MigrateBondingCurveCreatorEvent: %w", err)
	}
	return nil
}

func UnmarshalMigrateBondingCurveCreatorEvent(buf []byte) (*MigrateBondingCurveCreatorEvent, error) {
	obj := new(MigrateBondingCurveCreatorEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type MinimumDistributableFeeEvent struct {
	MinimumRequired   uint64 `json:"minimumRequired"`
	DistributableFees uint64 `json:"distributableFees"`
	CanDistribute     bool   `json:"canDistribute"`
}

func (obj MinimumDistributableFeeEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `MinimumRequired`:
	err = encoder.Encode(obj.MinimumRequired)
	if err != nil {
		return errors.NewField("MinimumRequired", err)
	}
	// Serialize `DistributableFees`:
	err = encoder.Encode(obj.DistributableFees)
	if err != nil {
		return errors.NewField("DistributableFees", err)
	}
	// Serialize `CanDistribute`:
	err = encoder.Encode(obj.CanDistribute)
	if err != nil {
		return errors.NewField("CanDistribute", err)
	}
	return nil
}

func (obj MinimumDistributableFeeEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding MinimumDistributableFeeEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *MinimumDistributableFeeEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `MinimumRequired`:
	err = decoder.Decode(&obj.MinimumRequired)
	if err != nil {
		return errors.NewField("MinimumRequired", err)
	}
	// Deserialize `DistributableFees`:
	err = decoder.Decode(&obj.DistributableFees)
	if err != nil {
		return errors.NewField("DistributableFees", err)
	}
	// Deserialize `CanDistribute`:
	err = decoder.Decode(&obj.CanDistribute)
	if err != nil {
		return errors.NewField("CanDistribute", err)
	}
	return nil
}

func (obj *MinimumDistributableFeeEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling MinimumDistributableFeeEvent: %w", err)
	}
	return nil
}

func UnmarshalMinimumDistributableFeeEvent(buf []byte) (*MinimumDistributableFeeEvent, error) {
	obj := new(MinimumDistributableFeeEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type OptionBool struct {
	V0 bool `json:"v0"`
}

func (obj OptionBool) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `V0`:
	err = encoder.Encode(obj.V0)
	if err != nil {
		return errors.NewField("V0", err)
	}
	return nil
}

func (obj OptionBool) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding OptionBool: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *OptionBool) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `V0`:
	err = decoder.Decode(&obj.V0)
	if err != nil {
		return errors.NewField("V0", err)
	}
	return nil
}

func (obj *OptionBool) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling OptionBool: %w", err)
	}
	return nil
}

func UnmarshalOptionBool(buf []byte) (*OptionBool, error) {
	obj := new(OptionBool)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ReservedFeeRecipientsEvent struct {
	Timestamp             int64                 `json:"timestamp"`
	ReservedFeeRecipient  solanago.PublicKey    `json:"reservedFeeRecipient"`
	ReservedFeeRecipients [7]solanago.PublicKey `json:"reservedFeeRecipients"`
}

func (obj ReservedFeeRecipientsEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `ReservedFeeRecipient`:
	err = encoder.Encode(obj.ReservedFeeRecipient)
	if err != nil {
		return errors.NewField("ReservedFeeRecipient", err)
	}
	// Serialize `ReservedFeeRecipients`:
	err = encoder.Encode(obj.ReservedFeeRecipients)
	if err != nil {
		return errors.NewField("ReservedFeeRecipients", err)
	}
	return nil
}

func (obj ReservedFeeRecipientsEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ReservedFeeRecipientsEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ReservedFeeRecipientsEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `ReservedFeeRecipient`:
	err = decoder.Decode(&obj.ReservedFeeRecipient)
	if err != nil {
		return errors.NewField("ReservedFeeRecipient", err)
	}
	// Deserialize `ReservedFeeRecipients`:
	err = decoder.Decode(&obj.ReservedFeeRecipients)
	if err != nil {
		return errors.NewField("ReservedFeeRecipients", err)
	}
	return nil
}

func (obj *ReservedFeeRecipientsEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ReservedFeeRecipientsEvent: %w", err)
	}
	return nil
}

func UnmarshalReservedFeeRecipientsEvent(buf []byte) (*ReservedFeeRecipientsEvent, error) {
	obj := new(ReservedFeeRecipientsEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SetCreatorEvent struct {
	Timestamp    int64              `json:"timestamp"`
	Mint         solanago.PublicKey `json:"mint"`
	BondingCurve solanago.PublicKey `json:"bondingCurve"`
	Creator      solanago.PublicKey `json:"creator"`
}

func (obj SetCreatorEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `BondingCurve`:
	err = encoder.Encode(obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Serialize `Creator`:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	return nil
}

func (obj SetCreatorEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SetCreatorEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SetCreatorEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `BondingCurve`:
	err = decoder.Decode(&obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	return nil
}

func (obj *SetCreatorEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SetCreatorEvent: %w", err)
	}
	return nil
}

func UnmarshalSetCreatorEvent(buf []byte) (*SetCreatorEvent, error) {
	obj := new(SetCreatorEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SetMetaplexCreatorEvent struct {
	Timestamp    int64              `json:"timestamp"`
	Mint         solanago.PublicKey `json:"mint"`
	BondingCurve solanago.PublicKey `json:"bondingCurve"`
	Metadata     solanago.PublicKey `json:"metadata"`
	Creator      solanago.PublicKey `json:"creator"`
}

func (obj SetMetaplexCreatorEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `BondingCurve`:
	err = encoder.Encode(obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Serialize `Metadata`:
	err = encoder.Encode(obj.Metadata)
	if err != nil {
		return errors.NewField("Metadata", err)
	}
	// Serialize `Creator`:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	return nil
}

func (obj SetMetaplexCreatorEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SetMetaplexCreatorEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SetMetaplexCreatorEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `BondingCurve`:
	err = decoder.Decode(&obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Deserialize `Metadata`:
	err = decoder.Decode(&obj.Metadata)
	if err != nil {
		return errors.NewField("Metadata", err)
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	return nil
}

func (obj *SetMetaplexCreatorEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SetMetaplexCreatorEvent: %w", err)
	}
	return nil
}

func UnmarshalSetMetaplexCreatorEvent(buf []byte) (*SetMetaplexCreatorEvent, error) {
	obj := new(SetMetaplexCreatorEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SetParamsEvent struct {
	InitialVirtualTokenReserves uint64                `json:"initialVirtualTokenReserves"`
	InitialVirtualSolReserves   uint64                `json:"initialVirtualSolReserves"`
	InitialRealTokenReserves    uint64                `json:"initialRealTokenReserves"`
	FinalRealSolReserves        uint64                `json:"finalRealSolReserves"`
	TokenTotalSupply            uint64                `json:"tokenTotalSupply"`
	FeeBasisPoints              uint64                `json:"feeBasisPoints"`
	WithdrawAuthority           solanago.PublicKey    `json:"withdrawAuthority"`
	EnableMigrate               bool                  `json:"enableMigrate"`
	PoolMigrationFee            uint64                `json:"poolMigrationFee"`
	CreatorFeeBasisPoints       uint64                `json:"creatorFeeBasisPoints"`
	FeeRecipients               [8]solanago.PublicKey `json:"feeRecipients"`
	Timestamp                   int64                 `json:"timestamp"`
	SetCreatorAuthority         solanago.PublicKey    `json:"setCreatorAuthority"`
	AdminSetCreatorAuthority    solanago.PublicKey    `json:"adminSetCreatorAuthority"`
}

func (obj SetParamsEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `InitialVirtualTokenReserves`:
	err = encoder.Encode(obj.InitialVirtualTokenReserves)
	if err != nil {
		return errors.NewField("InitialVirtualTokenReserves", err)
	}
	// Serialize `InitialVirtualSolReserves`:
	err = encoder.Encode(obj.InitialVirtualSolReserves)
	if err != nil {
		return errors.NewField("InitialVirtualSolReserves", err)
	}
	// Serialize `InitialRealTokenReserves`:
	err = encoder.Encode(obj.InitialRealTokenReserves)
	if err != nil {
		return errors.NewField("InitialRealTokenReserves", err)
	}
	// Serialize `FinalRealSolReserves`:
	err = encoder.Encode(obj.FinalRealSolReserves)
	if err != nil {
		return errors.NewField("FinalRealSolReserves", err)
	}
	// Serialize `TokenTotalSupply`:
	err = encoder.Encode(obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	// Serialize `FeeBasisPoints`:
	err = encoder.Encode(obj.FeeBasisPoints)
	if err != nil {
		return errors.NewField("FeeBasisPoints", err)
	}
	// Serialize `WithdrawAuthority`:
	err = encoder.Encode(obj.WithdrawAuthority)
	if err != nil {
		return errors.NewField("WithdrawAuthority", err)
	}
	// Serialize `EnableMigrate`:
	err = encoder.Encode(obj.EnableMigrate)
	if err != nil {
		return errors.NewField("EnableMigrate", err)
	}
	// Serialize `PoolMigrationFee`:
	err = encoder.Encode(obj.PoolMigrationFee)
	if err != nil {
		return errors.NewField("PoolMigrationFee", err)
	}
	// Serialize `CreatorFeeBasisPoints`:
	err = encoder.Encode(obj.CreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CreatorFeeBasisPoints", err)
	}
	// Serialize `FeeRecipients`:
	err = encoder.Encode(obj.FeeRecipients)
	if err != nil {
		return errors.NewField("FeeRecipients", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `SetCreatorAuthority`:
	err = encoder.Encode(obj.SetCreatorAuthority)
	if err != nil {
		return errors.NewField("SetCreatorAuthority", err)
	}
	// Serialize `AdminSetCreatorAuthority`:
	err = encoder.Encode(obj.AdminSetCreatorAuthority)
	if err != nil {
		return errors.NewField("AdminSetCreatorAuthority", err)
	}
	return nil
}

func (obj SetParamsEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SetParamsEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SetParamsEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `InitialVirtualTokenReserves`:
	err = decoder.Decode(&obj.InitialVirtualTokenReserves)
	if err != nil {
		return errors.NewField("InitialVirtualTokenReserves", err)
	}
	// Deserialize `InitialVirtualSolReserves`:
	err = decoder.Decode(&obj.InitialVirtualSolReserves)
	if err != nil {
		return errors.NewField("InitialVirtualSolReserves", err)
	}
	// Deserialize `InitialRealTokenReserves`:
	err = decoder.Decode(&obj.InitialRealTokenReserves)
	if err != nil {
		return errors.NewField("InitialRealTokenReserves", err)
	}
	// Deserialize `FinalRealSolReserves`:
	err = decoder.Decode(&obj.FinalRealSolReserves)
	if err != nil {
		return errors.NewField("FinalRealSolReserves", err)
	}
	// Deserialize `TokenTotalSupply`:
	err = decoder.Decode(&obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	// Deserialize `FeeBasisPoints`:
	err = decoder.Decode(&obj.FeeBasisPoints)
	if err != nil {
		return errors.NewField("FeeBasisPoints", err)
	}
	// Deserialize `WithdrawAuthority`:
	err = decoder.Decode(&obj.WithdrawAuthority)
	if err != nil {
		return errors.NewField("WithdrawAuthority", err)
	}
	// Deserialize `EnableMigrate`:
	err = decoder.Decode(&obj.EnableMigrate)
	if err != nil {
		return errors.NewField("EnableMigrate", err)
	}
	// Deserialize `PoolMigrationFee`:
	err = decoder.Decode(&obj.PoolMigrationFee)
	if err != nil {
		return errors.NewField("PoolMigrationFee", err)
	}
	// Deserialize `CreatorFeeBasisPoints`:
	err = decoder.Decode(&obj.CreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CreatorFeeBasisPoints", err)
	}
	// Deserialize `FeeRecipients`:
	err = decoder.Decode(&obj.FeeRecipients)
	if err != nil {
		return errors.NewField("FeeRecipients", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `SetCreatorAuthority`:
	err = decoder.Decode(&obj.SetCreatorAuthority)
	if err != nil {
		return errors.NewField("SetCreatorAuthority", err)
	}
	// Deserialize `AdminSetCreatorAuthority`:
	err = decoder.Decode(&obj.AdminSetCreatorAuthority)
	if err != nil {
		return errors.NewField("AdminSetCreatorAuthority", err)
	}
	return nil
}

func (obj *SetParamsEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SetParamsEvent: %w", err)
	}
	return nil
}

func UnmarshalSetParamsEvent(buf []byte) (*SetParamsEvent, error) {
	obj := new(SetParamsEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Shareholder struct {
	Address  solanago.PublicKey `json:"address"`
	ShareBps uint16             `json:"shareBps"`
}

func (obj Shareholder) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Address`:
	err = encoder.Encode(obj.Address)
	if err != nil {
		return errors.NewField("Address", err)
	}
	// Serialize `ShareBps`:
	err = encoder.Encode(obj.ShareBps)
	if err != nil {
		return errors.NewField("ShareBps", err)
	}
	return nil
}

func (obj Shareholder) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Shareholder: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Shareholder) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Address`:
	err = decoder.Decode(&obj.Address)
	if err != nil {
		return errors.NewField("Address", err)
	}
	// Deserialize `ShareBps`:
	err = decoder.Decode(&obj.ShareBps)
	if err != nil {
		return errors.NewField("ShareBps", err)
	}
	return nil
}

func (obj *Shareholder) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Shareholder: %w", err)
	}
	return nil
}

func UnmarshalShareholder(buf []byte) (*Shareholder, error) {
	obj := new(Shareholder)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SharingConfig struct {
	Bump         uint8              `json:"bump"`
	Version      uint8              `json:"version"`
	Status       ConfigStatus       `json:"status"`
	Mint         solanago.PublicKey `json:"mint"`
	Admin        solanago.PublicKey `json:"admin"`
	AdminRevoked bool               `json:"adminRevoked"`
	Shareholders []Shareholder      `json:"shareholders"`
}

func (obj SharingConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `Version`:
	err = encoder.Encode(obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Serialize `Status`:
	err = encoder.Encode(obj.Status)
	if err != nil {
		return errors.NewField("Status", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `Admin`:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Serialize `AdminRevoked`:
	err = encoder.Encode(obj.AdminRevoked)
	if err != nil {
		return errors.NewField("AdminRevoked", err)
	}
	// Serialize `Shareholders`:
	err = encoder.Encode(obj.Shareholders)
	if err != nil {
		return errors.NewField("Shareholders", err)
	}
	return nil
}

func (obj SharingConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SharingConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SharingConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `Version`:
	err = decoder.Decode(&obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Deserialize `Status`:
	err = decoder.Decode(&obj.Status)
	if err != nil {
		return errors.NewField("Status", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Deserialize `AdminRevoked`:
	err = decoder.Decode(&obj.AdminRevoked)
	if err != nil {
		return errors.NewField("AdminRevoked", err)
	}
	// Deserialize `Shareholders`:
	err = decoder.Decode(&obj.Shareholders)
	if err != nil {
		return errors.NewField("Shareholders", err)
	}
	return nil
}

func (obj *SharingConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SharingConfig: %w", err)
	}
	return nil
}

func UnmarshalSharingConfig(buf []byte) (*SharingConfig, error) {
	obj := new(SharingConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SyncUserVolumeAccumulatorEvent struct {
	User                     solanago.PublicKey `json:"user"`
	TotalClaimedTokensBefore uint64             `json:"totalClaimedTokensBefore"`
	TotalClaimedTokensAfter  uint64             `json:"totalClaimedTokensAfter"`
	Timestamp                int64              `json:"timestamp"`
}

func (obj SyncUserVolumeAccumulatorEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `TotalClaimedTokensBefore`:
	err = encoder.Encode(obj.TotalClaimedTokensBefore)
	if err != nil {
		return errors.NewField("TotalClaimedTokensBefore", err)
	}
	// Serialize `TotalClaimedTokensAfter`:
	err = encoder.Encode(obj.TotalClaimedTokensAfter)
	if err != nil {
		return errors.NewField("TotalClaimedTokensAfter", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj SyncUserVolumeAccumulatorEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SyncUserVolumeAccumulatorEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SyncUserVolumeAccumulatorEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `TotalClaimedTokensBefore`:
	err = decoder.Decode(&obj.TotalClaimedTokensBefore)
	if err != nil {
		return errors.NewField("TotalClaimedTokensBefore", err)
	}
	// Deserialize `TotalClaimedTokensAfter`:
	err = decoder.Decode(&obj.TotalClaimedTokensAfter)
	if err != nil {
		return errors.NewField("TotalClaimedTokensAfter", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj *SyncUserVolumeAccumulatorEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SyncUserVolumeAccumulatorEvent: %w", err)
	}
	return nil
}

func UnmarshalSyncUserVolumeAccumulatorEvent(buf []byte) (*SyncUserVolumeAccumulatorEvent, error) {
	obj := new(SyncUserVolumeAccumulatorEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// ix_name: "buy" | "sell" | "buy_exact_sol_in"
type TradeEvent struct {
	Mint                 solanago.PublicKey `json:"mint"`
	SolAmount            uint64             `json:"solAmount"`
	TokenAmount          uint64             `json:"tokenAmount"`
	IsBuy                bool               `json:"isBuy"`
	User                 solanago.PublicKey `json:"user"`
	Timestamp            int64              `json:"timestamp"`
	VirtualSolReserves   uint64             `json:"virtualSolReserves"`
	VirtualTokenReserves uint64             `json:"virtualTokenReserves"`
	RealSolReserves      uint64             `json:"realSolReserves"`
	RealTokenReserves    uint64             `json:"realTokenReserves"`
}

func (obj TradeEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `SolAmount`:
	err = encoder.Encode(obj.SolAmount)
	if err != nil {
		return errors.NewField("SolAmount", err)
	}
	// Serialize `TokenAmount`:
	err = encoder.Encode(obj.TokenAmount)
	if err != nil {
		return errors.NewField("TokenAmount", err)
	}
	// Serialize `IsBuy`:
	err = encoder.Encode(obj.IsBuy)
	if err != nil {
		return errors.NewField("IsBuy", err)
	}
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `VirtualSolReserves`:
	err = encoder.Encode(obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Serialize `VirtualTokenReserves`:
	err = encoder.Encode(obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Serialize `RealSolReserves`:
	err = encoder.Encode(obj.RealSolReserves)
	if err != nil {
		return errors.NewField("RealSolReserves", err)
	}
	// Serialize `RealTokenReserves`:
	err = encoder.Encode(obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	return nil
}

func (obj TradeEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TradeEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TradeEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `SolAmount`:
	err = decoder.Decode(&obj.SolAmount)
	if err != nil {
		return errors.NewField("SolAmount", err)
	}
	// Deserialize `TokenAmount`:
	err = decoder.Decode(&obj.TokenAmount)
	if err != nil {
		return errors.NewField("TokenAmount", err)
	}
	// Deserialize `IsBuy`:
	err = decoder.Decode(&obj.IsBuy)
	if err != nil {
		return errors.NewField("IsBuy", err)
	}
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `VirtualSolReserves`:
	err = decoder.Decode(&obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Deserialize `VirtualTokenReserves`:
	err = decoder.Decode(&obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Deserialize `RealSolReserves`:
	err = decoder.Decode(&obj.RealSolReserves)
	if err != nil {
		return errors.NewField("RealSolReserves", err)
	}
	// Deserialize `RealTokenReserves`:
	err = decoder.Decode(&obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	return nil
}

func (obj *TradeEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TradeEvent: %w", err)
	}
	return nil
}

func UnmarshalTradeEvent(buf []byte) (*TradeEvent, error) {
	obj := new(TradeEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type UpdateGlobalAuthorityEvent struct {
	Global       solanago.PublicKey `json:"global"`
	Authority    solanago.PublicKey `json:"authority"`
	NewAuthority solanago.PublicKey `json:"newAuthority"`
	Timestamp    int64              `json:"timestamp"`
}

func (obj UpdateGlobalAuthorityEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Global`:
	err = encoder.Encode(obj.Global)
	if err != nil {
		return errors.NewField("Global", err)
	}
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `NewAuthority`:
	err = encoder.Encode(obj.NewAuthority)
	if err != nil {
		return errors.NewField("NewAuthority", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj UpdateGlobalAuthorityEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding UpdateGlobalAuthorityEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *UpdateGlobalAuthorityEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Global`:
	err = decoder.Decode(&obj.Global)
	if err != nil {
		return errors.NewField("Global", err)
	}
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `NewAuthority`:
	err = decoder.Decode(&obj.NewAuthority)
	if err != nil {
		return errors.NewField("NewAuthority", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj *UpdateGlobalAuthorityEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling UpdateGlobalAuthorityEvent: %w", err)
	}
	return nil
}

func UnmarshalUpdateGlobalAuthorityEvent(buf []byte) (*UpdateGlobalAuthorityEvent, error) {
	obj := new(UpdateGlobalAuthorityEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type UpdateMayhemVirtualParamsEvent struct {
	Timestamp               int64              `json:"timestamp"`
	Mint                    solanago.PublicKey `json:"mint"`
	VirtualTokenReserves    uint64             `json:"virtualTokenReserves"`
	VirtualSolReserves      uint64             `json:"virtualSolReserves"`
	NewVirtualTokenReserves uint64             `json:"newVirtualTokenReserves"`
	NewVirtualSolReserves   uint64             `json:"newVirtualSolReserves"`
	RealTokenReserves       uint64             `json:"realTokenReserves"`
	RealSolReserves         uint64             `json:"realSolReserves"`
}

func (obj UpdateMayhemVirtualParamsEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `VirtualTokenReserves`:
	err = encoder.Encode(obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Serialize `VirtualSolReserves`:
	err = encoder.Encode(obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Serialize `NewVirtualTokenReserves`:
	err = encoder.Encode(obj.NewVirtualTokenReserves)
	if err != nil {
		return errors.NewField("NewVirtualTokenReserves", err)
	}
	// Serialize `NewVirtualSolReserves`:
	err = encoder.Encode(obj.NewVirtualSolReserves)
	if err != nil {
		return errors.NewField("NewVirtualSolReserves", err)
	}
	// Serialize `RealTokenReserves`:
	err = encoder.Encode(obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	// Serialize `RealSolReserves`:
	err = encoder.Encode(obj.RealSolReserves)
	if err != nil {
		return errors.NewField("RealSolReserves", err)
	}
	return nil
}

func (obj UpdateMayhemVirtualParamsEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding UpdateMayhemVirtualParamsEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *UpdateMayhemVirtualParamsEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `VirtualTokenReserves`:
	err = decoder.Decode(&obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Deserialize `VirtualSolReserves`:
	err = decoder.Decode(&obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Deserialize `NewVirtualTokenReserves`:
	err = decoder.Decode(&obj.NewVirtualTokenReserves)
	if err != nil {
		return errors.NewField("NewVirtualTokenReserves", err)
	}
	// Deserialize `NewVirtualSolReserves`:
	err = decoder.Decode(&obj.NewVirtualSolReserves)
	if err != nil {
		return errors.NewField("NewVirtualSolReserves", err)
	}
	// Deserialize `RealTokenReserves`:
	err = decoder.Decode(&obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	// Deserialize `RealSolReserves`:
	err = decoder.Decode(&obj.RealSolReserves)
	if err != nil {
		return errors.NewField("RealSolReserves", err)
	}
	return nil
}

func (obj *UpdateMayhemVirtualParamsEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling UpdateMayhemVirtualParamsEvent: %w", err)
	}
	return nil
}

func UnmarshalUpdateMayhemVirtualParamsEvent(buf []byte) (*UpdateMayhemVirtualParamsEvent, error) {
	obj := new(UpdateMayhemVirtualParamsEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type UserVolumeAccumulator struct {
	User                  solanago.PublicKey `json:"user"`
	NeedsClaim            bool               `json:"needsClaim"`
	TotalUnclaimedTokens  uint64             `json:"totalUnclaimedTokens"`
	TotalClaimedTokens    uint64             `json:"totalClaimedTokens"`
	CurrentSolVolume      uint64             `json:"currentSolVolume"`
	LastUpdateTimestamp   int64              `json:"lastUpdateTimestamp"`
	HasTotalClaimedTokens bool               `json:"hasTotalClaimedTokens"`
}

func (obj UserVolumeAccumulator) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `NeedsClaim`:
	err = encoder.Encode(obj.NeedsClaim)
	if err != nil {
		return errors.NewField("NeedsClaim", err)
	}
	// Serialize `TotalUnclaimedTokens`:
	err = encoder.Encode(obj.TotalUnclaimedTokens)
	if err != nil {
		return errors.NewField("TotalUnclaimedTokens", err)
	}
	// Serialize `TotalClaimedTokens`:
	err = encoder.Encode(obj.TotalClaimedTokens)
	if err != nil {
		return errors.NewField("TotalClaimedTokens", err)
	}
	// Serialize `CurrentSolVolume`:
	err = encoder.Encode(obj.CurrentSolVolume)
	if err != nil {
		return errors.NewField("CurrentSolVolume", err)
	}
	// Serialize `LastUpdateTimestamp`:
	err = encoder.Encode(obj.LastUpdateTimestamp)
	if err != nil {
		return errors.NewField("LastUpdateTimestamp", err)
	}
	// Serialize `HasTotalClaimedTokens`:
	err = encoder.Encode(obj.HasTotalClaimedTokens)
	if err != nil {
		return errors.NewField("HasTotalClaimedTokens", err)
	}
	return nil
}

func (obj UserVolumeAccumulator) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding UserVolumeAccumulator: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *UserVolumeAccumulator) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `NeedsClaim`:
	err = decoder.Decode(&obj.NeedsClaim)
	if err != nil {
		return errors.NewField("NeedsClaim", err)
	}
	// Deserialize `TotalUnclaimedTokens`:
	err = decoder.Decode(&obj.TotalUnclaimedTokens)
	if err != nil {
		return errors.NewField("TotalUnclaimedTokens", err)
	}
	// Deserialize `TotalClaimedTokens`:
	err = decoder.Decode(&obj.TotalClaimedTokens)
	if err != nil {
		return errors.NewField("TotalClaimedTokens", err)
	}
	// Deserialize `CurrentSolVolume`:
	err = decoder.Decode(&obj.CurrentSolVolume)
	if err != nil {
		return errors.NewField("CurrentSolVolume", err)
	}
	// Deserialize `LastUpdateTimestamp`:
	err = decoder.Decode(&obj.LastUpdateTimestamp)
	if err != nil {
		return errors.NewField("LastUpdateTimestamp", err)
	}
	// Deserialize `HasTotalClaimedTokens`:
	err = decoder.Decode(&obj.HasTotalClaimedTokens)
	if err != nil {
		return errors.NewField("HasTotalClaimedTokens", err)
	}
	return nil
}

func (obj *UserVolumeAccumulator) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling UserVolumeAccumulator: %w", err)
	}
	return nil
}

func UnmarshalUserVolumeAccumulator(buf []byte) (*UserVolumeAccumulator, error) {
	obj := new(UserVolumeAccumulator)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
