// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package meteora_dlmm

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AddLiquidity2 is the `addLiquidity2` instruction.
type AddLiquidity2 struct {
	LiquidityParameter    *LiquidityParameter
	RemainingAccountsInfo *RemainingAccountsInfo

	// [0] = [WRITE] position
	//
	// [1] = [WRITE] lbPair
	//
	// [2] = [WRITE] binArrayBitmapExtension
	//
	// [3] = [WRITE] userTokenX
	//
	// [4] = [WRITE] userTokenY
	//
	// [5] = [WRITE] reserveX
	//
	// [6] = [WRITE] reserveY
	//
	// [7] = [] tokenXMint
	//
	// [8] = [] tokenYMint
	//
	// [9] = [SIGNER] sender
	//
	// [10] = [] tokenXProgram
	//
	// [11] = [] tokenYProgram
	//
	// [12] = [] eventAuthority
	//
	// [13] = [] program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAddLiquidity2InstructionBuilder creates a new `AddLiquidity2` instruction builder.
func NewAddLiquidity2InstructionBuilder() *AddLiquidity2 {
	nd := &AddLiquidity2{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 14),
	}
	return nd
}

// SetLiquidityParameter sets the "liquidityParameter" parameter.
func (inst *AddLiquidity2) SetLiquidityParameter(liquidityParameter LiquidityParameter) *AddLiquidity2 {
	inst.LiquidityParameter = &liquidityParameter
	return inst
}

// SetRemainingAccountsInfo sets the "remainingAccountsInfo" parameter.
func (inst *AddLiquidity2) SetRemainingAccountsInfo(remainingAccountsInfo RemainingAccountsInfo) *AddLiquidity2 {
	inst.RemainingAccountsInfo = &remainingAccountsInfo
	return inst
}

// SetPositionAccount sets the "position" account.
func (inst *AddLiquidity2) SetPositionAccount(position ag_solanago.PublicKey) *AddLiquidity2 {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(position).WRITE()
	return inst
}

// GetPositionAccount gets the "position" account.
func (inst *AddLiquidity2) GetPositionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetLbPairAccount sets the "lbPair" account.
func (inst *AddLiquidity2) SetLbPairAccount(lbPair ag_solanago.PublicKey) *AddLiquidity2 {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(lbPair).WRITE()
	return inst
}

// GetLbPairAccount gets the "lbPair" account.
func (inst *AddLiquidity2) GetLbPairAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetBinArrayBitmapExtensionAccount sets the "binArrayBitmapExtension" account.
func (inst *AddLiquidity2) SetBinArrayBitmapExtensionAccount(binArrayBitmapExtension ag_solanago.PublicKey) *AddLiquidity2 {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(binArrayBitmapExtension).WRITE()
	return inst
}

// GetBinArrayBitmapExtensionAccount gets the "binArrayBitmapExtension" account.
func (inst *AddLiquidity2) GetBinArrayBitmapExtensionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetUserTokenXAccount sets the "userTokenX" account.
func (inst *AddLiquidity2) SetUserTokenXAccount(userTokenX ag_solanago.PublicKey) *AddLiquidity2 {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(userTokenX).WRITE()
	return inst
}

// GetUserTokenXAccount gets the "userTokenX" account.
func (inst *AddLiquidity2) GetUserTokenXAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetUserTokenYAccount sets the "userTokenY" account.
func (inst *AddLiquidity2) SetUserTokenYAccount(userTokenY ag_solanago.PublicKey) *AddLiquidity2 {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(userTokenY).WRITE()
	return inst
}

// GetUserTokenYAccount gets the "userTokenY" account.
func (inst *AddLiquidity2) GetUserTokenYAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetReserveXAccount sets the "reserveX" account.
func (inst *AddLiquidity2) SetReserveXAccount(reserveX ag_solanago.PublicKey) *AddLiquidity2 {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(reserveX).WRITE()
	return inst
}

// GetReserveXAccount gets the "reserveX" account.
func (inst *AddLiquidity2) GetReserveXAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetReserveYAccount sets the "reserveY" account.
func (inst *AddLiquidity2) SetReserveYAccount(reserveY ag_solanago.PublicKey) *AddLiquidity2 {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(reserveY).WRITE()
	return inst
}

// GetReserveYAccount gets the "reserveY" account.
func (inst *AddLiquidity2) GetReserveYAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetTokenXMintAccount sets the "tokenXMint" account.
func (inst *AddLiquidity2) SetTokenXMintAccount(tokenXMint ag_solanago.PublicKey) *AddLiquidity2 {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(tokenXMint)
	return inst
}

// GetTokenXMintAccount gets the "tokenXMint" account.
func (inst *AddLiquidity2) GetTokenXMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetTokenYMintAccount sets the "tokenYMint" account.
func (inst *AddLiquidity2) SetTokenYMintAccount(tokenYMint ag_solanago.PublicKey) *AddLiquidity2 {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(tokenYMint)
	return inst
}

// GetTokenYMintAccount gets the "tokenYMint" account.
func (inst *AddLiquidity2) GetTokenYMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetSenderAccount sets the "sender" account.
func (inst *AddLiquidity2) SetSenderAccount(sender ag_solanago.PublicKey) *AddLiquidity2 {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(sender).SIGNER()
	return inst
}

// GetSenderAccount gets the "sender" account.
func (inst *AddLiquidity2) GetSenderAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetTokenXProgramAccount sets the "tokenXProgram" account.
func (inst *AddLiquidity2) SetTokenXProgramAccount(tokenXProgram ag_solanago.PublicKey) *AddLiquidity2 {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(tokenXProgram)
	return inst
}

// GetTokenXProgramAccount gets the "tokenXProgram" account.
func (inst *AddLiquidity2) GetTokenXProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetTokenYProgramAccount sets the "tokenYProgram" account.
func (inst *AddLiquidity2) SetTokenYProgramAccount(tokenYProgram ag_solanago.PublicKey) *AddLiquidity2 {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(tokenYProgram)
	return inst
}

// GetTokenYProgramAccount gets the "tokenYProgram" account.
func (inst *AddLiquidity2) GetTokenYProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetEventAuthorityAccount sets the "eventAuthority" account.
func (inst *AddLiquidity2) SetEventAuthorityAccount(eventAuthority ag_solanago.PublicKey) *AddLiquidity2 {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(eventAuthority)
	return inst
}

// GetEventAuthorityAccount gets the "eventAuthority" account.
func (inst *AddLiquidity2) GetEventAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetProgramAccount sets the "program" account.
func (inst *AddLiquidity2) SetProgramAccount(program ag_solanago.PublicKey) *AddLiquidity2 {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(program)
	return inst
}

// GetProgramAccount gets the "program" account.
func (inst *AddLiquidity2) GetProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

func (inst AddLiquidity2) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AddLiquidity2,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AddLiquidity2) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AddLiquidity2) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.LiquidityParameter == nil {
			return errors.New("LiquidityParameter parameter is not set")
		}
		if inst.RemainingAccountsInfo == nil {
			return errors.New("RemainingAccountsInfo parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Position is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.LbPair is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.BinArrayBitmapExtension is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.UserTokenX is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.UserTokenY is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.ReserveX is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.ReserveY is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.TokenXMint is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.TokenYMint is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.Sender is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.TokenXProgram is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.TokenYProgram is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.EventAuthority is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.Program is not set")
		}
	}
	return nil
}

func (inst *AddLiquidity2) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AddLiquidity2")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("   LiquidityParameter", *inst.LiquidityParameter))
						paramsBranch.Child(ag_format.Param("RemainingAccountsInfo", *inst.RemainingAccountsInfo))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=14]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("               position", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("                 lbPair", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("binArrayBitmapExtension", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("             userTokenX", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("             userTokenY", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("               reserveX", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("               reserveY", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("             tokenXMint", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("             tokenYMint", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("                 sender", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("          tokenXProgram", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("          tokenYProgram", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("         eventAuthority", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("                program", inst.AccountMetaSlice.Get(13)))
					})
				})
		})
}

func (obj AddLiquidity2) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `LiquidityParameter` param:
	err = encoder.Encode(obj.LiquidityParameter)
	if err != nil {
		return err
	}
	// Serialize `RemainingAccountsInfo` param:
	err = encoder.Encode(obj.RemainingAccountsInfo)
	if err != nil {
		return err
	}
	return nil
}
func (obj *AddLiquidity2) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `LiquidityParameter`:
	err = decoder.Decode(&obj.LiquidityParameter)
	if err != nil {
		return err
	}
	// Deserialize `RemainingAccountsInfo`:
	err = decoder.Decode(&obj.RemainingAccountsInfo)
	if err != nil {
		return err
	}
	return nil
}

// NewAddLiquidity2Instruction declares a new AddLiquidity2 instruction with the provided parameters and accounts.
func NewAddLiquidity2Instruction(
	// Parameters:
	liquidityParameter LiquidityParameter,
	remainingAccountsInfo RemainingAccountsInfo,
	// Accounts:
	position ag_solanago.PublicKey,
	lbPair ag_solanago.PublicKey,
	binArrayBitmapExtension ag_solanago.PublicKey,
	userTokenX ag_solanago.PublicKey,
	userTokenY ag_solanago.PublicKey,
	reserveX ag_solanago.PublicKey,
	reserveY ag_solanago.PublicKey,
	tokenXMint ag_solanago.PublicKey,
	tokenYMint ag_solanago.PublicKey,
	sender ag_solanago.PublicKey,
	tokenXProgram ag_solanago.PublicKey,
	tokenYProgram ag_solanago.PublicKey,
	eventAuthority ag_solanago.PublicKey,
	program ag_solanago.PublicKey) *AddLiquidity2 {
	return NewAddLiquidity2InstructionBuilder().
		SetLiquidityParameter(liquidityParameter).
		SetRemainingAccountsInfo(remainingAccountsInfo).
		SetPositionAccount(position).
		SetLbPairAccount(lbPair).
		SetBinArrayBitmapExtensionAccount(binArrayBitmapExtension).
		SetUserTokenXAccount(userTokenX).
		SetUserTokenYAccount(userTokenY).
		SetReserveXAccount(reserveX).
		SetReserveYAccount(reserveY).
		SetTokenXMintAccount(tokenXMint).
		SetTokenYMintAccount(tokenYMint).
		SetSenderAccount(sender).
		SetTokenXProgramAccount(tokenXProgram).
		SetTokenYProgramAccount(tokenYProgram).
		SetEventAuthorityAccount(eventAuthority).
		SetProgramAccount(program)
}
