// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package meteora_dlmm

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ClaimReward2 is the `claimReward2` instruction.
type ClaimReward2 struct {
	RewardIndex           *uint64
	MinBinId              *int32
	MaxBinId              *int32
	RemainingAccountsInfo *RemainingAccountsInfo

	// [0] = [WRITE] lbPair
	//
	// [1] = [WRITE] position
	//
	// [2] = [SIGNER] sender
	//
	// [3] = [WRITE] rewardVault
	//
	// [4] = [] rewardMint
	//
	// [5] = [WRITE] userTokenAccount
	//
	// [6] = [] tokenProgram
	//
	// [7] = [] memoProgram
	//
	// [8] = [] eventAuthority
	//
	// [9] = [] program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewClaimReward2InstructionBuilder creates a new `ClaimReward2` instruction builder.
func NewClaimReward2InstructionBuilder() *ClaimReward2 {
	nd := &ClaimReward2{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 10),
	}
	return nd
}

// SetRewardIndex sets the "rewardIndex" parameter.
func (inst *ClaimReward2) SetRewardIndex(rewardIndex uint64) *ClaimReward2 {
	inst.RewardIndex = &rewardIndex
	return inst
}

// SetMinBinId sets the "minBinId" parameter.
func (inst *ClaimReward2) SetMinBinId(minBinId int32) *ClaimReward2 {
	inst.MinBinId = &minBinId
	return inst
}

// SetMaxBinId sets the "maxBinId" parameter.
func (inst *ClaimReward2) SetMaxBinId(maxBinId int32) *ClaimReward2 {
	inst.MaxBinId = &maxBinId
	return inst
}

// SetRemainingAccountsInfo sets the "remainingAccountsInfo" parameter.
func (inst *ClaimReward2) SetRemainingAccountsInfo(remainingAccountsInfo RemainingAccountsInfo) *ClaimReward2 {
	inst.RemainingAccountsInfo = &remainingAccountsInfo
	return inst
}

// SetLbPairAccount sets the "lbPair" account.
func (inst *ClaimReward2) SetLbPairAccount(lbPair ag_solanago.PublicKey) *ClaimReward2 {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(lbPair).WRITE()
	return inst
}

// GetLbPairAccount gets the "lbPair" account.
func (inst *ClaimReward2) GetLbPairAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetPositionAccount sets the "position" account.
func (inst *ClaimReward2) SetPositionAccount(position ag_solanago.PublicKey) *ClaimReward2 {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(position).WRITE()
	return inst
}

// GetPositionAccount gets the "position" account.
func (inst *ClaimReward2) GetPositionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSenderAccount sets the "sender" account.
func (inst *ClaimReward2) SetSenderAccount(sender ag_solanago.PublicKey) *ClaimReward2 {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(sender).SIGNER()
	return inst
}

// GetSenderAccount gets the "sender" account.
func (inst *ClaimReward2) GetSenderAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetRewardVaultAccount sets the "rewardVault" account.
func (inst *ClaimReward2) SetRewardVaultAccount(rewardVault ag_solanago.PublicKey) *ClaimReward2 {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(rewardVault).WRITE()
	return inst
}

// GetRewardVaultAccount gets the "rewardVault" account.
func (inst *ClaimReward2) GetRewardVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetRewardMintAccount sets the "rewardMint" account.
func (inst *ClaimReward2) SetRewardMintAccount(rewardMint ag_solanago.PublicKey) *ClaimReward2 {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(rewardMint)
	return inst
}

// GetRewardMintAccount gets the "rewardMint" account.
func (inst *ClaimReward2) GetRewardMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetUserTokenAccountAccount sets the "userTokenAccount" account.
func (inst *ClaimReward2) SetUserTokenAccountAccount(userTokenAccount ag_solanago.PublicKey) *ClaimReward2 {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(userTokenAccount).WRITE()
	return inst
}

// GetUserTokenAccountAccount gets the "userTokenAccount" account.
func (inst *ClaimReward2) GetUserTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *ClaimReward2) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *ClaimReward2 {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *ClaimReward2) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetMemoProgramAccount sets the "memoProgram" account.
func (inst *ClaimReward2) SetMemoProgramAccount(memoProgram ag_solanago.PublicKey) *ClaimReward2 {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(memoProgram)
	return inst
}

// GetMemoProgramAccount gets the "memoProgram" account.
func (inst *ClaimReward2) GetMemoProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetEventAuthorityAccount sets the "eventAuthority" account.
func (inst *ClaimReward2) SetEventAuthorityAccount(eventAuthority ag_solanago.PublicKey) *ClaimReward2 {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(eventAuthority)
	return inst
}

// GetEventAuthorityAccount gets the "eventAuthority" account.
func (inst *ClaimReward2) GetEventAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetProgramAccount sets the "program" account.
func (inst *ClaimReward2) SetProgramAccount(program ag_solanago.PublicKey) *ClaimReward2 {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(program)
	return inst
}

// GetProgramAccount gets the "program" account.
func (inst *ClaimReward2) GetProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

func (inst ClaimReward2) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ClaimReward2,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ClaimReward2) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ClaimReward2) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.RewardIndex == nil {
			return errors.New("RewardIndex parameter is not set")
		}
		if inst.MinBinId == nil {
			return errors.New("MinBinId parameter is not set")
		}
		if inst.MaxBinId == nil {
			return errors.New("MaxBinId parameter is not set")
		}
		if inst.RemainingAccountsInfo == nil {
			return errors.New("RemainingAccountsInfo parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.LbPair is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Position is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Sender is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.RewardVault is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.RewardMint is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.UserTokenAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.MemoProgram is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.EventAuthority is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.Program is not set")
		}
	}
	return nil
}

func (inst *ClaimReward2) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ClaimReward2")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=4]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("          RewardIndex", *inst.RewardIndex))
						paramsBranch.Child(ag_format.Param("             MinBinId", *inst.MinBinId))
						paramsBranch.Child(ag_format.Param("             MaxBinId", *inst.MaxBinId))
						paramsBranch.Child(ag_format.Param("RemainingAccountsInfo", *inst.RemainingAccountsInfo))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=10]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("        lbPair", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("      position", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("        sender", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("   rewardVault", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("    rewardMint", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("     userToken", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("  tokenProgram", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("   memoProgram", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("eventAuthority", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("       program", inst.AccountMetaSlice.Get(9)))
					})
				})
		})
}

func (obj ClaimReward2) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `RewardIndex` param:
	err = encoder.Encode(obj.RewardIndex)
	if err != nil {
		return err
	}
	// Serialize `MinBinId` param:
	err = encoder.Encode(obj.MinBinId)
	if err != nil {
		return err
	}
	// Serialize `MaxBinId` param:
	err = encoder.Encode(obj.MaxBinId)
	if err != nil {
		return err
	}
	// Serialize `RemainingAccountsInfo` param:
	err = encoder.Encode(obj.RemainingAccountsInfo)
	if err != nil {
		return err
	}
	return nil
}
func (obj *ClaimReward2) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `RewardIndex`:
	err = decoder.Decode(&obj.RewardIndex)
	if err != nil {
		return err
	}
	// Deserialize `MinBinId`:
	err = decoder.Decode(&obj.MinBinId)
	if err != nil {
		return err
	}
	// Deserialize `MaxBinId`:
	err = decoder.Decode(&obj.MaxBinId)
	if err != nil {
		return err
	}
	// Deserialize `RemainingAccountsInfo`:
	err = decoder.Decode(&obj.RemainingAccountsInfo)
	if err != nil {
		return err
	}
	return nil
}

// NewClaimReward2Instruction declares a new ClaimReward2 instruction with the provided parameters and accounts.
func NewClaimReward2Instruction(
	// Parameters:
	rewardIndex uint64,
	minBinId int32,
	maxBinId int32,
	remainingAccountsInfo RemainingAccountsInfo,
	// Accounts:
	lbPair ag_solanago.PublicKey,
	position ag_solanago.PublicKey,
	sender ag_solanago.PublicKey,
	rewardVault ag_solanago.PublicKey,
	rewardMint ag_solanago.PublicKey,
	userTokenAccount ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	memoProgram ag_solanago.PublicKey,
	eventAuthority ag_solanago.PublicKey,
	program ag_solanago.PublicKey) *ClaimReward2 {
	return NewClaimReward2InstructionBuilder().
		SetRewardIndex(rewardIndex).
		SetMinBinId(minBinId).
		SetMaxBinId(maxBinId).
		SetRemainingAccountsInfo(remainingAccountsInfo).
		SetLbPairAccount(lbPair).
		SetPositionAccount(position).
		SetSenderAccount(sender).
		SetRewardVaultAccount(rewardVault).
		SetRewardMintAccount(rewardMint).
		SetUserTokenAccountAccount(userTokenAccount).
		SetTokenProgramAccount(tokenProgram).
		SetMemoProgramAccount(memoProgram).
		SetEventAuthorityAccount(eventAuthority).
		SetProgramAccount(program)
}
