// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package meteora_dlmm

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// InitializeTokenBadge is the `initializeTokenBadge` instruction.
type InitializeTokenBadge struct {

	// [0] = [] tokenMint
	//
	// [1] = [WRITE] tokenBadge
	//
	// [2] = [WRITE, SIGNER] admin
	//
	// [3] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewInitializeTokenBadgeInstructionBuilder creates a new `InitializeTokenBadge` instruction builder.
func NewInitializeTokenBadgeInstructionBuilder() *InitializeTokenBadge {
	nd := &InitializeTokenBadge{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetTokenMintAccount sets the "tokenMint" account.
func (inst *InitializeTokenBadge) SetTokenMintAccount(tokenMint ag_solanago.PublicKey) *InitializeTokenBadge {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(tokenMint)
	return inst
}

// GetTokenMintAccount gets the "tokenMint" account.
func (inst *InitializeTokenBadge) GetTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetTokenBadgeAccount sets the "tokenBadge" account.
func (inst *InitializeTokenBadge) SetTokenBadgeAccount(tokenBadge ag_solanago.PublicKey) *InitializeTokenBadge {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(tokenBadge).WRITE()
	return inst
}

// GetTokenBadgeAccount gets the "tokenBadge" account.
func (inst *InitializeTokenBadge) GetTokenBadgeAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetAdminAccount sets the "admin" account.
func (inst *InitializeTokenBadge) SetAdminAccount(admin ag_solanago.PublicKey) *InitializeTokenBadge {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(admin).WRITE().SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *InitializeTokenBadge) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *InitializeTokenBadge) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *InitializeTokenBadge {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *InitializeTokenBadge) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst InitializeTokenBadge) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_InitializeTokenBadge,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst InitializeTokenBadge) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *InitializeTokenBadge) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.TokenMint is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.TokenBadge is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Admin is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *InitializeTokenBadge) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("InitializeTokenBadge")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("    tokenMint", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("   tokenBadge", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("        admin", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj InitializeTokenBadge) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *InitializeTokenBadge) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewInitializeTokenBadgeInstruction declares a new InitializeTokenBadge instruction with the provided parameters and accounts.
func NewInitializeTokenBadgeInstruction(
	// Accounts:
	tokenMint ag_solanago.PublicKey,
	tokenBadge ag_solanago.PublicKey,
	admin ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *InitializeTokenBadge {
	return NewInitializeTokenBadgeInstructionBuilder().
		SetTokenMintAccount(tokenMint).
		SetTokenBadgeAccount(tokenBadge).
		SetAdminAccount(admin).
		SetSystemProgramAccount(systemProgram)
}
